/**
 * Nomes "de gente" pra códigos que a fonte devolve sem nome (FIIs e ETFs vêm como "HGLG11" =
 * "HGLG11") e pra ativos de fora, que a fonte brasileira não lista. É o que permite alguém
 * digitar "kinea" ou "apple" sem saber o código — o motivo de o buscador existir.
 *
 * Lista curada, não exaustiva: quem procura um fundo pequeno ainda acha pelo código.
 */
export const KNOWN_FII: Record<string, string> = {
  HGLG11: "CSHG Logística",
  KNRI11: "Kinea Renda Imobiliária",
  MXRF11: "Maxi Renda",
  XPML11: "XP Malls",
  VISC11: "Vinci Shopping Centers",
  BTLG11: "BTG Pactual Logística",
  HGRE11: "CSHG Real Estate",
  KNCR11: "Kinea Rendimentos Imobiliários",
  KNIP11: "Kinea Índice de Preços",
  KNSC11: "Kinea Securities",
  CPTS11: "Capitânia Securities II",
  IRDM11: "Iridium Recebíveis Imobiliários",
  HGBS11: "Hedge Brasil Shopping",
  XPLG11: "XP Log",
  VILG11: "Vinci Logística",
  PVBI11: "VBI Prime Properties",
  RBRR11: "RBR Rendimento High Grade",
  RBRP11: "RBR Properties",
  BRCO11: "Bresco Logística",
  TRXF11: "TRX Real Estate",
  HFOF11: "Hedge Top FOFII 3",
  RECR11: "REC Recebíveis Imobiliários",
  VGIP11: "Valora CRI Índice de Preços",
  MALL11: "Malls Brasil Plural",
  GGRC11: "GGR Covepi Renda",
  ALZR11: "Alianza Trust Renda Imobiliária",
  BCFF11: "BTG Pactual Fundo de Fundos",
  RZTR11: "Riza Terrax",
  TGAR11: "TG Ativo Real",
  JSRE11: "JS Real Estate Multigestão",
  HSML11: "HSI Malls",
  LVBI11: "VBI Logístico",
  DEVA11: "Devant Recebíveis Imobiliários",
  VRTA11: "Fator Verità",
  HGCR11: "CSHG Recebíveis Imobiliários",
  BTCI11: "BTG Pactual Crédito Imobiliário",
  HGRU11: "CSHG Renda Urbana",
  TEPP11: "Tellus Properties",
  PLCR11: "Plural Recebíveis Imobiliários",
  SNCI11: "Suno Crédito Imobiliário",
  VINO11: "Vinci Offices",
  BRCR11: "BTG Pactual Corporate Office",
  PATL11: "Pátria Logística",
  RVBI11: "VBI Reits FoF",
  KFOF11: "Kinea Fundo de Fundos",
  BBPO11: "BB Progressivo II",
  SARE11: "Santander Renda de Aluguéis",
  URPR11: "Urca Prime Renda",
  HCTR11: "Hectare CE",
  VGHF11: "Valora Hedge Fund",
  CVBI11: "VBI CRI",
  RBVA11: "Rio Bravo Renda Varejo",
  RCRB11: "Rio Bravo Renda Corporativa",
  XPCI11: "XP Crédito Imobiliário",
  BTAL11: "BTG Pactual Agro Logística",
  GARE11: "Guardian Real Estate",
  LIFE11: "More Real Estate FoF",
};

export const KNOWN_ETF_BR: Record<string, string> = {
  BOVA11: "iShares Ibovespa",
  IVVB11: "iShares S&P 500",
  SMAL11: "iShares Small Cap",
  HASH11: "Hashdex Nasdaq Crypto Index",
  NASD11: "Trend Nasdaq-100",
  XINA11: "Trend China",
  DIVO11: "It Now Dividendos (IDIV)",
  GOLD11: "Trend Ouro",
  BOVV11: "It Now Ibovespa",
  PIBB11: "It Now IBrX-50",
  SPXI11: "It Now S&P 500",
  XFIX11: "Trend IFIX (fundos imobiliários)",
  IMAB11: "It Now IMA-B (Tesouro IPCA+)",
  B5P211: "It Now IMA-B 5 (IPCA+ curto)",
  IRFM11: "It Now IRF-M (prefixados)",
  FIXA11: "Trend Renda Fixa Pré",
  WRLD11: "Trend MSCI World (ações globais)",
  ACWI11: "Trend MSCI ACWI (ações do mundo todo)",
  EURP11: "Trend Europa",
  USDB11: "Trend Dólar",
  BITH11: "Hashdex Bitcoin",
  ETHE11: "Hashdex Ethereum",
  QBTC11: "QR Bitcoin",
  ISUS11: "iShares Sustentabilidade (ISE)",
  ECOO11: "It Now Carbono Eficiente (ICO2)",
  NDIV11: "Trend Dividendos Nasdaq",
  TECK11: "Trend Tecnologia EUA",
  SMAC11: "It Now Small Caps",
  BBSD11: "BB ETF S&P Dividendos",
  MATB11: "It Now Materiais Básicos",
  FIND11: "It Now Financeiro (IFNC)",
  DIVD11: "It Now IDIV (Dividendos)",
  JURO11: "Sparta Juro Real",
  IB5M11: "It Now IB5M+",
};

export const KNOWN_US_STOCK: Record<string, string> = {
  AAPL: "Apple",
  MSFT: "Microsoft",
  AMZN: "Amazon",
  GOOGL: "Alphabet (Google)",
  META: "Meta (Facebook, Instagram)",
  NVDA: "Nvidia",
  TSLA: "Tesla",
  "BRK.B": "Berkshire Hathaway",
  JPM: "JPMorgan Chase",
  V: "Visa",
  MA: "Mastercard",
  JNJ: "Johnson & Johnson",
  PG: "Procter & Gamble",
  KO: "Coca-Cola",
  PEP: "PepsiCo",
  DIS: "Disney",
  NFLX: "Netflix",
  NKE: "Nike",
  MCD: "McDonald's",
  WMT: "Walmart",
  COST: "Costco",
  HD: "Home Depot",
  XOM: "ExxonMobil",
  CVX: "Chevron",
  PFE: "Pfizer",
  MRK: "Merck",
  ABBV: "AbbVie",
  UNH: "UnitedHealth",
  LLY: "Eli Lilly",
  AMD: "AMD",
  INTC: "Intel",
  CSCO: "Cisco",
  ORCL: "Oracle",
  ADBE: "Adobe",
  CRM: "Salesforce",
  PYPL: "PayPal",
  UBER: "Uber",
  ABNB: "Airbnb",
  SBUX: "Starbucks",
  BA: "Boeing",
  CAT: "Caterpillar",
  MMM: "3M",
  IBM: "IBM",
  T: "AT&T",
  VZ: "Verizon",
  BAC: "Bank of America",
  WFC: "Wells Fargo",
  GS: "Goldman Sachs",
  MS: "Morgan Stanley",
  AXP: "American Express",
  MELI: "Mercado Livre",
  NU: "Nubank",
  PBR: "Petrobras (ADR)",
  VALE: "Vale (ADR)",
  ITUB: "Itaú Unibanco (ADR)",
  BBD: "Bradesco (ADR)",
  AVGO: "Broadcom",
  QCOM: "Qualcomm",
  TXN: "Texas Instruments",
  SHOP: "Shopify",
  SPOT: "Spotify",
  BABA: "Alibaba",
  TSM: "TSMC (Taiwan Semiconductor)",
  ASML: "ASML",
  NVO: "Novo Nordisk",
  LVMUY: "LVMH",
};

export const KNOWN_ETF_US: Record<string, string> = {
  VOO: "Vanguard S&P 500",
  IVV: "iShares Core S&P 500",
  SPY: "SPDR S&P 500",
  QQQ: "Invesco Nasdaq-100",
  VTI: "Vanguard Total Stock Market (EUA inteiro)",
  VT: "Vanguard Total World (mundo inteiro)",
  VXUS: "Vanguard Total International (fora dos EUA)",
  VEA: "Vanguard Developed Markets",
  VWO: "Vanguard Emerging Markets",
  SCHD: "Schwab US Dividend Equity",
  VYM: "Vanguard High Dividend Yield",
  VIG: "Vanguard Dividend Appreciation",
  BND: "Vanguard Total Bond Market",
  TLT: "iShares 20+ Year Treasury",
  GLD: "SPDR Gold",
  IAU: "iShares Gold",
  DIA: "SPDR Dow Jones",
  IWM: "iShares Russell 2000 (small caps)",
  ARKK: "ARK Innovation",
  VNQ: "Vanguard Real Estate (REITs)",
  XLK: "Technology Select Sector",
  XLF: "Financial Select Sector",
  XLE: "Energy Select Sector",
  SMH: "VanEck Semiconductor",
  IBIT: "iShares Bitcoin Trust",
  JEPI: "JPMorgan Equity Premium Income",
  VGT: "Vanguard Information Technology",
  IEFA: "iShares Core MSCI EAFE",
  EWZ: "iShares MSCI Brazil",
};

/**
 * Ações brasileiras pelo nome que se fala. A fonte traz a razão social ("BCO BRASIL S.A.",
 * "ITAU UNIBANCO HOLDING"), e ninguém procura assim: procura "Banco do Brasil", "Itaú".
 * A razão social continua valendo como apelido na busca.
 */
export const KNOWN_STOCK_BR: Record<string, string> = {
  PETR4: "Petrobras",
  PETR3: "Petrobras (ON)",
  VALE3: "Vale",
  ITUB4: "Itaú Unibanco",
  ITUB3: "Itaú Unibanco (ON)",
  BBDC4: "Bradesco",
  BBDC3: "Bradesco (ON)",
  BBAS3: "Banco do Brasil",
  SANB11: "Santander Brasil",
  BPAC11: "BTG Pactual",
  ITSA4: "Itaúsa",
  B3SA3: "B3 (a Bolsa)",
  ABEV3: "Ambev",
  WEGE3: "WEG",
  MGLU3: "Magazine Luiza",
  SUZB3: "Suzano",
  KLBN11: "Klabin",
  RENT3: "Localiza",
  RAIL3: "Rumo",
  EQTL3: "Equatorial Energia",
  ELET3: "Eletrobras",
  ELET6: "Eletrobras (PNB)",
  PRIO3: "PRIO (PetroRio)",
  RECV3: "PetroRecôncavo",
  HAPV3: "Hapvida",
  RDOR3: "Rede D'Or",
  LREN3: "Lojas Renner",
  GGBR4: "Gerdau",
  GOAU4: "Metalúrgica Gerdau",
  CSNA3: "CSN (Siderúrgica Nacional)",
  CMIN3: "CSN Mineração",
  USIM5: "Usiminas",
  CMIG4: "Cemig",
  SBSP3: "Sabesp",
  CPLE6: "Copel",
  TAEE11: "Taesa",
  TRPL4: "ISA Cteep",
  ALUP11: "Alupar",
  EGIE3: "Engie Brasil",
  ENGI11: "Energisa",
  CPFE3: "CPFL Energia",
  AURE3: "Auren Energia",
  ENEV3: "Eneva",
  VIVT3: "Vivo (Telefônica Brasil)",
  TIMS3: "TIM",
  EMBR3: "Embraer",
  AZUL4: "Azul",
  CYRE3: "Cyrela",
  MRVE3: "MRV",
  EZTC3: "EZTEC",
  DIRR3: "Direcional",
  CURY3: "Cury",
  NTCO3: "Natura",
  RADL3: "Raia Drogasil",
  CRFB3: "Carrefour Brasil",
  PCAR3: "Pão de Açúcar (GPA)",
  ASAI3: "Assaí",
  GMAT3: "Grupo Mateus",
  BEEF3: "Minerva",
  JBSS3: "JBS",
  BRFS3: "BRF",
  MRFG3: "Marfrig",
  MDIA3: "M. Dias Branco",
  CAML3: "Camil",
  SMTO3: "São Martinho",
  SLCE3: "SLC Agrícola",
  AGRO3: "BrasilAgro",
  RAIZ4: "Raízen",
  CSAN3: "Cosan",
  UGPA3: "Ultrapar (Ipiranga)",
  VBBR3: "Vibra Energia",
  BRKM5: "Braskem",
  BBSE3: "BB Seguridade",
  PSSA3: "Porto Seguro",
  CXSE3: "Caixa Seguridade",
  CIEL3: "Cielo",
  TOTS3: "Totvs",
  LWSA3: "Locaweb",
  INTB3: "Intelbras",
  POSI3: "Positivo",
  ALOS3: "Allos (shoppings)",
  MULT3: "Multiplan",
  IGTI11: "Iguatemi",
  VAMO3: "Vamos",
  MOVI3: "Movida",
  BRAP4: "Bradespar",
  PETZ3: "Petz",
  ARZZ3: "Arezzo",
  SOMA3: "Grupo Soma",
  VIVA3: "Vivara",
  ALPA4: "Alpargatas (Havaianas)",
  GRND3: "Grendene",
  CVCB3: "CVC",
  COGN3: "Cogna",
  YDUQ3: "Yduqs",
  SAPR11: "Sanepar",
  CSMG3: "Copasa",
  FLRY3: "Fleury",
  ODPV3: "Odontoprev",
  HYPE3: "Hypera",
  DXCO3: "Dexco (Duratex)",
  TUPY3: "Tupy",
  POMO4: "Marcopolo",
  RAPT4: "Randon",
  MYPK3: "Iochpe-Maxion",
  LEVE3: "Mahle Metal Leve",
  CEAB3: "C&A",
  SMFT3: "Smart Fit",
  BHIA3: "Casas Bahia",
  STBP3: "Santos Brasil",
  ECOR3: "Ecorodovias",
  CCRO3: "CCR (Motiva)",
  JHSF3: "JHSF",
  LOGG3: "LOG Commercial Properties",
  ANIM3: "Ânima Educação",
  SEER3: "Ser Educacional",
  BLAU3: "Blau Farmacêutica",
  ONCO3: "Oncoclínicas",
  CBAV3: "CBA (Alumínio)",
  AMER3: "Americanas",
};
