import { TITULOS_PADRAO, simuladoresDoTema, tarefasDoTema, inteiro, semDiaria, estadoParaFrase, type Voz } from "../voice-base";

/** "1 ativo" / "3 ativos": a mesma regra de plural do catálogo de importação. */
const s = (n: number) => (n === 1 ? "" : "s");

/**
 * Disciplina: o coach que cobra porque acredita que a pessoa consegue. Comando curto, número
 * na frente, sem rodeio. Meta continua "meta" (ela pediu: missão soa estranho), o resumo é "seu resultado", progresso é "seu avanço".
 * A cobrança ataca a decisão, nunca a pessoa. Emojis só 🔥 ⚡ 🎯 🏆 📈 ✓, e com parcimônia.
 * Caixa alta só em FOCO e EVOLUÇÃO.
 */
export const disciplina: Voz = {
  // Técnico da beira do campo, não consultor: energia, "bora", e sempre o próximo movimento.
  // Foi o ajuste da Dani: "tem pouca linguagem de bora, de o que eu preciso fazer".
  saudacao: (p, nome) => `Bora${nome ? `, ${nome}` : ""}! ${p === "noite" ? "Fecha o dia com o placar em dia." : "O que precisa ser feito hoje?"}`,
  subSaudacao: () => "Seu dinheiro não se organiza sozinho. Você organiza.",
  tituloPainel: "Seu resultado",
  rotuloResultado: "Guardado",
  fraseResultado: (estadoBruto, d) => {
    const estado = estadoParaFrase(estadoBruto, d.resultado);
    const v = inteiro(d.money, d.resultado);
    if (estado === "bom") return `${v} guardados. É assim que se constrói patrimônio. Bora manter. 🔥`;
    if (estado === "normal") return `${v} guardados. Dá pra mais. Bora subir a régua.`;
    if (estado === "ruim") return d.mesFechado ? "Gastou mais do que ganhou. Bora virar isso a partir de hoje: registra, corta, segue." : "Gastando mais do que ganhou. Ainda dá tempo. Bora segurar o resto do mês.";
    return null;
  },
  ritmo: { rapido: "⚠️ Saindo do plano. Bora segurar.", limite: "No limite. Segura firme.", dentro: "No plano ✓ Bora manter." },
  tituloOrcamento: () => "Plano do mês 🎯",
  fraseOrcamento: (d) => {
    if (d.situacao === "sem-plano") {
      return "Sem plano não tem jogo. Bora: define ali embaixo quanto vai gastar e eu te aviso antes de estourar.";
    }
    const pronta = semDiaria(d);
    if (pronta) return pronta;
    const porDia = inteiro(d.money, d.porDia!);
    if (d.situacao === "estourou") return `⚠️ Saiu do plano: ${inteiro(d.money, d.restante)} acima. Bora corrigir hoje.`;
    // "É pouco? Sim" só quando é pouco de verdade: gastando adiantado, com o que sobrou
    // espremido nos dias que faltam. Com folga, a frase seria mentira — e ela apontou isso.
    if (d.situacao === "adiantado") return `${porDia} até dia ${d.ultimoDia}. É pouco? Sim. Vai dar? Vai. Se mantiver o FOCO. Bora.`;
    if (d.situacao === "folgado") return `${porDia} por dia. Tem folga — bora guardar mais.`;
    return `${porDia} por dia até dia ${d.ultimoDia}. Mantém o FOCO. Bora.`;
  },
  mesVazio: "Nada registrado. Bora: dois minutos e o mês toma forma.",
  metaBatida: () => "Meta batida ✓ Você fez o que disse que faria. Bora pra próxima →",
  rodape: (estado) => (estado === "bom" ? "Bora. Mantém o FOCO." : estado === "normal" ? "Dá pra mais. Bora subir a régua." : estado === "ruim" ? "Corrige hoje. Bora." : null),
  nav: { metas: "Metas", flowTabs: ["Resultado", "Gastos", "Plano"] },
  titulos: {
    ...TITULOS_PADRAO,
    comparacao: (tipo, valor, mes) =>
      tipo === "sem" ? `Zero em ${mes}` : tipo === "igual" ? `Igual a ${mes}. Estável.` : tipo === "mais" ? `${valor} a mais que ${mes}. Bora segurar essa.` : `${valor} a menos que ${mes}. Isso é EVOLUÇÃO. Bora manter.`,
    simuladores: "Bora decidir com número, não com achismo",
    simuladoresSub: "Seis calculadoras. Cada uma responde uma decisão que você vai ter que tomar.",
    simulador: simuladoresDoTema({
      "/simuladores/financiar-vs-alugar": { subtitle: "Financiar ou alugar e investir a diferença. A conta decide, não a vontade." },
      "/simuladores/amortizar-vs-investir": { subtitle: "Sobrou dinheiro. Quita ou investe? Faz a conta antes de gastar." },
      "/simuladores/consorcio": { subtitle: "Consórcio ou financiamento. O custo real dos dois, lado a lado." },
      "/simuladores/marcacao-mercado": { subtitle: "Vender o título prefixado antes do vencimento: lucro ou prejuízo? Vê o número antes de decidir." },
      "/simuladores/carro": { subtitle: "Assinar ou comprar 0km. Em 24 meses, qual pesa menos." },
      "/simuladores/vale-a-pena": { subtitle: "Quantas horas de trabalho custa. Depois decide." },
    }),
    registrar: "Bora registrar",
    registrarNovo: "Bora: registra o que aconteceu",
    registrarFalar: "Fala o lançamento",
    registrarImportar: "Manda o extrato",
    lancamentoSalvo: "Registrado ✓ Boa! Próximo.",
    // Coach. Comando curto, número na frente, adjetivo só sobre a decisão. Poucos emojis:
    // 🔥 ⚡ 🎯 🏆 📈 ✓. Caixa alta só em FOCO e EVOLUÇÃO.
    visaoGeral: "Seu resultado no ano",
    visaoGeralSub: "{ano} até aqui. Bora ver o que os números dizem.",
    patrimonio: "Patrimônio construído",
    rendaNoAno: "Entrou",
    gastosNoAno: "Saiu",
    sobrouNoAno: "Ficou com você",
    sobrouNoAnoDica: (cem, manteve, pct) =>
      pct >= 20 ? `De cada ${cem}, ${manteve} ficaram. É assim que se constrói patrimônio. Bora manter. 🔥`
      : pct > 0 ? `De cada ${cem}, ${manteve} ficaram. Dá pra mais. Bora subir a régua.`
      : "Nada ficou este ano. Bora virar isso a partir de hoje.",
    statusModulos: "Suas metas",
    modReserva: "Reserva",
    modMetas: "Metas",
    modAposentadoria: "Liberdade",
    modDividendos: "Renda passiva (30 dias)",
    economiaNoMes: "Guardado no mês",
    economiaAbaixo: "Dentro do plano ✓",
    economiaAcima: "Fora do plano. Bora corrigir agora.",
    categoriaEstourou: "Onde você saiu do plano",
    categoriaEstourouDica: (pct) => `${pct} acima do combinado. Bora segurar essa.`,
    nenhumaEstourou: "Nenhuma fora do plano. Disciplina ✓",
    economizouMaisEm: "Onde você segurou",
    economizouMaisEmDica: (pct) => `${pct} abaixo do plano. Isso é EVOLUÇÃO. Bora repetir.`,
    semLancamento: "Sem registro. Bora registrar.",
    soGastos: "Gastos",
    soGastosSub: "Cada gasto foi uma decisão. Aqui estão todas.",
    orcamento: "Plano do mês 🎯",
    orcamentoSub: "O plano que você fez, e o quanto está cumprindo.",
    orcamentoPorCategoria: "Plano por categoria",
    paraOndeFoi: "Pra onde foi o dinheiro",
    ritmoDoMes: "Ritmo",
    anoMesAMes: "O ano, mês a mês",
    caiuNaConta: "Renda passiva caiu",
    caiuNaContaSub: "Seus ativos pagaram. Registra como renda e segue.",
    planejamento: "Plano",
    poupanca: "Guardado",
    metas: "Metas 🎯",
    metasSub: "Cada meta tem prazo e um número por mês. Cumpre o número, a meta se cumpre. Bora.",
    metasVazio: "Nenhuma meta. Bora criar a primeira — dois minutos.",
    reserva: "Reserva ⚡",
    reservaSub: "O que te mantém de pé quando o imprevisto chega. Não é opcional.",
    reservaMeta: "Alvo da reserva",
    reservaAtual: "Reserva hoje",
    reservaTempo: "Tempo até completar",
    reservaProjecao: "Até completar",
    aposentadoria: "Liberdade 🏆",
    aposentadoriaSub: "Do acúmulo até viver de renda. O caminho inteiro, sem atalho.",
    aposentadoriaWizardSub: "Monta o plano. Poucos passos, decisão firme.",
    metaStatus: { ahead: "Adiantada 🔥", onTrack: "No ritmo ✓", behind: "Atrasada. Bora retomar.", achieved: "Cumprida 🏆" },
    metaGuardar: (v) => `Sua meta do mês: guardar ${v}. Bora.`,
    metaMeses: (n) => `${n} ${n === 1 ? "mês" : "meses"}. Cada um conta.`,
    metaAporteFeito: (mes) => `Aporte de ${mes} feito ✓ Boa!`,
    metaAporteToast: (mes) => `Aporte de ${mes} registrado. Meta andando. Bora pra próxima.`,
    metaMarcar: (mes) => `Cumpri ${mes}`,
    splitTitulo: (mes) => `Pra onde vai o aporte de ${mes}`,
    splitSub: (v) => `${v} por mês, do seu plano. Reserva primeiro, depois as metas por prazo.`,
    splitVazioTitulo: "Pra onde vai o aporte?",
    splitVazioSub: "Diz no plano quanto guarda por mês. O app divide entre reserva e metas.",
    formCusto: "Quanto custa um mês da sua vida?",
    formCustoHint: "É isso que a reserva cobre enquanto a renda não volta. Número real.",
    formMeses: "Quantos meses quer ter cobertos?",
    formMesesHint: "Renda estável: 6. Autônomo ou renda variável: 12.",
    formJaTenho: "Já guardado",
    apSeNadaMudar: (idade) => `Se nada mudar, aos ${idade} anos você terá`,
    apDaPe: "Fecha ✓",
    apNaoDaPe: "Ainda não fecha. Bora ajustar agora.",
    apVereditoIntro: "É o que esse patrimônio paga sem comer o principal. Você quer gastar",
    apBolso: (anos) => `Do seu bolso, em ${anos} anos`,
    apJurosNota: (um, mais) => `Pra cada ${um} seu, os juros põem ${mais}. Tempo é o seu maior ativo.`,
    apEditar: "Ajustar meus dados",
    apProjecao: "Trajetória do patrimônio",
    apAcumuloDesc: "você ainda aporta, o patrimônio só cresce.",
    apUsufrutoDesc: "os aportes param, os saques começam.",
    apAnoAAno: "Ver ano a ano",
    planTabs: ["Metas", "Reserva", "Liberdade"],
    visaoGeralLink: "Ver o mês →",
    semanaTitulo: "Bora: sua semana",
    tarefa: tarefasDoTema({
      lancamentos: (n, feita) => (feita ? `Gastos da semana registrados (${n ?? 0}) ✓ Boa!` : "Bora registrar os gastos da semana"),
      "orcamento-definir": () => "Bora definir quanto vai gastar por categoria",
      "orcamento-estourado": (n, _f, pl) => `Bora corrigir ${n ?? 1} categoria${pl ? "s" : ""} fora do plano`,
      "orcamento-ok": () => "Plano do mês sob controle ✓",
      "reserva-configurar": () => "Bora definir sua reserva. Hoje.",
      "reserva-completar": (n) => `Bora avançar na reserva (${n ?? 0}%)`,
      "reserva-ok": () => "Reserva completa 🏆",
      "meta-criar": () => "Bora criar sua primeira meta",
      "meta-atrasada": (n, _f, pl) => `Bora retomar ${n ?? 1} ${pl ? "metas atrasadas" : "meta atrasada"}`,
      "meta-ok": () => "Metas no ritmo ✓",
      aporte: (_n, feita) => (feita ? "Aporte do mês feito ✓ Boa!" : "Bora separar o aporte do mês. Agora."),
      "reuniao-casal": () => "Bora: 15 min pra olhar os gastos do mês, os dois juntos",
    }),
    navSecao: (b, t) =>
      ({ "/dashboard": "Seu resultado", "/planejamento": "Metas", "/carteira": "Patrimônio", "/divisao": "Quem paga quanto", "/investir": "Vale investir?" } as Record<string, string>)[b] ?? t,
    navFilho: (h, t) =>
      ({ "/planejamento/metas": "Metas", "/planejamento/reserva-emergencia": "Reserva", "/planejamento/acumulo": "Liberdade", "/orcamento": "Plano" } as Record<string, string>)[h] ?? t,
    carteira: "Patrimônio",
    carteiraSub: "Cada ativo com um objetivo. O que não tem objetivo, não tem direção.",
    carteiraLink: "Ver por objetivo →",
    carteiraVazio: "Nenhum ativo. Cadastra o primeiro e o patrimônio começa a existir aqui.",
    porObjetivo: "Patrimônio por objetivo",
    porObjetivoSub: "Onde cada real está, e o atual × ideal por classe.",
    objReserva: "Reserva",
    objLiberdade: "Liberdade",
    objSem: "Sem objetivo",
    objSemMetaHint: "Sem alvo cadastrado na Reserva",
    secaoMetas: "Metas",
    estrategiaVsAlvo: "Carteira atual × alvo",
    alocacaoPorClasse: "Atual × ideal por classe",
    estrategia: "Estratégia",
    estrategiaSub: "Define o alvo por classe (somando 100%). É a régua da carteira, independente do ideal de cada ativo.",
    contribTitulo: (mes) => `Aporte de ${mes}. Quanto?`,
    contribSub: "Onde o aporte entra pra carteira voltar ao alvo.",
    contribVazio: "Carteira vazia: a divisão segue só a estratégia.",
    contribSemEstrategiaTitulo: "Aporte do mês. Onde entra?",
    contribSemEstrategiaSub: "Com estratégia definida, o app diz quanto vai pra cada tipo até a carteira bater o alvo. Três perguntas.",
    contribDefinir: "Definir estratégia →",
    divTitulo: (total) => `Renda passiva a caminho · ${total}`,
    compHint: "O tracinho é o alvo. O que está atrás dele é o que comprar no próximo aporte.",
    compDeveriaTer: "Alvo",
    objNenhumTitulo: "Nenhum ativo tem objetivo.",
    objNenhumTexto: (valor) =>
      `${valor} em "sem objetivo". Diz o que cada ativo é — reserva, liberdade ou uma meta — e esta tela passa a responder quanto falta, não só a somar.`,
    objNenhumLink: "Dar objetivo aos ativos →",
    campeaoTitulo: "O maior gasto do mês",
    campeaoPergunta: (_k, label) => `Quanto foi em ${label.toLowerCase()}? Número na mesa.`,

    // ── Simuladores ──────────────────────────────────────────────────────────────────────
    simContinuar: "Próximo",
    simVerResultado: "Ver o veredito",
    simResultado: "Veredito",
    simSalvarBotao: "Guardar esta simulação",
    simSalva: "Simulação guardada ✓",
    simSalvaToast: "Guardada ✓ Fica na lista de simuladores.",
    simSalvarErro: "Não consegui guardar esta simulação. Tenta de novo.",
    simSalvarNomePlaceholder: "Dá um nome (opcional)",
    simSalvasTitulo: "Suas simulações",
    simFinValorImovelHint: "O preço do imóvel que você quer comprar.",
    simFinEntradaHint: "O que você paga à vista. O resto é o valor financiado.",
    simFinVenceFinanciar: "Financiar vence",
    simFinVenceAlugar: "Alugar e investir vence",
    simAmortSaldoHint: "O que você ainda deve no financiamento hoje.",
    simAmortValorDisponivelHint: "O dinheiro que sobrou. Vai amortizar ou investir — um dos dois.",
    simAmortVenceAmortizar: "Amortiza",
    simAmortVenceInvestir: "Investe",
    simAmortVeredito: (vencedor, valor) => `${vencedor === "AMORTIZAR" ? "Amortizar" : "Investir"} rende ${valor} a mais. A conta decidiu.`,
    simConsVenceConsorcio: "Consórcio vence",
    simConsVenceFinanciamento: "Financiamento vence",
    simConsVeredito: (vencedor, valor) => `${vencedor === "CONSORCIO" ? "Consórcio" : "Financiamento"} sai ${valor} mais barato. Decisão tomada.`,
    simMarcLucro: "Vender agora dá lucro",
    simMarcPrejuizo: "Vender agora dá prejuízo",
    simMarcSub: "Levar até o vencimento zera esse risco.",
    simCarroVenceAssinar: "Assinar vence",
    simCarroVenceComprar: "Comprar vence",
    simCarroVeredito: (vencedor, valor) => `${vencedor === "ASSINATURA" ? "Assinar" : "Comprar"} sai ${valor} mais barato em 24 meses. Número na mesa.`,
    simValePasso1Titulo: "Quanto custa?",
    simValePasso1Sub: "O preço do que você está pensando em comprar.",
    simValeSemRenda: (mes) => `Sem renda registrada em ${mes}.`,
    simValePasso2Titulo: "Que tipo de gasto é?",
    simValePasso2Sub: "Isso muda a conta do que você deixa de ganhar.",
    simValeCompraUnicaDesc: "Pontual: uma roupa, um eletrônico, uma viagem.",
    simValeHabitoDesc: "Repete todo mês: assinatura, delivery, café.",
    simValeTempoUnico: "Horas de trabalho que isso custa",
    simValeTempoMensal: "Horas de trabalho por mês",
    simValeHorizontePergunta: "Se não comprar e investir, por quanto tempo?",
    simValeBarraInvestirUnico: "Investir",
    simValeBarraInvestirMensal: "Segurar e investir",
    simValeVeredito: (valor) => `Investindo, ${valor} a mais no fim. Decide.`,
    simValeEscolhaComprar: "Prioridade sua? Então cabe no plano do mês. Confere antes de pagar.",
    simValeEscolhaNao: "Decisão certa. Isso te aproxima das metas. 📈",
    simValeEscolhaDuvida: "Volta aqui quando decidir. Dúvida já é sinal: pensa mais um pouco antes de gastar.",

    // ── Formulários ──────────────────────────────────────────────────────────────────────
    formMetaNova: "Nova meta",
    formMetaEditar: "Editar meta",
    formMetaAdicionar: "Criar meta",
    formMetaCriada: "Meta criada ✓ Agora é cumprir.",
    formMetaAtualizada: "Meta atualizada ✓",
    formMetaNome: "Nome da meta",
    formMetaValorAlvo: "Alvo",
    formMetaMesAno: "Prazo (mês/ano)",
    formAtivoAdicionado: "Ativo adicionado ✓",
    formAtivoAtualizado: "Ativo atualizado ✓",
    formAtivoObjetivos: { OUTRO: "Outro", RESERVA_EMERGENCIA: "Reserva", LIBERDADE_FINANCEIRA: "Liberdade", META: "Meta" },
    formAtivoMetaVinculada: "Meta vinculada",
    formAtivoValorAtualHint: "Deixa em branco: o app busca a cotação de hoje e multiplica pela quantidade.",
    formOrcSalvo: "Plano salvo pro ano inteiro. Agora é cumprir.",
    formOrcTitulo: "Monta o plano",
    formOrcSub: "Três perguntas. Parte das respostas o app já tirou dos seus lançamentos.",
    formOrcRendaSugestao: (mes, valor) => `${mes}: entraram ${valor}.`,
    formOrcQuantoGuardar: "Quanto você vai guardar?",
    formOrcCursoNota: (pct, liberdade) =>
      `No curso, a conta é ${pct}%: ${liberdade}% pra liberdade financeira e 8% pros sonhos. Quem está começando costuma conseguir 10% — se apertar, ajusta depois. Nada aqui é promessa.`,
    formOrcDividaTitulo: (valor) => `Divide os ${valor}`,
    formOrcPassou: (valor) => `Passou ${valor} do que sobra. Bora ajustar.`,
    formOrcSugerir: "Sugere pra mim",
    formOrcSugestaoNota: (moradia, alimentacao, saude, pct) =>
      `A sugestão segue a distribuição do curso: moradia ${moradia}% da renda, alimentação ${alimentacao}%, saúde ${saude}%, e por aí vai. Guardando menos que ${pct}% sobra folga; guardando mais, tudo encolhe junto. É ponto de partida: mexe à vontade.`,
    formOrcCustomNota: "Pet, academia, filhos: o que é grande na sua vida e não cabe nas de cima. O que vem uma vez por ano, divide por 12.",
    formOrcVerPlano: "Ver o plano →",
    formOrcProntoPlano: (ano) => `Pronto. Plano de ${ano} na mesa`,
    formOrcPraOndeNota: "Reserva primeiro, depois as metas por prazo. O resto fica livre.",
    formOrcEstourou: "As categorias somam mais do que sobra. Volta e ajusta, ou guarda menos.",
    formOrcSalvar: "Salvar o plano",
    formOrcAjustar: "Ajustar categorias",
    formOrcSemGasto: "zero mês passado",
    formReservaMediaSugestao: (n) => `Média dos seus últimos ${n === 1 ? "mês fechado" : `${n} meses fechados`}.`,
    formReservaCarteiraSugestao: "Na carteira, isso está marcado como reserva.",
    formApVidaHelp: "O gasto mensal que você quer bancar só com renda passiva, em dinheiro de hoje.",
    formApOutrasPergunta: "Já tem outras rendas?",
    formApOutrasHelp: "Aluguel, INSS, pensão: o que continua entrando quando você parar de trabalhar. Zero se não tiver.",
    formApInvestidoPergunta: "Quanto já tem investido?",
    formApInvestidoHelp: "Tudo que já está aplicado hoje e vai compor esse patrimônio.",
    formApAportePergunta: "Quanto aporta por mês?",
    formApAporteHelp: "O valor que você consegue investir todo mês na fase de acúmulo. Número real, não desejo.",
    formApIdadeHelp: "Idade objetivo é quando você quer a independência. Expectativa de vida é opcional.",
    formApPremissasHelp: "Já vieram preenchidas com valores comuns. Ajusta se quiser. Taxas ao ano.",
    formApVerPlano: "Ver o plano",
    formApGuardarPergunta: "Quanto guarda por mês?",
    formApPremissasSub: "Os números técnicos. Já preenchidos — abre só se for mexer.",
    formApPremissasNota: "Nenhum destes números é promessa: é o cenário que você escolhe simular.",
    formEstSalva: "Estratégia salva ✓ Agora a carteira tem alvo.",
    formEstPronto: "Ou parte de um perfil pronto (ajusta depois)",
    formEstComoFicaria: "Como a carteira ficaria",
    formLancDescricaoPlaceholder: "Ex.: o lugar, o que comprou",
    formLancMetaVinculada: "Meta vinculada (opcional)",
    formLancLancar: "Registrar",

    // ── Importação e a gaveta Registrar ──────────────────────────────────────────────────
    impVozSegure: "Segura pra falar",
    impVozSolte: "Solta pra transcrever",
    impVozNaoSuportado: "Seu navegador não suporta reconhecimento de voz. Usa a opção de digitar.",
    impVozNaoEntendi: "Não entendi. Fala de novo.",
    impVozErroPermissao: "Libera o microfone nas configurações do navegador e tenta de novo.",
    impVozErroSemFala: "Não te ouvi. Aproxima o microfone e tenta de novo.",
    impVozErroRede: "A conexão caiu durante a gravação. Tenta de novo.",
    impVozErroGenerico: "Não deu pra gravar agora. Tenta de novo.",
    impVozSafariDica: "Autorizar o microfone toda vez cansa? O Safari pergunta de novo a cada visita.",
    impLendoArquivo: "Lendo o arquivo...",
    impErroEnvio: "Não consegui enviar o arquivo. Confere a internet e tenta de novo.",
    impErroSalvar: "Não consegui salvar. Confere a internet e tenta de novo.",
    impProtegido: "Arquivo protegido por senha",
    impDesbloquear: "Desbloquear e seguir",
    impArquivoGrande: "Arquivo grande demais (máx. 4 MB). Exporta um período menor, ou salva em Excel (.xlsx) ou CSV — pesa muito menos que PDF.",
    impOQueSubindo: "O que é esse arquivo?",
    impExtratoDica: "Entrada vira renda, saída vira gasto, pelo sinal do valor.",
    impFaturaDica: "Toda linha entra como gasto (compras do cartão).",
    impFaturaMes: "Fatura de qual mês?",
    impFaturaMesDica: (mes) => `Todas as compras desta fatura entram em ${mes}, mesmo as do mês anterior (o fechamento costuma cruzar dois meses).`,
    impEscolherExtrato: "Escolher o extrato",
    impSenhaDicaBanco: "Quase sempre é o seu CPF, só os números. Se não for, a senha está no e-mail em que o banco mandou o arquivo.",
    impPareceFaturaAviso: "Importa como extrato e cada compra do cartão vira renda no seu mês.",
    impPareceExtratoAviso: "Importa como fatura e cada entrada da conta vira gasto.",
    impQualCategoria: "Categoria?",
    impNovaCategoriaDica: "A categoria nova já entra no plano do mês. Define um valor pra ela.",
    impSemCategoriaSub: (n, soma) => `${n === 1 ? "Não entra" : "Não entram"} na importação. Some ${soma}. Resolve.`,
    impNumerosErradosDica:
      "Confere a lista abaixo antes de confirmar. Se estiver errado mesmo, fala com a gente — já guardamos uma cópia do arquivo e ensinamos o app a ler esse banco.",
    impLinhasLidas: (lidas, total) => `Li ${lidas} de ${total} linhas com valor.`,
    impCoberturaBaixa: "Menos da metade das linhas com valor virou lançamento. Confere se falta alguma coisa.",
    impSomaDiferente: (abaixo, diferenca) =>
      `A soma lida ${abaixo ? "está" : "passa"} ${diferenca} ${abaixo ? "abaixo" : "acima"} do total impresso na fatura. Pode faltar (ou sobrar) linha. Confere.`,
    impRepetidosDica: "Mesma data, valor e descrição mais de uma vez. Compra de verdade, mantém; arquivo repetindo, deixa só uma.",
    impImportadosSucesso: (n) => `${n} lançamentos importados ✓ Mês registrado.`,
    impToastImportados: (n) => `${n} lançamentos importados ✓`,
    impPagamentoFatura: (n) =>
      `Achei ${n === 1 ? "este lançamento" : "estes lançamentos"} no seu extrato que ${n === 1 ? "pode ser" : "podem ser"} o pagamento desta fatura. Remove pra não contar o gasto duas vezes?`,
    impRemovidoExtrato: "Removido do extrato ✓",
    impCarteiraArquivoGrande: "Arquivo grande demais (máx. ~7 MB). Exporta um relatório menor e tenta de novo.",
    impSenhaDicaCorretora: "Digita a senha do arquivo (a mesma que a corretora pede pra abrir). Ela é usada só pra abrir e não fica salva.",
    impCarteiraEmDia: (n) => `Carteira em dia com esse extrato: ${n} ativo${s(n)} conferido${s(n)}, nenhuma mudança. ✓`,
    impCarteiraFeito: (criados, atualizados) =>
      [criados > 0 ? `${criados} novo${s(criados)} na carteira` : null, atualizados > 0 ? `${atualizados} atualizado${s(atualizados)}` : null]
        .filter(Boolean)
        .join(" · ") || "Nada pra mudar. Carteira já estava em dia ✓",
    impIrpfSelecioneUm: "Seleciona ao menos um ativo pra aplicar o preço médio.",
    impIrpfIntro: [
      "Sua declaração de IR tem o ",
      "preço médio",
      " de cada ação e FII (o custo de aquisição), que os extratos de corretora não trazem. Sobe o PDF do recibo da declaração e eu preencho o investido de cada ativo, pra o lucro/prejuízo sair certo.",
    ],
    impIrpfConfira: "Confere o ativo da sua carteira em cada linha (as que a declaração só traz o nome da empresa vêm sem casar — escolhe à mão ou deixa de fora).",
    impIrpfEncontrei: (n) => `Achei ${n} ativo${s(n)} com preço médio.`,
    impIrpfConcluido: (n) => `Preço médio preenchido em ${n} ativo${s(n)} ✓ Agora o lucro/prejuízo deles calcula certo.`,
    impRepeteSub: "Estava nos meses anteriores e ainda não está neste. Um toque registra.",
    impRepeteLancar: "Registrar",
    impRepeteLancado: "Registrado ✓",
    impRepeteLancadoAteDezembro: "Registrado neste mês e nos seguintes até dezembro ✓",
    impRepeteErro: "Não consegui registrar. Tenta de novo.",
    impResumoPronto: "Seu resultado do mês está pronto",
    impResumoProntoSub: "Os números do mês. Sem rodeio.",
    impStoryTitulo: "Resultado do mês",
    impStorySub: "O que você fez com o dinheiro este mês.",
    impStoryGastou: "Este mês saiu",
    impStoryMaiorParte: "A maior parte foi pra",
    impStoryComparado: "Comparado com o mês passado, você gastou",
    impStoryDiaEconomico: "Seu dia mais disciplinado da semana foi",
    impStoryDiaGastador: "O dia em que mais saiu dinheiro foi",
    impStoryDesdeQueChegou: (meses, positivo) =>
      `Desde que você chegou aqui (${meses} ${meses === 1 ? "mês" : "meses"}),${positivo ? " ficou com você" : " o saldo ficou"}`,
    impStoryAcumuladoRuim: "Mês a mês isso vira. O primeiro passo é encarar o número. Corrige hoje.",
    impStoryProjecaoUnica: "Se investisse hoje, de uma vez, tudo que já juntou, em 10 anos vira até…",
    impStoryProjecaoMensal: "Mantendo o que você guarda em média todo mês, reinvestindo, em 10 anos vira até…",
    impStoryNoBolso: "Ficou com você desde o início",
    impStoryPotencial: "Potencial em 10 anos mantendo o que guarda em média",
    impStoryCompartilhar: "Compartilhar resultado",
    impShareTitulo: "Meu resultado do mês",
    impShareImagemTitulo: ["Meu resultado", "do mês"],
    impShareFicouNoBolso: "Ficou comigo desde o início",
    impSharePotencial: "Potencial em 10 anos mantendo o que guardo em média",
    impShareTexto: (periodo, gastei, positivo, saldo, potencial) =>
      [
        `Meu resultado do mês (${periodo}):`,
        `• Gastei ${gastei}`,
        `• ${positivo ? "Ficou comigo" : "Saldo"} desde o início: ${saldo}`,
        `• Potencial em 10 anos: ${potencial}`,
      ].join("\n"),

    // ── Shell: primeiros passos, tour, cartões do Fluxo, avisos ──────────────────────────
    uiPrimeirosPassos: "Começa por aqui",
    uiPassoRegistrar: "Registra o primeiro gasto ou renda",
    uiPassoOrcamento: "Define o plano do mês",
    uiPassoCarteira: "Monta o patrimônio",
    uiTourBoasVindasTitulo: "Boas-vindas ao SPI Finance",
    uiTourBoasVindasTexto: "Tour rápido: onde fica cada coisa, botão por botão. Pula quando quiser.",
    uiTourRegistrarTexto: "Aqui você registra tudo: digita o gasto, fala por áudio ou importa o extrato do banco. Começa sempre por ele.",
    uiTourFluxoTitulo: "Aqui é o seu resultado",
    uiTourFluxoTexto: "O mês num lugar só: renda, gastos e o plano por categoria, com alerta quando você sai do plano.",
    uiTourMetasTitulo: "Aqui são as Metas",
    uiTourMetasTexto: "Cria metas (viagem, casa), a reserva e a liberdade. O app diz quanto guardar por mês. Você cumpre.",
    uiTourCarteiraTitulo: "Aqui é o Patrimônio",
    uiTourCarteiraTexto: "Seus investimentos e o lucro de cada um. Dá pra puxar o preço médio direto da declaração de Imposto de Renda.",
    uiTourMaisTexto: "Seu resultado no ano, Simuladores e Análises ficam neste menu.",
    uiTourFimTitulo: "Pronto. Agora é com você 🔥",
    uiTourFimTexto: "Toca no + e registra o primeiro lançamento. Em segundos o mês toma forma.",
    uiTourAvancar: "Próximo",
    uiFluxoTituloFuturo: (mes) => `O que já está marcado pra ${mes}`,
    uiFluxoTituloCorrente: (mes) => `${mes} até aqui`,
    uiFluxoTituloFechado: (mes) => `${mes}, fechado`,
    uiFluxoDicaCorrente: "A faixa entre as linhas é o que sobrou até aqui",
    uiFluxoDicaFechado: "A faixa entre as linhas é o que sobrou",
    uiRendaDividida: "Pra onde a renda foi",
    uiRendaGastouAMais: (valor) => `Saiu ${valor} a mais do que entrou este mês. Corrige.`,
    uiRendaManteve: (pct) => `Você manteve **${pct}** do que entrou (aportes e sobra).`,
    uiSetaCompara: "A seta compara com o mês passado. Abaixo de 8% não aparece: é oscilação normal.",
    uiHeatmapDica: "Um quadradinho por dia, mais forte onde saiu mais.",
    uiHeatmapPico: (dia, valor) => `Dia que mais saiu: ${dia} · ${valor}`,
    uiRestaurarFalhou: "Não consegui restaurar. Registra de novo à mão.",
    uiInstalarConviteTitulo: "Instala no celular",
    uiInstalarConviteSub: "Tela cheia, ícone próprio. Um toque a menos entre você e o registro.",
    uiErroTitulo: "Deu erro por aqui",
    uiErroTexto: "Erro nosso, não seu. Seus dados estão seguros. Recarrega; se continuar, sai e entra de novo.",
    uiNaoEncontradoTexto: "Confere o endereço ou volta pro início. O plano está te esperando lá.",
    uiNaoEncontradoVoltar: "Voltar pro início",

    // ── Configurações e viagem ───────────────────────────────────────────────────────────
    cfgPerfilSub: "Seus dados.",
    cfgNotificacoesSub: "Avisos no celular, o resultado do mês por e-mail e o que aparece em Análises.",
    cfgResumoEmail: "Resultado do mês por e-mail",
    cfgResumoEmailDica: "Uma vez por mês, no começo: quanto entrou, quanto saiu e o que mudou.",
    cfgAlertasOrcamento: "Alertas do plano do mês",
    cfgAlertasOrcamentoDica: "Categoria com 80% do plano gasto e ainda metade do mês pela frente, ou já fora do plano. Chega no celular (se ligado) ou por e-mail.",
    cfgMetasAtrasadas: "Metas atrasadas",
    cfgMetasAtrasadasDica: "Quando uma meta fica atrás do ritmo. Um aviso por meta por mês.",
    cfgPushDica: "Uma mensagem no celular, como as de um app: categoria perto de sair do plano com metade do mês pela frente, ou meta atrasada. Sem e-mail.",
    cfgPushLigadoToast: "Avisos ligados neste aparelho ✓",
    cfgPushFalhouToast: "Não consegui ligar os avisos aqui. Tenta de novo.",
    cfgConexoesDesligada: "A conexão com bancos ainda não está ligada neste app. Por enquanto, o caminho é Registrar › Importa o extrato.",
    cfgDadosSub: "Exporta seus dados ou exclui a conta.",
    cfgExportFalhou: "Não consegui exportar. Tenta de novo.",
    cfgTaxaAdicionadaToast: "Taxa adicionada ✓",
    cfgTaxasVazio: "Nenhuma taxa cadastrada.",
    cfgPerfisSub: "Cada perfil é um dinheiro separado: lançamentos, metas e carteira não se misturam.",
    cfgPerfisCriadoToast: (nome) => `Perfil ${nome} criado ✓ Você já está nele.`,
    cfgPerfisFalhou: "Não consegui fazer isso agora. Tenta de novo.",
    viagemSub: "Calcula quanto custa o destino e transforma em meta com aporte mensal.",
    viagemVazio: "Busca o primeiro destino acima. Dá pra somar vários lugares na mesma viagem e dizer quantos dias fica em cada um.",
    viagemNenhumDestino: "Nenhum destino encontrado. Tenta outro nome ou o país.",
    viagemMediaDica: "Estes valores são a média pra uma viagem como a sua. Orçamento diferente? Toca no número e ajusta — o total recalcula na hora.",
    viagemPorPessoa: (porPessoa, porMes, meses) =>
      `${porPessoa} por pessoa · guardando ${porMes}/mês, você chega lá em ${meses} ${meses === 1 ? "mês" : "meses"}. Cumpre o número.`,
    viagemMetaCriadaToast: "Meta da viagem criada ✓ Está em Metas.",
    viagemVerMeta: "Ver a meta em Metas",
    viagemCriarMeta: "Criar meta desta viagem",
    viagemCriandoMeta: "Criando meta...",

    // ── Carteira, análises, página da meta e gráficos ──────────────────────────────────
    cartSuaCarteira: (n) => `Seu patrimônio · ${n} ativo${s(n)}`,
    cartCotacoesAtualizadas: (n) => `${n} cotações atualizadas ✓`,
    cartTracinhoAlvo: "O tracinho é o alvo. O que está atrás dele é o que comprar no próximo aporte.",
    cartNaEstrategia: "Carteira no alvo ✓",
    cartDefinaQuanto: "Define quanto quer em cada tipo e compara com a carteira de hoje.",
    cartPraFicarNoAlvo: "Pra voltar ao alvo:",
    cartSuasMetas: "Suas metas",
    cartObjMeta: "Meta",
    cartMetaPrefixo: (nome) => `Meta: ${nome}`,
    cartAporteProntoTitulo: "Pronto. Tudo batendo ✓",
    cartMetasAndaram: (lista) => `Metas que andaram junto: ${lista}.`,
    cartCadastreAtivo: "Cadastra o ativo que recebeu esse dinheiro. Aí a carteira bate com o que você lançou no mês.",
    cartDigaQuanto: "Diz quanto entrou em cada ativo.",
    cartToquePraDizer: "Toca pra dizer em quais ativos entrou.",
    cartEnquantoNaoDisser: (meta) => `Enquanto não disser, a carteira fica com um valor e o mês com outro${meta ? `, e a meta ${meta} não anda` : ""}.`,
    cartMetaDoAtivo: (nome) => `meta: ${nome}`,
    cartPassouDoAporte: (valor) => `Passou ${valor} do que você aportou. Bora ajustar.`,
    cartTudoDistribuido: "Tudo distribuído ✓",
    cartAporteAplicado: "Carteira e metas atualizadas com o aporte do mês ✓",
    cartAtualizarCarteira: "É isso. Atualizar carteira",
    cartAtivoNaoEstaAqui: "O ativo não está aqui? Cadastra primeiro",
    cartDaMeta: (pct, valor) => `${pct} da meta (${valor})`,
    cartSemAtivos: "Nenhum ativo cadastrado.",
    cartSemEstrategiaDepois: ". Define os percentuais-alvo por classe pra ver aqui o comparativo e o rebalanceamento.",
    fichasSub: "Onde você está e o que precisa de ação agora.",
    fichasInsightsVazio: "Cadastra o plano do mês, metas, reserva e uma estratégia de carteira. Os insights automáticos começam a aparecer aqui.",
    fichasAtencaoTitulo: "O que precisa de ação",
    fichasAcoesSub: "Digita o nome ou o código e o app lê os números.",
    fichasFiisSub: "Digita o nome ou o código e o app lê o fundo.",
    fichasStocksSub: "Ações no exterior: digita o nome ou o código e o app lê.",
    fichasEtfsSub: "Digita o nome ou o código e o app lê o fundo.",
    fichasAnalisesVazio: "Nenhuma análise. Digita um código acima e o app lê os números.",
    fichasFichaCriada: "Ficha criada ✓",
    fichasConcentra: "Comprar mais te concentra além do que a estratégia pede. Bora conferir o plano antes.",
    metaBreadcrumbPlanejamento: "Metas",
    metaRitmo: { NOT_STARTED: "Sem prazo hábil", ON_TRACK: "No ritmo ✓", BEHIND: "Atrasada. Bora retomar.", ACHIEVED: "Cumprida 🏆" },
    metaTrajetoria: "Trajetória até a meta",
    grafMetaLinha: (valor) => `alvo ${valor}`,
    grafNenhumGasto: "Zero gasto neste período.",

    // Casal: quem paga quanto. Rendas diferentes pedem proporção, não 50/50 — a conta decide.
    casTitulo: "Quanto cada um paga",
    casSub: "Rendas diferentes pedem divisão proporcional, não 50/50. Quem ganha mais, paga mais — na mesma proporção. Faz a conta, não o achismo.",
    casRendaA: "Quanto um dos dois recebe por mês",
    casRendaAHint: "Renda líquida de uma pessoa do casal.",
    casRendaB: "Quanto o outro recebe por mês",
    casRendaBHint: "Renda líquida da outra pessoa.",
    casDespesas: "Despesas comuns do mês",
    casDespesasHint: "Aluguel, mercado, contas da casa. O que é dos dois, não o gasto de cada um.",
    casDespesasSugestao: (valor) => `Vocês gastaram ${valor} este mês`,
    casPctLabel: "Já combinaram outro percentual? (opcional)",
    casPctSufixo: "% pro outro",
    casPctVoltar: (pct) => `Voltar pro cálculo da renda (${pct}%)`,
    casPctDica: "Em branco, a conta segue a renda de cada um.",
    casSemRenda: "Preenche a renda dos dois. Sem número, não tem conta.",
    casHeaderAuto: "Divisão proporcional à renda",
    casHeaderManual: "Percentual combinado por vocês",
    casTextoAuto: "Quem ganha mais, paga mais — na mesma proporção da renda. Não é 50/50.",
    casTextoManual: "Vocês definiram o percentual. A conta segue esse número, não o da renda.",
    casContribA: "Um dos dois paga",
    casContribB: "O outro paga",
    casContribPct: (pct) => `${pct}% das despesas comuns`,
    casSobraLivre: (valor) => `Sobra livre: ${valor}`,
    casComparandoTitulo: "Comparando com 50/50",
    casComparandoIgual: (valor) => `Dividindo igual, cada um pagaria ${valor}.`,
    casComparandoMenos: (valor) => `Do jeito que está, quem ganha menos paga ${valor} a menos por mês. Justo.`,
    casComparandoMais: (valor) => `Do jeito que está, quem ganha menos paga ${valor} a mais por mês.`,
    casComparandoParecido: "Rendas parecidas. Dá quase no mesmo que 50/50.",
    casComparandoManualNota: (pct) => `Pela renda, seria ${pct}% pro outro.`,
    casRendaConjunta: (valor) => `Renda conjunta: ${valor}. Não fica salvo — é só pra decidir esse mês.`,

    // Empresa: vale a pena investir? Payback e comparação com a aplicação, sem enrolação.
    invTitulo: "Vale a pena investir na empresa?",
    invSub: "Máquina, reforma, ponto novo, contratação. Em quanto tempo se paga — e se rende mais que deixar parado. Decide com número.",
    invCusto: "Quanto custa o investimento?",
    invCustoHint: "Valor à vista. Máquina, reforma, ponto novo, contratação.",
    invTipoLabel: "O que ele traz por mês?",
    invTipoVenda: "Mais vendas",
    invTipoEconomia: "Economia de custo",
    invReceitaLabelVenda: "Receita a mais por mês",
    invReceitaLabelEconomia: "Economia por mês",
    invReceitaHintVenda: "O que você espera vender a mais. Usa a média, não o melhor mês — otimismo não paga conta.",
    invReceitaHintEconomia: "O que deixa de gastar por mês (energia, terceiro, retrabalho).",
    invMargemLabel: "Quanto sobra de cada venda, depois dos custos dela",
    invMargemHint: "Margem de contribuição, pela DRE. Vender mais só vale o que sobra depois de mercadoria, taxa e frete.",
    invCustoMensal: "Custo fixo novo por mês",
    invCustoMensalHint: "O que o investimento passa a custar todo mês: manutenção, salário, aluguel maior, software. Zero se não tiver.",
    invPrazoLabel: "Prazo pra avaliar",
    invTaxaLabel: "Aplicação rende ao ano",
    invVeredictoEyebrow: "Veredito",
    invVeredictoValeTitulo: "Vale a pena",
    invVeredictoValeTexto: (meses) => `Se paga em ${meses} ${meses === 1 ? "mês" : "meses"} e rende mais que deixar parado. Decisão fácil.`,
    invVeredictoEmpataTitulo: "Empata com a aplicação",
    invVeredictoEmpataTexto: (meses) => `Se paga em ${meses} meses, mas o ganho fica parecido com a aplicação. Decide pelo que isso traz pra empresa, não só pelo número.`,
    invVeredictoNaoValeTitulo: "Não vale, por enquanto",
    invVeredictoNaoValeTextoForaDoPrazo: (meses, horizonte) => `Só se paga em ${meses} meses, além dos ${horizonte} que você deu de prazo. Reavalia.`,
    invVeredictoNaoValeTextoRendeMais: "Deixar aplicado rende mais que esse investimento devolve no prazo. Não bora.",
    invVeredictoNuncaSePagaTitulo: "Não se paga",
    invVeredictoNuncaSePagaTexto: "O custo novo come toda a margem que a receita nova traz. Esse investimento nunca se paga do jeito que está.",
    invGanhoMes: "Ganho por mês",
    invGanhoMesNota: "já tirando o custo novo",
    invSePagaEm: "Se paga em",
    invSePagaNunca: "nunca",
    invSePagaNota: "payback",
    invResultadoEm: (horizonte) => `Resultado em ${horizonte} meses`,
    invResultadoNota: (pct) => `${pct}% sobre o investido`,
    invNaAplicacao: "Na aplicação, renderia",
    invNaAplicacaoNota: (taxa) => `${taxa}% ao ano, sem IR`,
    invGraficoTitulo: "Empresa × aplicação, mês a mês",
    invGraficoDescSupera: (mes) => `A empresa passa a aplicação no mês ${mes}. Ponto de virada.`,
    invGraficoDescNaoSupera: "No prazo dado, a aplicação rende mais. Sem meio-termo.",
    invGraficoLegendaEmpresa: "Na empresa",
    invGraficoLegendaAplicacao: "Na aplicação",
    invReceitaNecessariaAntes: (horizonte) => `Pra se pagar em ${horizonte} meses, precisa trazer pelo menos `,
    invReceitaNecessariaDepois: " de vendas a mais por mês.",
    invReceitaAbaixo: " Você estimou menos que isso. Ajusta a meta ou o prazo.",
    invReceitaAcima: " Você estimou acima disso. No caminho certo.",
    invRodapeNota: "Conta simples, sem inflação nem imposto sobre a aplicação — só pra dar a ordem de grandeza. Decisão apertada, chama o contador antes de assinar.",

    // E-mail: o resumo do mês e o convite pra voltar. Mesma voz de coach, comando curto.
    emailSaudacao: (nome) => (nome ? `Bora, ${nome}!` : "Bora!"),
    emailRecapAssunto: (mes) => `Seu resultado de ${mes} tá pronto`,
    emailRecapIntro: (mes) => `${mes} fechado. Olha o que os números dizem:`,
    emailRecapSobrou: "Guardado no mês",
    emailRecapFaltou: "Faltou no mês",
    emailRecapPrimeiroMes: "Primeiro mês com registro. Do próximo em diante, dá pra comparar e cobrar evolução.",
    emailRecapGastosIguais: "Mesmo nível do mês anterior. Sem piora, sem evolução ainda.",
    emailRecapGastosMenos: (valor) => `Você gastou ${valor} que no mês anterior. Isso é evolução.`,
    emailRecapGastosMais: (valor) => `Seus gastos ficaram ${valor} do mês anterior. Corrige agora, antes que vire hábito.`,
    emailMaiorGasto: "Maior gasto",
    emailRecapBotao: "Ver o resultado completo",
    emailRecapRodape: "Você recebe este resultado uma vez por mês.",
    emailConviteAssunto: (mes) => `Bora começar ${mes}?`,
    emailConviteIntro1: (mes) => `${mes} começou. Mês novo, placar zerado — a hora certa de começar é agora, não depois do dia 10.`,
    emailConviteIntro2:
      "Não precisa organizar tudo hoje. <strong>Registra um gasto agora</strong>, só um, e o app já começa a montar o resto: pra onde o dinheiro foi, quanto sobrou, quanto dá pra guardar.",
    emailConviteBotao: "Bora: registrar meu primeiro gasto",
  },
};
