import { TITULOS_PADRAO, simuladoresDoTema, tarefasDoTema, inteiro, semDiaria, type Voz } from "../voice-base";

/**
 * O menu na voz do Game, por rota. O mês é a temporada (a carteira continua "carteira": "inventário" soou ruim), os
 * simuladores são treino: a pessoa lê o app como um placar dela contra ela mesma.
 */
const GAME_SECOES: Record<string, string> = {
  "/dashboard": "Placar",
  "/mensal": "Temporada",
  "/planejamento": "Missões",
  "/carteira": "Carteira",
  "/simuladores": "Treino",
};
const GAME_FILHOS: Record<string, string> = {
  "/mensal": "Mensal",
  "/mensal/gastos": "Gastos",
  "/orcamento": "Missões",
  "/planejamento/metas": "Missões",
  "/planejamento/reserva-emergencia": "Reserva",
  "/planejamento/acumulo": "Missão final",
  "/carteira": "Carteira",
  "/carteira/por-objetivo": "Por missão",
};

const s = (n: number) => (n === 1 ? "" : "s");

export const game: Voz = {
  // O Game não cumprimenta: a tela abre no ranking (divisão, pontos, temporada).
  saudacao: () => null,
  subSaudacao: () => null,
  tituloPainel: null,
  rotuloResultado: "Guardado",
  fraseResultado: (estado, d) => {
    const v = inteiro(d.money, d.resultado);
    if (estado === "bom") return `+${v} na reserva. ${d.recorde ? "Seu melhor mês da temporada." : "Temporada fechando forte."} +100 pontos`;
    if (estado === "normal") return `+${v} na reserva. Chega a 20% do que entrou e a temporada pontua +100.`;
    if (estado === "ruim") return d.mesFechado ? "Temporada fechada sem pontuar. Zero ponto este mês." : "Missão em risco: nada na reserva ainda.";
    return null;
  },
  ritmo: { rapido: "Missão em risco", limite: "No limite da missão", dentro: "Missão no ritmo" },
  tituloOrcamento: () => "Missão do mês",
  fraseOrcamento: (d) => {
    const pronta = semDiaria(d);
    if (pronta) return pronta;
    const porDia = inteiro(d.money, d.porDia!);
    if (d.situacao === "estourou") return `Missão perdida: ${inteiro(d.money, d.restante)} acima do limite.`;
    if (d.situacao === "adiantado") return `Missão difícil: ${porDia} por dia para fechar no positivo.`;
    if (d.situacao === "folgado") return `Missão tranquila: ${porDia} por dia.`;
    return `${porDia} por dia para fechar a temporada no positivo.`;
  },
  mesVazio: "Temporada sem registro. Lança e aporta pra fechar o combo.",
  metaBatida: (nome) => `Conquista desbloqueada: ${nome}`,
  rodape: (estado) => (estado === "bom" ? "Divisão subindo. 🏆" : estado === "normal" ? "Dá pra pontuar mais nesta temporada." : estado === "ruim" ? "Temporada em risco. Ainda dá tempo." : null),
  nav: { metas: "Missões", flowTabs: ["Mensal", "Gastos", "Missões"] },
  titulos: {
    ...TITULOS_PADRAO,
    comparacao: (tipo, valor, mes) =>
      tipo === "sem" ? `Zero em ${mes}` : tipo === "igual" ? `Igual a ${mes}` : tipo === "mais" ? `${valor} a mais que ${mes} · −pontos` : `${valor} a menos que ${mes} · +pontos`,
    simuladores: "Treino de decisão",
    simuladoresSub: "Seis cenários pra testar a jogada antes de gastar de verdade.",
    simulador: simuladoresDoTema({
      "/simuladores/financiar-vs-alugar": { subtitle: "Financiar ou alugar e investir a diferença? Testa a jogada antes de assinar." },
      "/simuladores/amortizar-vs-investir": { subtitle: "Sobrou dinheiro: quita a dívida ou investe? A conta decide a jogada." },
      "/simuladores/consorcio": { subtitle: "Consórcio ou financiamento? O custo real de cada rota." },
      "/simuladores/marcacao-mercado": { subtitle: "Vender o título antes do vencimento dá lucro ou prejuízo? Simula antes de apertar o botão." },
      "/simuladores/carro": { subtitle: "Assinar ou comprar o carro? Qual rota custa menos em 24 meses." },
      "/simuladores/vale-a-pena": { subtitle: "Quantas horas de jogo custa esse item? Calcula antes de comprar." },
    }),
    registrar: "Registrar",
    registrarNovo: "Novo registro · conta pro combo",
    registrarFalar: "Por voz · conta pro combo",
    registrarImportar: "Importar extrato · conta pro combo do mês",
    lancamentoSalvo: "Registrado. Conta pro combo do mês.",
    // Ranqueada: temporada, missão, pontos. Sério, sem emoji — só o troféu quando é conquista
    // e a chama quando é sequência de meses. A divisão mede constância, nunca patrimônio.
    visaoGeral: "Placar do ano",
    visaoGeralSub: "Temporada {ano}.",
    patrimonio: "Patrimônio acumulado",
    rendaNoAno: "Entrou",
    gastosNoAno: "Saiu",
    sobrouNoAno: "Na reserva",
    sobrouNoAnoDica: (cem, manteve, pct) =>
      pct >= 20 ? `De cada ${cem}, ${manteve} pra reserva. Divisão subindo. 🏆`
      : pct > 0 ? `De cada ${cem}, ${manteve} pra reserva. Dá pra pontuar mais.`
      : "Nada pra reserva este ano. Temporada zerada.",
    statusModulos: "Missões abertas",
    modReserva: "Vida extra (reserva)",
    modMetas: "Missões",
    modAposentadoria: "Missão final",
    modDividendos: "Bônus (30 dias)",
    economiaNoMes: "Guardado na temporada",
    economiaAbaixo: "Missão cumprida ✓",
    economiaAcima: "Missão falhou. Próxima temporada.",
    categoriaEstourou: "Onde você perdeu pontos",
    categoriaEstourouDica: (pct) => `${pct} acima do limite`,
    nenhumaEstourou: "Nenhuma perda. Temporada limpa 🏆",
    economizouMaisEm: "Onde você pontuou mais",
    economizouMaisEmDica: (pct) => `${pct} abaixo do limite. +pontos`,
    semLancamento: "Sem registro. Sem pontos.",
    soGastos: "Gastos",
    soGastosSub: "Cada gasto por categoria.",
    orcamento: "Missões",
    orcamentoSub: "O limite de cada missão e onde você está.",
    orcamentoPorCategoria: "Missão por categoria",
    paraOndeFoi: "Pra onde foi o dinheiro nesta temporada",
    ritmoDoMes: "Ritmo da temporada",
    anoMesAMes: "Temporadas do ano",
    caiuNaConta: "Bônus na conta",
    caiuNaContaSub: "Seus ativos pagaram. Registra como renda e pontua.",
    planejamento: "Limite",
    poupanca: "Guardado",
    metas: "Missões",
    metasSub: "Cada missão tem prazo e pontos por mês.",
    metasVazio: "Nenhuma missão ativa. Crie a primeira e comece a pontuar.",
    reserva: "Reserva · vida extra",
    reservaSub: "Sua vida extra. Sem ela, qualquer imprevisto é game over.",
    reservaMeta: "Alvo da reserva",
    reservaTempo: "Tempo pra completar",
    reservaProjecao: "Até completar",
    aposentadoria: "Missão final",
    aposentadoriaSub: "Do acúmulo até viver de renda. A última fase.",
    aposentadoriaWizardSub: "Configure a missão final em poucos passos.",
    metaStatus: { ahead: "Adiantada", onTrack: "No ritmo", behind: "Atrasada", achieved: "Concluída 🏆" },
    metaGuardar: (v) => `${v} este mês pra manter a missão`,
    metaMeses: (n) => `${n} ${n === 1 ? "mês" : "meses"} pra fechar`,
    metaAporteFeito: (mes) => `Missão de ${mes} cumprida ✓`,
    metaAporteToast: (mes) => `Aporte de ${mes} registrado. Combo do mês avançando.`,
    metaMarcar: (mes) => `Cumpri ${mes}`,
    splitTitulo: (mes) => `Divisão do aporte · ${mes}`,
    splitSub: (v) => `${v} por mês. Reserva primeiro, depois as missões por prazo.`,
    splitVazioTitulo: "Pra onde vai o aporte?",
    splitVazioSub: "Diga na missão do mês quanto quer guardar, e o app divide entre reserva e missões.",
    apSeNadaMudar: (idade) => `Se nada mudar, aos ${idade} anos você chega com`,
    apDaPe: "Missão final: cumprida 🏆",
    apNaoDaPe: "Missão final: ainda não",
    apJurosNota: (um, mais) => `Pra cada ${um} seu, os juros somam ${mais}. É o multiplicador.`,
    apProjecao: "Trajetória",
    apAcumuloDesc: "fase de aporte: o patrimônio só cresce.",
    apUsufrutoDesc: "os aportes param e os saques pra viver começam.",
    planTabs: ["Missões", "Reserva", "Missão final"],
    carteiraTabs: ["Carteira", "Por missão", "Estratégia"],
    visaoGeralLink: "Ver a temporada →",
    semanaTitulo: "Missões da semana",
    tarefa: tarefasDoTema({
      lancamentos: (n, feita) => (feita ? `Gastos da semana registrados (${n ?? 0}) ✓ metade do combo` : "Registrar os gastos da semana · metade do combo"),
      "orcamento-definir": () => "Definir o limite de cada categoria",
      "orcamento-estourado": (n, _f, pl) => `Recuperar ${n ?? 1} categoria${pl ? "s" : ""} acima do limite`,
      "orcamento-ok": () => "Limites do mês sob controle ✓",
      "reserva-configurar": () => "Configurar a vida extra (reserva)",
      "reserva-completar": (n) => `Avançar na reserva (${n ?? 0}%)`,
      "reserva-ok": () => "Reserva completa 🏆",
      "meta-criar": () => "Criar a primeira missão",
      "meta-atrasada": (n, _f, pl) => `Retomar ${n ?? 1} ${pl ? "missões atrasadas" : "missão atrasada"}`,
      "meta-ok": () => "Missões no ritmo ✓",
      aporte: (_n, feita) => (feita ? "Aporte do mês feito ✓ combo fechado" : "Separar o aporte do mês · fecha o combo (+100)"),
    }),
    navSecao: (b, t) => GAME_SECOES[b] ?? t,
    navFilho: (h, t) => GAME_FILHOS[h] ?? t,
    carteira: "Carteira",
    carteiraSub: "Seus ativos e a missão de cada um.",
    carteiraLink: "Ver por missão →",
    carteiraVazio: "Carteira vazia. Adicione o primeiro ativo pra acompanhar aqui.",
    porObjetivo: "Carteira por missão",
    porObjetivoSub: "Posição por missão e alocação atual × alvo por classe.",
    porObjetivoEditar: "← editar carteira",
    posicaoPorObjetivo: "Posição por missão",
    objReserva: "Reserva (vida extra)",
    objSem: "Sem missão definida",
    objSemMetaHint: "Sem alvo cadastrado na reserva",
    secaoMetas: "Missões",
    estrategiaVsAlvo: "Carteira atual × estratégia-alvo",
    alocacaoPorClasse: "Alocação atual × alvo por classe",
    estrategia: "Estratégia da carteira",
    estrategiaSub: "Os percentuais-alvo por classe de estratégia (somando 100%), independente do alvo de cada ativo individual.",
    contribTitulo: (mes) => `Aporte de ${mes}: quanto?`,
    contribSub: "Onde o aporte entra pra fechar o alvo da carteira.",
    contribVazio: "Carteira vazia: a divisão segue só a estratégia.",
    contribSemEstrategiaTitulo: "Onde vai o aporte desta temporada?",
    contribSemEstrategiaSub: "Com uma estratégia definida, o app diz quanto vai pra cada tipo de investimento pra fechar o alvo. São três perguntas.",
    divTitulo: (total) => `Bônus a caminho · ${total}`,
    compHint: "O tracinho é o alvo. Quem está atrás dele é o próximo aporte.",
    objNenhumTitulo: "Nenhum ativo tem missão ainda.",
    objNenhumTexto: (valor) =>
      `Seus ${valor} estão todos em "sem missão". Dizer o que cada ativo é — reserva, liberdade financeira ou uma missão — é o que deixa esta tela responder "quanto falta" em vez de só somar.`,
    objNenhumLink: "Dar missão aos ativos →",

    // ── Simuladores: cada calculadora é um treino, cada resultado é uma jogada testada ──
    simSalvarBotao: "Salvar este treino",
    simSalva: "Treino salvo",
    simSalvaToast: "Treino salvo. Fica na lista de simuladores.",
    simSalvarErro: "Não consegui salvar este treino.",
    simSalvasTitulo: "Seus treinos salvos",
    simSalvaSemNome: "Treino",
    simPaywallNome: "Treino de decisão",
    simFinVenceFinanciar: "Financiar vence",
    simFinVenceAlugar: "Alugar e investir vence",
    simAmortVenceAmortizar: "Amortizar vence",
    simAmortVenceInvestir: "Investir vence",
    simAmortVeredito: (vencedor, valor) => `${vencedor === "AMORTIZAR" ? "Amortizar" : "Investir"} fecha com ${valor} a mais.`,
    simConsVenceConsorcio: "Consórcio vence: sai mais barato",
    simConsVenceFinanciamento: "Financiamento vence: sai mais barato",
    simCarroVenceAssinar: "Assinar vence: sai mais barato",
    simCarroVenceComprar: "Comprar vence: sai mais barato",
    simMarcLucro: "Vender agora daria lucro",
    simMarcPrejuizo: "Vender agora daria prejuízo",
    simMarcSub: "Levar até o vencimento tira esse risco da mesa.",
    simValePasso1Sub: "Digite o preço do item que está na mira.",
    simValeRendaMes: (mes) => `em ${mes} (Temporada)`,
    simValeSemRenda: (mes) => `Nenhuma renda registrada em ${mes} ainda.`,
    simValeCadastre: "cadastre na Temporada",
    simValeTitulo: "Vale a jogada?",
    simValeBarraInvestirMensal: "Segurar e investir",
    simValeVeredito: (valor) => `Investindo, você fecha com ${valor} a mais.`,
    simValeEscolhaComprar: "Se é prioridade, ok — só confira que cabe no limite da temporada.",
    simValeEscolhaNao: "Boa jogada. Isso aproxima das suas missões.",
    simValeEscolhaDuvida: "Sem problema. Dá pra voltar aqui quando tiver mais clareza — a dúvida já é sinal de que vale pensar mais um pouco.",

    // ── Formulários: meta vira missão, orçamento vira limite, lançar vira registrar ──
    formMetaNova: "Nova missão",
    formMetaEditar: "Editar missão",
    formMetaAdicionar: "Adicionar missão",
    formMetaCriada: "Missão criada. Temporada aberta.",
    formMetaAtualizada: "Missão atualizada.",
    formMetaNome: "Nome da missão",
    formMetaIcones: { VIAGEM: "Viagem", CASA: "Casa", CARRO: "Carro", APOSENTADORIA: "Missão final", GENERICO: "Genérico" },
    formMetaMesAno: "Prazo (mês/ano)",
    formAtivoAdicionado: "Ativo adicionado à carteira.",
    formAtivoAtualizado: "Ativo atualizado.",
    formAtivoObjetivos: { OUTRO: "Outro", RESERVA_EMERGENCIA: "Reserva (vida extra)", LIBERDADE_FINANCEIRA: "Liberdade financeira", META: "Missão" },
    formAtivoMetaVinculada: "Missão vinculada",
    formOrcSalvo: "Limites salvos pro ano inteiro.",
    formOrcTitulo: "Vamos definir os limites da temporada",
    formOrcSub: "Três perguntas. O app já sabe parte das respostas pelos seus registros.",
    formOrcQuantoGuardar: "Quanto você quer guardar por temporada?",
    formOrcSobraTitulo: "Limite pra gastar",
    formOrcDividaTitulo: (valor) => `Divida os ${valor} entre as missões`,
    formOrcVerPlano: "Ver meus limites →",
    formOrcSeuPlano: (ano) => `Seus limites de ${ano}`,
    formOrcProntoPlano: (ano) => `Pronto. Seus limites de ${ano}`,
    formOrcPraOnde: "Pra onde vai o aporte",
    formOrcPraOndeNota: "Reserva primeiro, depois as missões por prazo. O resto fica livre.",
    formOrcEstourou: "As categorias somam mais do que o limite. Volte e ajuste, ou guarde menos.",
    formOrcSalvar: "Salvar meus limites",
    formOrcApagarDepois: "? Os registros que já usaram essa categoria continuam existindo, só perdem a categorização.",
    formApVerPlano: "Ver a missão final",
    formEstSalva: "Estratégia salva.",
    formEstComoFicaria: "Como sua carteira ficaria",
    formEstReservaPergunta: "Sua vida extra (a reserva) já está completa?",
    formLancMetaVinculada: "Missão vinculada (opcional)",
    formLancLancar: "Registrar",

    // ── Importação: a gaveta Registrar, os importadores e o placar da temporada ──
    impConectarBancoSub: "Open Finance · os lançamentos chegam sozinhos — o combo do mês não falha 🔥",
    impNovaCategoriaDica: "A categoria nova já aparece nas Missões pra você definir um limite pra ela.",
    impImportarN: (n) => `Importar ${n} lançamento${s(n)} · +pontos`,
    impImportadosSucesso: (n) => `${n} lançamentos importados. Temporada pontuada.`,
    impToastImportados: (n) => `${n} lançamentos importados · +pontos`,
    impCarteiraEscolher: "Escolher a posição da corretora",
    impCarteiraEmDia: (n) => `Carteira já em dia com esse extrato: ${n} ativo${s(n)} conferido${s(n)}, nenhuma mudança encontrada.`,
    impCarteiraNovos: "Novos na carteira",
    impCarteiraSemMudanca: (n) =>
      `${n} ativo${s(n)} sem mudança, já ${n === 1 ? "está" : "estão"} na carteira e ${n === 1 ? "fica" : "ficam"} como ${n === 1 ? "está" : "estão"}.`,
    impCarteiraFeito: (criados, atualizados) =>
      [criados > 0 ? `${criados} novo${s(criados)} na carteira` : null, atualizados > 0 ? `${atualizados} atualizado${s(atualizados)}` : null]
        .filter(Boolean)
        .join(" · ") || "Nada pra mudar, carteira já estava em dia.",
    impIrpfConfira:
      "Confira o ativo da sua carteira em cada linha (as que a declaração só traz o nome da empresa vêm sem casar — escolha à mão ou deixe de fora).",
    impIrpfComoFunciona:
      "O preço médio vira o valor investido (preço médio × quantidade da carteira). A cotação atual não muda, só o investido, que é a base do lucro/prejuízo.",
    impRepeteSub: "Estava nas temporadas anteriores e ainda não está nesta. Um toque registra.",
    impRepeteLancar: "Registrar",
    impRepeteLancado: "Registrado. Conta pro combo do mês.",
    impRepeteLancadoAteDezembro: "Registrado nesta temporada e nas seguintes até dezembro.",
    impRepeteErro: "Não consegui registrar. Tente de novo.",
    impResumoPronto: "Placar da temporada pronto",
    impResumoProntoSub: "Veja como o mês fechou, número por número",
    impStoryTitulo: "Placar da Temporada",
    impStorySub: "Como foi a temporada, número por número.",
    impStoryGastou: "Nesta temporada você gastou",
    impStoryComparado: "Comparado com a temporada anterior, você gastou",
    impStoryEsteMes: "Esta temporada",
    impStoryMesPassado: "Temporada passada",
    impStoryDiaEconomico: "Seu dia da semana com menos gasto foi",
    impStoryDiaGastador: "O dia da semana com mais gasto foi",
    impStoryAcumuladoRuim: "Temporada a temporada dá pra virar. O primeiro passo é ver o número.",
    impStoryDestaques: "Destaques da temporada",
    impStoryGastosDoMes: "Gastos da temporada",
    impStoryCompartilhar: "Compartilhar placar",
    impShareTitulo: "Meu placar do mês",
    impShareImagemTitulo: ["Meu placar", "do mês"],
    impShareTexto: (periodo, gastei, positivo, saldo, potencial) =>
      [
        `Meu placar do mês (${periodo}):`,
        `• Gastei ${gastei}`,
        `• ${positivo ? "Ficou no bolso" : "Saldo"} desde o início: ${saldo}`,
        `• Potencial em 10 anos: ${potencial}`,
      ].join("\n"),

    // ── Shell: primeiros passos, tour, cartões do mês, erros ──
    uiPrimeirosPassos: "Primeiras missões",
    uiPassoRegistrar: "Registre seu primeiro gasto ou renda · metade do combo",
    uiPassoOrcamento: "Defina os limites da temporada",
    uiPassoCarteira: "Monte sua carteira de investimentos",
    uiTourBoasVindasTitulo: "Boas-vindas ao SPI Finance",
    uiTourBoasVindasTexto: "Um tour rápido mostrando ONDE fica cada coisa, botão por botão. Dá pra pular quando quiser.",
    uiTourRegistrarTitulo: "Este + é o botão que pontua",
    uiTourRegistrarTexto: "É por aqui que você registra tudo: digite um gasto, fale por áudio ou importe o extrato do banco. Lançar no mês e fazer o aporte fecha o combo da temporada: +100 pontos. Comece sempre por ele.",
    uiTourFluxoTitulo: "Aqui é a Temporada",
    uiTourFluxoTexto: "Seu mês em um lugar: renda, gastos e o limite de cada missão, com um alerta quando o ritmo passa do limite.",
    uiTourMetasTitulo: "Aqui são as Missões",
    uiTourMetasTexto: "Crie missões (viagem, casa), a reserva — sua vida extra — e a missão final, a aposentadoria. O app calcula quanto guardar por mês pra fechar cada uma.",
    uiTourCarteiraTitulo: "Aqui é a Carteira",
    uiTourCarteiraTexto: "Seus investimentos e o lucro de cada um. Dá até pra puxar o preço médio direto da sua declaração de Imposto de Renda.",
    uiTourMaisTexto: "Placar do ano, Treino de decisão e Análises ficam neste menu.",
    uiTourFimTitulo: "Temporada aberta.",
    uiTourFimTexto: "Toque no + e registre o primeiro lançamento: metade do combo do mês feita 🔥",
    uiFluxoTituloFuturo: (mes) => `O que já está marcado pra ${mes}`,
    uiFluxoTituloCorrente: (mes) => `Temporada de ${mes}: como está indo`,
    uiFluxoTituloFechado: (mes) => `Temporada de ${mes}: como fechou`,
    uiFluxoDicaFuturo: "Lançamentos repetidos e agendados. A temporada ainda não começou.",
    uiRendaDividida: "Como a renda foi dividida",
    uiRendaGastouAMais: (valor) => `Saiu ${valor} a mais do que entrou nesta temporada.`,
    uiMaioresGastos: "Maiores gastos da temporada",
    uiSetaCompara: "A seta compara com a temporada passada. Variação abaixo de 8% não aparece — é oscilação normal.",
    uiErroTitulo: "Erro do nosso lado",
    uiErroTexto: "Foi um erro nosso, não seu — seus dados e seus pontos estão seguros. Tente recarregar; se continuar, saia e entre de novo.",
    uiNaoEncontradoTexto: "Verifique o endereço ou volte pro início — a temporada continua lá.",
    uiNaoEncontradoVoltar: "Voltar pro início",

    // ── Configurações: só onde o app fala de orçamento, metas e carteira ──
    cfgResumoEmail: "Placar do mês por e-mail",
    cfgResumoEmailDica: "Uma vez por mês, no começo da temporada: quanto entrou, quanto saiu e o que mudou.",
    cfgAlertasOrcamento: "Alertas de limite",
    cfgAlertasOrcamentoDica:
      "Categoria com 80% do limite gasto e ainda com metade da temporada pela frente, ou já estourada. Chega no celular (se ligado) ou por e-mail.",
    cfgMetasAtrasadas: "Missões atrasadas",
    cfgMetasAtrasadasDica: "Quando uma missão fica pra trás do ritmo. Um aviso por missão por mês.",
    cfgPushDica:
      "Uma mensagem no celular, como as de um app: quando uma categoria está perto de estourar o limite e ainda falta metade da temporada, ou uma missão ficou pra trás. Sem e-mail.",
    cfgExportCarteiraDica:
      "Gera um arquivo CSV com todos os ativos da sua carteira (nome, ticker, classe, quantidade, valor investido e valor atual).",
    cfgExportCarteira: "Exportar carteira (CSV)",
    cfgExcluirContaTexto: [
      "Apaga a conta e ",
      "todos os seus dados",
      " (lançamentos, limites, missões, carteira) de forma definitiva. Não tem volta, se quiser guardar algo, exporte antes.",
    ],
    cfgPerfisSub: "Cada perfil é um dinheiro separado: lançamentos, missões e carteira não se misturam entre eles.",
    cfgPerfisExcluirTexto: [
      "Excluir ",
      " apaga junto tudo que está dentro dele: lançamentos, limites, missões e carteira. Isso não tem como desfazer.",
    ],
    viagemSub: "Estime quanto custa o destino e transforme em missão com aporte mensal.",
    viagemPorPessoa: (porPessoa, porMes, meses) =>
      `${porPessoa} por pessoa · guardando ${porMes}/mês, a missão fecha em ${meses} ${meses === 1 ? "mês" : "meses"}.`,
    viagemMetaCriadaToast: "Missão da viagem criada. Veja em Missões.",
    viagemVerMeta: "Ver minha missão em Missões",
    viagemCriarMeta: "Criar missão desta viagem",
    viagemCriandoMeta: "Criando missão...",

    // ── Carteira: aporte do mês, por missão, análises e gráficos ──
    cartSuaCarteira: (n) => `Sua carteira · ${n} ativo${s(n)}`,
    cartRotuloMeta: (nome) => `missão "${nome}"`,
    cartPorTipo: "Carteira atual, por tipo",
    cartTracinhoAlvo: "O tracinho é o seu alvo. Quem está atrás dele é o próximo aporte.",
    cartNaEstrategia: "Carteira na estratégia",
    cartDefinaQuanto: "Defina quanto quer ter em cada tipo e compare com a carteira atual.",
    cartDaCarteira: (pct) => `${pct} da carteira`,
    cartDefinirObjetivoDos: (n) => `Definir missão dos ${n}…`,
    cartSuasMetas: "Suas missões",
    cartObjMeta: "Missão",
    cartMetaPrefixo: (nome) => `Missão: ${nome}`,
    cartImportarCarteira: "Importar carteira",
    cartAporteProntoTitulo: "Aporte aplicado. Tudo batendo.",
    cartMetasAndaram: (lista) => `Suas missões andaram junto: ${lista}.`,
    cartCadastreAtivo: "Cadastre o ativo que recebeu esse dinheiro e a carteira passa a bater com o que você registrou na temporada.",
    cartEnquantoNaoDisser: (meta) =>
      `Enquanto não disser, a carteira fica com um valor e o mês com outro${meta ? `, e a missão ${meta} não anda junto` : ""}.`,
    cartMetaDoAtivo: (nome) => `missão: ${nome}`,
    cartAporteAplicado: "Carteira e missões atualizadas com o aporte da temporada.",
    cartAtualizarCarteira: "É isso, atualizar carteira",
    cartDaMeta: (pct, valor) => `${pct} da missão (${valor})`,
    cartSemAtivos: "Nenhum ativo na carteira ainda.",
    cartColMeta: "Missão",
    cartSemEstrategiaLink: "estratégia da carteira",
    cartSemEstrategiaDepois: ". Defina os percentuais-alvo por classe pra ver aqui o comparativo e o rebalanceamento.",
    fichasSub: "Seu placar de saúde financeira e o que pede atenção agora.",
    fichasInsightsVazio: "Cadastre limites, missões, reserva e uma estratégia de carteira pra começar a receber insights automáticos aqui.",
    fichasNaCarteira: "na sua carteira",
    fichasNaSuaCarteira: (ticker) => `${ticker} na sua carteira`,
    fichasNaoRecomendacao: "Não é recomendação: é a sua carteira lida junto com os números do ativo.",
    metaBreadcrumbPlanejamento: "Missões",
    metaRitmo: { NOT_STARTED: "Sem prazo hábil", ON_TRACK: "No ritmo", BEHIND: "Atrasada", ACHIEVED: "Concluída 🏆" },
    metaMesesRestantes: "Meses pra fechar",
    metaTrajetoria: "Trajetória até fechar a missão",
    grafMetaLinha: (valor) => `alvo ${valor}`,
    grafPronta: (pct) => `${pct}% completa`,
  },
};
