import { nDias } from "../textos/foco";
import { TITULOS_PADRAO, simuladoresDoTema, tarefasDoTema, inteiro, semDiaria, estadoParaFrase, type Voz, type Titulos } from "../voice-base";

/**
 * O menu na voz do Game, por rota. O mês é a temporada (a carteira continua "carteira": "inventário" soou ruim), os
 * simuladores são treino: a pessoa lê o app como um placar dela contra ela mesma.
 */
const GAME_SECOES: Record<string, string> = {
  "/dashboard": "Placar",
  "/mensal": "Temporada",
  "/planejamento": "Missões",
  "/carteira": "Carteira",
  "/simuladores": "Treino",
  "/divisao": "Divisão co-op",
  "/investir": "Vale investir?",
};
const GAME_FILHOS: Record<string, string> = {
  "/mensal": "Mensal",
  "/mensal/gastos": "Gastos",
  // O orçamento é "Limites": "Missões" já são as metas, e dois botões "Missões" na mesma tela
  // levavam a lugares diferentes.
  "/orcamento": "Limites",
  "/planejamento/metas": "Missões",
  "/planejamento/reserva-emergencia": "Reserva",
  "/planejamento/acumulo": "Missão final",
  "/carteira": "Carteira",
  "/carteira/por-objetivo": "Por missão",
};

const s = (n: number) => (n === 1 ? "" : "s");

// "Posso comprar?" passo a passo (05/10/2026): a compra é uma jogada da temporada. Metas são
// missões, a reserva é a vida extra; o placar fala do número, nunca de quem joga.
const mesesGm = (n: number) => `${n} ${n === 1 ? "mês" : "meses"}`;
const GAME_COMPRA: Partial<Titulos> = {
  compraOutraCoisaPergunta: "Qual é o item?",
  compraQuantoCusta: "Quanto custa o item?",
  compraContinuar: "Próximo",
  compraComoPagar: "Como você quer pagar?",
  compraDecideVoce: "O app escolhe a jogada",
  compraDecideVoceSub: "Pega a rota que pesa menos no mês",
  compraEmQuantasVezes: "Em quantas vezes?",
  compraTotalPago: (t) => `Custo total da jogada: ${t}`,
  compraSincera: "Jogo limpo:",
  compraSinceraSub: "Essa compra é",
  compraSinceridade: {
    precisa: { titulo: "Preciso mesmo", sub: "Faz falta no dia a dia" },
    quero: { titulo: "Quero muito", sub: "Penso nela faz tempo" },
    impulso: { titulo: "Impulso", sub: "Vi agora e quis" },
  },
  compraAnalisando: "Lendo o placar do mês…",
  compraAnaliseItens: ["Seus gastos da temporada", "Compras que você já decidiu", "Suas missões e a vida extra", "Quanto costuma sobrar"],
  compraVereditoTitulo: (v, s, soPorImpulso) => {
    if (v === "ok") return "Pode comprar. Jogada limpa.";
    if (s === "precisa") return v === "custo" ? "Precisa? Dá pra fazer, com ajuste." : "Hoje o placar não fecha, nem apertando.";
    if (v === "custo") return soPorImpulso ? "Cabe, mas foi jogada de impulso." : "Dá, mas a jogada tem custo.";
    return "Eu seguraria essa jogada agora.";
  },
  compraOQueValeMais: "Qual jogada vale mais pra você?",
  compraPrioridadeCompra: "Comprar agora",
  compraPrioridadeCompraSub: (meta, mes) => `A missão ${meta} passa para ${mes}`,
  compraPrioridadeSonho: (meta, mes) => `Missão ${meta} em ${mes}`,
  compraPrioridadeSonhoSub: "A compra vira uma missão e vem depois",
  compraVerComoCaber: "Ver jogadas para fazer caber",
  compraCaberTitulo: "Dá pra fazer caber",
  compraCaberSub: "Escolha uma jogada. Cada uma mostra o que acontece com a sua temporada.",
  compraCaberNadaTitulo: "Esse item ainda não cabe",
  compraCaminho: (c) => {
    switch (c?.chave) {
      case "parcelar":
        return { titulo: `Parcelar em ${c.vezes}x sem juros`, detalhe: `${c.vezes}x de ${c.porMes}`, comoCompra: `Em ${c.vezes}x de ${c.porMes}, sem juros` };
      case "barato":
        return c.vezes && c.vezes > 1
          ? { titulo: `Buscar um de até ${c.valor}`, detalhe: `Em ${c.vezes}x sem juros, cabe no que sobra`, comoCompra: `Um de até ${c.valor}, em ${c.vezes}x sem juros` }
          : { titulo: `Buscar um de até ${c.valor}`, detalhe: "À vista, cabe no que sobra", comoCompra: `Um de até ${c.valor}, à vista` };
      case "cortar":
        return {
          titulo: `Travar ${c.valor}`,
          detalhe: `Em ${c.cortes}${c.cortePorMes ? ", por mês" : ", só nesta temporada"}`,
          comoCompra: `Travando ${c.valor}${c.cortePorMes ? " por mês" : " nesta temporada"}`,
        };
      case "desconto":
        return { titulo: "Pedir desconto à vista", detalhe: `Loja costuma dar uns 10%: ${c.valor} em vez de ${c.parcelado} parcelado`, comoCompra: `À vista com desconto, por ${c.valor}` };
      case "juntarRapido":
        return { titulo: `Juntar mais rápido: compra em ${c.mes}`, detalhe: `Gastando ${c.cortes} a menos por mês, à vista`, comoCompra: `Juntando ${c.porMes} por mês` };
      case "juntar":
        return { titulo: `Juntar e comprar em ${c.mes}`, detalhe: `Guardando ${c.porMes} por mês, à vista`, comoCompra: `Juntando ${c.porMes} por mês` };
      default:
        return { titulo: "", detalhe: "", comoCompra: "" };
    }
  },
  compraSeloCabe: "Cabe ✓",
  compraSeloSemDivida: "Sem dívida ✓",
  compraSeloCusto: "Ainda tem custo",
  compraSeguirCom: "Fechar essa jogada",
  compraEscolhaUm: "Escolha uma jogada",
  compraOQueVaiFazer: "Qual vai ser a jogada?",
  compraSugestao: "Jogada sugerida",
  compraDecComprarSub: (precisa) => (precisa ? "Pela rota que pesa menos" : "Pela rota que a gente viu"),
  compraDecGuardar: "Vou juntar primeiro",
  compraDecGuardarSub: "Vira uma missão no app",
  compraDecGuardarMeta: (mensal, mes) => `Missão de ${mensal} por mês, compra em ${mes}`,
  compraDecDesistir: "Vou passar a vez",
  compraDecDesistirSub: "Não preciso disso agora",
  compraFimComprarTitulo: "Jogada feita.",
  compraFimGuardarTitulo: "Jogada planejada.",
  compraFimGuardar: (mensal, meses, mes, corte) =>
    `${mensal} por mês por ${mesesGm(meses)}${corte ? `, gastando ${corte} a menos` : ""}. Em ${mes} você compra à vista, sem dívida.`,
  compraFimAmanhaTitulo: "Jogada pausada até amanhã.",
  compraFimDesistirTitulo: "Crédito mantido.",
  compraCriarMeta: "Criar a missão",
  compraMetaCriada: "Missão criada.",
  compraVerMeta: "Ver a missão",
};

export const game: Voz = {
  // O Game não cumprimenta: a tela abre no ranking (divisão, pontos, temporada).
  saudacao: () => null,
  subSaudacao: () => null,
  tituloPainel: null,
  rotuloResultado: "Sobrou",
  fraseResultado: (estadoBruto, d) => {
    const estado = estadoParaFrase(estadoBruto, d.resultado);
    const v = inteiro(d.money, d.resultado);
    if (estado === "bom") return `+${v} na reserva. ${d.recorde ? "Seu melhor mês da temporada." : "Temporada fechando forte."} +100 pontos`;
    if (estado === "normal") return `+${v} na reserva. Chega a 20% do que entrou e a temporada pontua +100.`;
    if (estado === "ruim") return d.mesFechado ? "Temporada fechada sem pontuar. Zero ponto este mês." : "Missão em risco: nada na reserva ainda.";
    return null;
  },
  ritmo: { rapido: "Missão em risco", limite: "No limite da missão", dentro: "Missão no ritmo" },
  tituloOrcamento: () => "Missão do mês",
  fraseOrcamento: (d) => {
    const pronta = semDiaria(d);
    if (pronta) return pronta;
    const porDia = inteiro(d.money, d.porDia!);
    if (d.situacao === "estourou") return `Missão perdida: ${inteiro(d.money, d.restante)} acima do limite.`;
    if (d.situacao === "adiantado") return `Missão difícil: ${porDia} por dia para fechar no positivo.`;
    if (d.situacao === "folgado") return `Missão tranquila: ${porDia} por dia.`;
    return `${porDia} por dia para fechar a temporada no positivo.`;
  },
  mesVazio: "Temporada sem registro. Lança e aporta pra fechar o combo.",
  metaBatida: (nome) => `Conquista desbloqueada: ${nome}`,
  rodape: (estado) => (estado === "bom" ? "Divisão subindo. 🏆" : estado === "normal" ? "Dá pra pontuar mais nesta temporada." : estado === "ruim" ? "Temporada em risco. Ainda dá tempo." : null),
  nav: { foco: "Objetivo", metas: "Missões", flowTabs: ["Mensal", "Gastos", "Limites"] },
  titulos: {
    ...TITULOS_PADRAO,
    // Aba Foco e "Posso comprar?"
    focoRitualEy: "Segunda",
    focoRitualT: "Missão semanal · 5 min",
    focoRitualP: "4 etapas. Complete e pontue.",
    focoFechEy: "Fim de temporada",
    focoFechT: (m) => `Fechar a temporada de ${m}`,
    focoFechP: "Confira o placar e desbloqueie o próximo mês.",
    focoComecar: "Iniciar",
    focoAmanhaT: (d, v) => `Jogada pendente: ${d} (${v})`,
    focoAmanhaP: "24 horas se passaram. Confirmar a jogada?",
    focoAindaQuero: "Confirmar jogada",
    focoRaioXT: (n) => `${n} ${n === 1 ? "gasto" : "gastos"} em loop no extrato`,
    focoRaioXP: (a) => `${a} por ano. Cortar libera crédito pras missões.`,
    focoBemTeto: (c, v) => `${c}: limite travado em ${v}`,
    focoTetoBotao: (v) => `Travar limite em ${v}`,
    focoSegurarBotao: (c) => `Bloquear ${c} até o fim da temporada`,
    focoPontual: "Evento pontual",
    focoRitualFeito: "Missão semanal completa.",
    focoFechFeito: (m) => `Temporada de ${m} fechada.`,
    fechTitulo: (m) => `Fechar a temporada de ${m}`,
    fechImportarT: (m) => `Carregar os dados de ${m}`,
    fechImportarP: "Extrato e fatura. A única etapa manual da missão.",
    fechImportarBtn: "Carregar dados",
    fechImportadoT: (m, n) => `Dados de ${m} carregados: ${n} ${n === 1 ? "lançamento" : "lançamentos"}`,
    fechLicao: "Replay do mês:",
    fechSobraP: "Bônus da temporada. Melhor jogada: vida extra (reserva), que ainda não está cheia.",
    fechSobraReserva: (v) => `Investir ${v} na vida extra`,
    fechSobraSoOQueFalta: (f, r) => `Faltam só ${f} pra vida extra encher. Vai esse valor, e os outros ${r} ficam no inventário.`,
    fechSobraConta: "Guardar no inventário",
    fechSemSobra: "Temporada fechada sem bônus. A próxima começa agora.",
    fechAjusteP: "Ajuste de estratégia: subir o limite ou treinar o controle?",
    fechAjusteSubir: (v) => `Limite de ${v}`,
    fechAjusteManter: "Manter o limite",
    fechAporteEy: "Missão do mês",
    fechAporteT: (v) => `Missão do mês: ${v} na vida extra`,
    fechAporteP: "Sem isso, a temporada fecha sem pontuar.",
    fechAporteFeito: "Missão completa",
    fechAporteDepois: "Completo essa semana",
    fechNumeroSub: "Crédito até o fim da temporada",
    fechNumeroP: (s) => `≈ ${s} por semana. Esse é o seu crédito.`,
    fechFechar: "Fechar temporada",
    ritTitulo: "Missão semanal",
    ritFechar: "Completar missão",
    raioxTitulo: "Raio-X: gastos em loop",
    raioxAtalho: "Raio-X",
    raioxIntro: "Cada item consome crédito todo mês. Escolha a jogada:",
    raioxCancelar: "Remover",
    raioxMetade: "Reduzir pela metade",
    raioxManter: "Manter no inventário",
    raioxEconomia: (a, c) => `+${a} de crédito por ano. Em 5 anos: ${c}.`,
    erradoLink: "Reportar erro",
    erradoObrigada: "Erro reportado. Obrigada!",
    conqTitulo: "Suas conquistas",
    focoAcao: "Abrir missão",
    focoTitulo: "Objetivo",
    focoLivreSemana: "Crédito da semana",
    focoLivreMes: "Crédito até o fim da temporada",
    focoLivreSub: "Gaste com estratégia.",
    focoLivreEstimativa: "Crédito da temporada (estimativa)",
    focoLivreEstimativaSub: (s) => `≈ ${s} por semana, se seguir a estratégia`,
    focoSemOrcamentoTitulo: "Sem limites definidos",
    focoSemOrcamentoSub: "Defina o orçamento pra liberar o crédito da temporada.",
    focoSemOrcamentoBotao: "Definir limites",
    focoDadosVelhos: (d) => `Dados de ${d} dias atrás. Placar desatualizado.`,
    focoImportar: "Carregar extrato",
    focoAtencao: "Alertas da partida",
    focoNadaTitulo: "Nenhum alerta ativo.",
    focoNadaSub: "",
    focoBem: "Conquistas em andamento",
    focoDuvida: "Consultar o manual",
    focoFioTitulo: "Sua jornada",
    focoEstouroT: (c) => `${c}: limite estourado`,
    focoEstouroP: (g, p, d) => `${g} de ${p}. ${nDias(d)} de partida pela frente.`,
    focoAporteT: (v) => `Missão do mês: ${v} na vida extra`,
    focoAporteP: "Sem isso, a temporada fecha sem pontuar.",
    focoRitmoT: (c, p) => `${c}: ${p} do limite usado`,
    focoRitmoP: (d, s) => `${nDias(d)} de partida e ${s} de crédito nessa categoria.`,
    focoMetaT: (m) => `Missão em risco: ${m}`,
    focoMetaP: (f) => `Pra recuperar: ${f} por mês.`,
    focoReservaT: (m) => `Vida extra: ${m} de cobertura`,
    focoReservaP: "A meta é de 6 a 12 meses.",
    focoBemRitmo: (c) => `${c} sob controle`,
    focoBemMeta: (m, q) => `${m} no ritmo: ${q}`,
    focoBemAporte: (v) => `+${v} na vida extra`,
    focoRitmoSemanalSub: "Missão semanal: 5 minutos.",
    focoRitmoMensalSub: "Fechamento de temporada: 15 minutos por mês.",
    compraOk: "Jogada liberada",
    compraCusto: "Jogada com custo",
    compraNao: "Jogada arriscada",
    comparacao: (tipo, valor, mes) =>
      tipo === "sem" ? `Zero em ${mes}` : tipo === "igual" ? `Igual a ${mes}` : tipo === "mais" ? `${valor} a mais que ${mes} · −pontos` : `${valor} a menos que ${mes} · +pontos`,
    simuladores: "Treino de decisão",
    simuladoresSub: "Seis cenários pra testar a jogada antes de gastar de verdade.",
    simulador: simuladoresDoTema({
      "/simuladores/financiar-vs-alugar": { subtitle: "Financiar ou alugar e investir a diferença? Testa a jogada antes de assinar." },
      "/simuladores/amortizar-vs-investir": { subtitle: "Sobrou dinheiro: quita a dívida ou investe? A conta decide a jogada." },
      "/simuladores/consorcio": { subtitle: "Consórcio ou financiamento? O custo real de cada rota." },
      "/simuladores/marcacao-mercado": { subtitle: "Vender o título antes do vencimento dá lucro ou prejuízo? Simula antes de apertar o botão." },
      "/simuladores/carro": { subtitle: "Assinar ou comprar o carro? Qual rota custa menos em 24 meses." },
      "/simuladores/vale-a-pena": { subtitle: "Quantas horas de jogo custa esse item? Calcula antes de comprar." },
    }),
    registrar: "Registrar",
    registrarNovo: "Novo registro · conta pro combo",
    registrarFalar: "Por voz · conta pro combo",
    registrarImportar: "Importar extrato · conta pro combo do mês",
    lancamentoSalvo: "Registrado. Conta pro combo do mês.",
    // Ranqueada: temporada, missão, pontos. Sério, sem emoji — só o troféu quando é conquista
    // e a chama quando é sequência de meses. A divisão mede constância, nunca patrimônio.
    visaoGeral: "Placar do ano",
    visaoGeralSub: "Temporada {ano}.",
    patrimonio: "Patrimônio acumulado",
    rendaNoAno: "Entrou",
    gastosNoAno: "Saiu",
    sobrouNoAno: "Na reserva",
    sobrouNoAnoDica: (cem, manteve, pct) =>
      pct >= 20 ? `De cada ${cem}, ${manteve} pra reserva. Divisão subindo. 🏆`
      : pct > 0 ? `De cada ${cem}, ${manteve} pra reserva. Dá pra pontuar mais.`
      : "Nada pra reserva este ano. Temporada zerada.",
    statusModulos: "Missões abertas",
    modReserva: "Vida extra (reserva)",
    modMetas: "Missões",
    modAposentadoria: "Missão final",
    modDividendos: "Bônus (30 dias)",
    economiaNoMes: "Guardado na temporada",
    economiaAbaixo: "Missão cumprida ✓",
    economiaAcima: "Missão falhou. Próxima temporada.",
    categoriaEstourou: "Onde você perdeu pontos",
    categoriaEstourouDica: (pct) => `${pct} acima do limite`,
    nenhumaEstourou: "Nenhuma perda. Temporada limpa 🏆",
    economizouMaisEm: "Onde você pontuou mais",
    economizouMaisEmDica: (pct) => `${pct} abaixo do limite. +pontos`,
    semLancamento: "Sem registro. Sem pontos.",
    soGastos: "Gastos",
    soGastosSub: "Cada gasto por categoria.",
    orcamento: "Limites",
    orcamentoSub: "O limite de cada categoria e onde você está.",
    orcamentoPorCategoria: "Limite por categoria",
    paraOndeFoi: "Pra onde foi o dinheiro nesta temporada",
    ritmoDoMes: "Ritmo da temporada",
    anoMesAMes: "Temporadas do ano",
    caiuNaConta: "Bônus na conta",
    caiuNaContaSub: "Seus ativos pagaram. Registra como renda e pontua.",
    planejamento: "Limite",
    poupanca: "Guardado",
    metas: "Missões",
    metasSub: "Cada missão tem prazo e pontos por mês.",
    metasVazio: "Nenhuma missão ativa. Crie a primeira e comece a pontuar.",
    reserva: "Reserva · vida extra",
    reservaSub: "Sua vida extra. Sem ela, qualquer imprevisto é game over.",
    reservaMeta: "Alvo da reserva",
    reservaTempo: "Tempo pra completar",
    reservaProjecao: "Até completar",
    aposentadoria: "Missão final",
    aposentadoriaSub: "Do acúmulo até viver de renda. A última fase.",
    aposentadoriaWizardSub: "Configure a missão final em poucos passos.",
    metaStatus: { ahead: "Adiantada", onTrack: "No ritmo", behind: "Atrasada", achieved: "Concluída 🏆" },
    metaGuardar: (v) => `${v} este mês pra manter a missão`,
    metaProximoAporte: (v, mes) => `Próxima missão: ${v} em ${mes}`,
    metaMeses: (n) => `${n} ${n === 1 ? "mês" : "meses"} pra fechar`,
    metaAporteFeito: (mes) => `Missão de ${mes} cumprida ✓`,
    metaAporteToast: (mes) => `Aporte de ${mes} registrado. Combo do mês avançando.`,
    metaMarcar: (mes) => `Cumpri ${mes}`,
    splitTitulo: (mes) => `Divisão do aporte · ${mes}`,
    splitSub: (v) => `${v} por mês. Reserva primeiro, depois as missões por prazo.`,
    splitVazioTitulo: "Pra onde vai o aporte?",
    splitVazioSub: "Diga na missão do mês quanto quer guardar, e o app divide entre reserva e missões.",
    apSeNadaMudar: (idade) => `Se nada mudar, aos ${idade} anos você chega com`,
    apDaPe: "Missão final: cumprida 🏆",
    apNaoDaPe: "Missão final: ainda não",
    apJurosNota: (um, mais) => `Pra cada ${um} seu, os juros somam ${mais}. É o multiplicador.`,
    apProjecao: "Trajetória",
    apAcumuloDesc: "fase de aporte: o patrimônio só cresce.",
    apUsufrutoDesc: "os aportes param e os saques pra viver começam.",
    planTabs: ["Missões", "Reserva", "Missão final"],
    carteiraTabs: ["Carteira", "Por missão", "Estratégia"],
    visaoGeralLink: "Ver a temporada →",
    semanaTitulo: "Missões da semana",
    tarefa: tarefasDoTema({
      lancamentos: (n, feita) => (feita ? `Gastos da semana registrados (${n ?? 0}) ✓ metade do combo` : "Registrar os gastos da semana · metade do combo"),
      "orcamento-definir": () => "Definir o limite de cada categoria",
      "orcamento-estourado": (n, _f, pl) => `Recuperar ${n ?? 1} categoria${pl ? "s" : ""} acima do limite`,
      "orcamento-ok": () => "Limites do mês sob controle ✓",
      "reserva-configurar": () => "Configurar a vida extra (reserva)",
      "reserva-completar": (n) => `Avançar na reserva (${n ?? 0}%)`,
      "reserva-ok": () => "Reserva completa 🏆",
      "meta-criar": () => "Criar a primeira missão",
      "meta-atrasada": (n, _f, pl) => `Retomar ${n ?? 1} ${pl ? "missões atrasadas" : "missão atrasada"}`,
      "meta-ok": () => "Missões no ritmo ✓",
      aporte: (_n, feita) => (feita ? "Aporte do mês feito ✓ combo fechado" : "Separar o aporte do mês · fecha o combo (+100)"),
      "reuniao-casal": () => "Missão co-op: 15 min revisando os gastos do mês, os dois juntos",
    }),
    navSecao: (b, t) => GAME_SECOES[b] ?? t,
    navFilho: (h, t) => GAME_FILHOS[h] ?? t,
    carteira: "Carteira",
    carteiraSub: "Seus ativos e a missão de cada um.",
    carteiraLink: "Ver por missão →",
    carteiraVazio: "Carteira vazia. Adicione o primeiro ativo pra acompanhar aqui.",
    porObjetivo: "Carteira por missão",
    posicaoPorObjetivo: "Posição por missão",
    objReserva: "Reserva (vida extra)",
    objSem: "Sem missão definida",
    secaoMetas: "Missões",
    estrategiaVsAlvo: "Carteira atual × estratégia-alvo",
    estrategia: "Estratégia da carteira",
    contribTitulo: (mes) => `Aporte de ${mes}: quanto?`,
    contribSub: "Onde o aporte entra pra fechar o alvo da carteira.",
    contribVazio: "Carteira vazia: a divisão segue só a estratégia.",
    contribSemEstrategiaTitulo: "Onde vai o aporte desta temporada?",
    divTitulo: (total) => `Bônus a caminho · ${total}`,
    objNenhumTitulo: "Nenhum ativo tem missão ainda.",
    objNenhumLink: "Dar missão aos ativos →",

    // ── Simuladores: cada calculadora é um treino, cada resultado é uma jogada testada ──
    simSalvarBotao: "Salvar este treino",
    simSalva: "Treino salvo",
    simSalvaToast: "Treino salvo. Fica na lista de simuladores.",
    simSalvarErro: "Não consegui salvar este treino.",
    simSalvasTitulo: "Seus treinos salvos",
    simSalvaSemNome: "Treino",
    simPaywallNome: "Treino de decisão",
    simFinVenceFinanciar: "Financiar vence",
    simFinVenceAlugar: "Alugar e investir vence",
    simAmortVenceAmortizar: "Amortizar vence",
    simAmortVenceInvestir: "Investir vence",
    simAmortVeredito: (vencedor, valor) => `${vencedor === "AMORTIZAR" ? "Amortizar" : "Investir"} fecha com ${valor} a mais.`,
    simConsVenceConsorcio: "Consórcio vence: sai mais barato",
    simConsVenceFinanciamento: "Financiamento vence: sai mais barato",
    simCarroVenceAssinar: "Assinar vence: sai mais barato",
    simCarroVenceComprar: "Comprar vence: sai mais barato",
    simMarcLucro: "Vender agora daria lucro",
    simMarcPrejuizo: "Vender agora daria prejuízo",
    simMarcSub: "Levar até o vencimento tira esse risco da mesa.",
    simValePasso1Sub: "Digite o preço do item que está na mira.",
    simValeRendaMes: (mes) => `em ${mes} (Temporada)`,
    simValeRendaPlano: (mes) => `planejada pra ${mes} (Limites)`,
    simValeSemRenda: (mes) => `Nenhuma renda registrada em ${mes} ainda.`,
    simValeCadastre: "cadastre na Temporada",
    simValeTitulo: "Vale a jogada?",
    simValeBarraInvestirMensal: "Segurar e investir",
    simValeVeredito: (valor) => `Investindo, você fecha com ${valor} a mais.`,
    simValeEscolhaComprar: "Se é prioridade, ok — só confira que cabe no limite da temporada.",
    simValeEscolhaNao: "Boa jogada. Isso aproxima das suas missões.",
    simValeEscolhaDuvida: "Sem problema. Dá pra voltar aqui quando tiver mais clareza — a dúvida já é sinal de que vale pensar mais um pouco.",

    // ── Formulários: meta vira missão, orçamento vira limite, lançar vira registrar ──
    formMetaNova: "Nova missão",
    formMetaEditar: "Editar missão",
    formMetaAdicionar: "Adicionar missão",
    formMetaCriada: "Missão criada. Temporada aberta.",
    formMetaAtualizada: "Missão atualizada.",
    formMetaNome: "Nome da missão",
    formMetaIcones: { VIAGEM: "Viagem", CASA: "Casa", CARRO: "Carro", APOSENTADORIA: "Missão final", GENERICO: "Genérico" },
    formMetaMesAno: "Prazo (mês/ano)",
    formAtivoAdicionado: "Ativo adicionado à carteira.",
    formAtivoAtualizado: "Ativo atualizado.",
    formAtivoObjetivos: { OUTRO: "Outro", RESERVA_EMERGENCIA: "Reserva (vida extra)", LIBERDADE_FINANCEIRA: "Liberdade financeira", META: "Missão" },
    formAtivoMetaVinculada: "Missão vinculada",
    formOrcSalvo: "Limites salvos daqui até dezembro.",
    formOrcTitulo: "Vamos definir os limites da temporada",
    formOrcQuantoGuardar: "Quanto você quer guardar por temporada?",
    formOrcSobraTitulo: "Limite pra gastar",
    formOrcDividaTitulo: (valor) => `Divida os ${valor} entre as missões`,
    formOrcVerPlano: "Ver meus limites →",
    formOrcEditarCurto: (ano) => `Editar limites ${ano}`,
    formOrcSeuPlano: (ano) => `Seus limites de ${ano}`,
    formOrcProntoPlano: (ano) => `Pronto. Seus limites de ${ano}`,
    formOrcPraOnde: "Pra onde vai o aporte",
    formOrcEstourou: "As categorias somam mais do que o limite. Volte e ajuste, ou guarde menos.",
    formOrcSalvar: "Salvar meus limites",
    formOrcApagarDepois: "? Os registros que já usaram essa categoria continuam existindo, só perdem a categorização.",
    formApVerPlano: "Ver a missão final",
    formEstSalva: "Estratégia salva.",
    formEstComoFicaria: "Como sua carteira ficaria",
    formLancMetaVinculada: "Missão vinculada (opcional)",
    formLancLancar: "Registrar",

    // ── Importação: a gaveta Registrar, os importadores e o placar da temporada ──
    impConectarBancoSub: "Open Finance · os lançamentos chegam sozinhos — o combo do mês não falha 🔥",
    impNovaCategoriaDica: "A categoria nova já aparece nas Missões pra você definir um limite pra ela.",
    impImportarN: (n) => `Importar ${n} lançamento${s(n)} · +pontos`,
    impImportadosSucesso: (n) => `${n === 1 ? "1 lançamento importado" : `${n} lançamentos importados`}. Temporada pontuada.`,
    impToastImportados: (n) => `${n} lançamentos importados · +pontos`,
    impCarteiraEscolher: "Escolher a posição da corretora",
    impCarteiraEmDia: (n) => `Carteira já em dia com esse extrato: ${n} ativo${s(n)} conferido${s(n)}, nenhuma mudança encontrada.`,
    impCarteiraNovos: "Novos na carteira",
    impCarteiraSemMudanca: (n) =>
      `${n} ativo${s(n)} sem mudança, já ${n === 1 ? "está" : "estão"} na carteira e ${n === 1 ? "fica" : "ficam"} como ${n === 1 ? "está" : "estão"}.`,
    impCarteiraFeito: (criados, atualizados) =>
      [criados > 0 ? `${criados} novo${s(criados)} na carteira` : null, atualizados > 0 ? `${atualizados} atualizado${s(atualizados)}` : null]
        .filter(Boolean)
        .join(" · ") || "Nada pra mudar, carteira já estava em dia.",
    impRepeteSub: "Estava nas temporadas anteriores e ainda não está nesta. Um toque registra.",
    impRepeteLancar: "Registrar",
    impRepeteLancado: "Registrado. Conta pro combo do mês.",
    impRepeteLancadoAteDezembro: "Registrado nesta temporada e nas seguintes até dezembro.",
    impRepeteErro: "Não consegui registrar. Tente de novo.",
    impResumoPronto: "Placar da temporada pronto",
    impResumoProntoSub: "Veja como o mês fechou, número por número",
    impStoryTitulo: "Placar da Temporada",
    impStorySub: "Como foi a temporada, número por número.",
    impStoryGastou: "Nesta temporada você gastou",
    impStoryComparado: "Comparado com a temporada anterior, você gastou",
    impStoryEsteMes: "Esta temporada",
    impStoryMesPassado: "Temporada passada",
    impStoryDiaEconomico: "Seu dia da semana com menos gasto foi",
    impStoryDiaGastador: "O dia da semana com mais gasto foi",
    impStoryAcumuladoRuim: "Temporada a temporada dá pra virar. O primeiro passo é ver o número.",
    impStoryDestaques: "Destaques da temporada",
    impStoryGastosDoMes: "Gastos da temporada",
    impStoryCompartilhar: "Compartilhar placar",
    impShareTitulo: "Meu placar do mês",
    impShareImagemTitulo: ["Meu placar", "do mês"],
    impShareTexto: (periodo, gastei, positivo, saldo, potencial) =>
      [
        `Meu placar do mês (${periodo}):`,
        `• Gastei ${gastei}`,
        `• ${positivo ? "Ficou no bolso" : "Saldo"} desde o início: ${saldo}`,
        `• Potencial em 10 anos: ${potencial}`,
      ].join("\n"),

    // ── Shell: primeiros passos, tour, cartões do mês, erros ──
    uiPrimeirosPassos: "Primeiras missões",
    uiPassoRegistrar: "Registre seu primeiro gasto ou renda · metade do combo",
    uiPassoOrcamento: "Defina os limites da temporada",
    uiPassoCarteira: "Monte sua carteira de investimentos",
    uiTourBoasVindasTitulo: "Boas-vindas ao SPI Finance",
    uiTourBoasVindasTexto: "Um tour rápido mostrando ONDE fica cada coisa, botão por botão. Dá pra pular quando quiser.",
    uiTourRegistrarTitulo: "Este + é o botão que pontua",
    uiTourFluxoTitulo: "Aqui é a Temporada",
    uiTourFluxoTexto: "Seu mês em um lugar: renda, gastos e o limite de cada missão, com um alerta quando o ritmo passa do limite.",
    uiTourMetasTitulo: "Aqui são as Missões",
    uiTourCarteiraTitulo: "Aqui é a Carteira",
    uiTourCarteiraTexto: "Seus investimentos e o lucro de cada um. Dá até pra puxar o preço médio direto da sua declaração de Imposto de Renda.",
    uiTourMaisTexto: "Placar do ano, Treino de decisão e Análises ficam neste menu.",
    uiTourFimTitulo: "Temporada aberta.",
    uiTourFimTexto: "Toque no + e registre o primeiro lançamento: metade do combo do mês feita 🔥",
    uiFluxoTituloFuturo: (mes) => `O que já está marcado pra ${mes}`,
    uiFluxoTituloCorrente: (mes) => `Temporada de ${mes}: como está indo`,
    uiFluxoTituloFechado: (mes) => `Temporada de ${mes}: como fechou`,
    uiFluxoDicaFuturo: "Lançamentos repetidos e agendados. A temporada ainda não começou.",
    uiRendaDividida: "Como a renda foi dividida",
    uiRendaGastouAMais: (valor) => `Saiu ${valor} a mais do que entrou nesta temporada.`,
    uiMaioresGastos: "Maiores gastos da temporada",
    uiSetaCompara: "A seta compara com a temporada passada. Variação abaixo de 8% não aparece — é oscilação normal.",
    uiErroTitulo: "Erro do nosso lado",
    uiErroTexto: "Foi um erro nosso, não seu — seus dados e seus pontos estão seguros. Tente recarregar; se continuar, saia e entre de novo.",
    uiNaoEncontradoTexto: "Verifique o endereço ou volte pro início — a temporada continua lá.",
    uiNaoEncontradoVoltar: "Voltar pro início",

    // ── Configurações: só onde o app fala de orçamento, metas e carteira ──
    cfgResumoEmail: "Placar do mês por e-mail",
    cfgResumoEmailDica: "Uma vez por mês, no começo da temporada: quanto entrou, quanto saiu e o que mudou.",
    cfgAlertasOrcamento: "Alertas de limite",
    cfgMetasAtrasadas: "Missões atrasadas",
    cfgMetasAtrasadasDica: "Quando uma missão fica pra trás do ritmo. Um aviso por missão por mês.",
    cfgExportCarteira: "Exportar carteira (CSV)",
    cfgExcluirContaTexto: [
      "Apaga a conta e ",
      "todos os seus dados",
      " (lançamentos, limites, missões, carteira) de forma definitiva. Não tem volta, se quiser guardar algo, exporte antes.",
    ],
    cfgPerfisSub: "Cada perfil é um dinheiro separado: lançamentos, missões e carteira não se misturam entre eles.",
    cfgPerfisExcluirTexto: [
      "Excluir ",
      " apaga junto tudo que está dentro dele: lançamentos, limites, missões e carteira. Isso não tem como desfazer.",
    ],
    viagemSub: "Estime quanto custa o destino e transforme em missão com aporte mensal.",
    viagemPorPessoa: (porPessoa, porMes, meses) =>
      `${porPessoa} por pessoa · guardando ${porMes}/mês, a missão fecha em ${meses} ${meses === 1 ? "mês" : "meses"}.`,
    viagemMetaCriadaToast: "Missão da viagem criada. Veja em Missões.",
    viagemVerMeta: "Ver minha missão em Missões",
    viagemCriarMeta: "Criar missão desta viagem",
    viagemCriandoMeta: "Criando missão...",

    // ── Carteira: aporte do mês, por missão, análises e gráficos ──
    cartSuaCarteira: (n) => `Sua carteira · ${n} ativo${s(n)}`,
    cartRotuloMeta: (nome) => `missão "${nome}"`,
    cartPorTipo: "Carteira atual, por tipo",
    cartTracinhoAlvo: "O tracinho é o seu alvo. Quem está atrás dele é o próximo aporte.",
    cartNaEstrategia: "Carteira na estratégia",
    cartDefinaQuanto: "Defina quanto quer ter em cada tipo e compare com a carteira atual.",
    cartDaCarteira: (pct) => `${pct} da carteira`,
    cartDefinirObjetivoDos: (n) => `Definir missão dos ${n}…`,
    cartSuasMetas: "Suas missões",
    cartObjMeta: "Missão",
    cartMetaPrefixo: (nome) => `Missão: ${nome}`,
    cartImportarCarteira: "Importar carteira",
    cartAporteProntoTitulo: "Aporte aplicado. Tudo batendo.",
    cartMetasAndaram: (lista) => `Suas missões andaram junto: ${lista}.`,
    cartCadastreAtivo: "Cadastre o ativo que recebeu esse dinheiro e a carteira passa a bater com o que você registrou na temporada.",
    cartEnquantoNaoDisser: (meta) =>
      `Enquanto não disser, a carteira fica com um valor e o mês com outro${meta ? `, e a missão ${meta} não anda junto` : ""}.`,
    cartMetaDoAtivo: (nome) => `missão: ${nome}`,
    cartAporteAplicado: "Carteira e missões atualizadas com o aporte da temporada.",
    cartAtualizarCarteira: "É isso, atualizar carteira",
    cartDaMeta: (pct, valor) => `${pct} da missão (${valor})`,
    fichasSub: "Seu placar de saúde financeira e o que pede atenção agora.",
    fichasNaCarteira: "na sua carteira",
    fichasNaSuaCarteira: (ticker) => `${ticker} na sua carteira`,
    fichasNaoRecomendacao: "Não é recomendação: é a sua carteira lida junto com os números do ativo.",
    metaBreadcrumbPlanejamento: "Missões",
    metaRitmo: { NOT_STARTED: "Sem prazo hábil", ON_TRACK: "No ritmo", BEHIND: "Atrasada", ACHIEVED: "Concluída 🏆" },
    metaMesesRestantes: "Meses pra fechar",
    metaTrajetoria: "Trajetória até fechar a missão",
    grafMetaLinha: (valor) => `alvo ${valor}`,
    grafPronta: (pct) => `${pct}% completa`,

    // Casal: modo co-op — dividir as despesas comuns proporcional à renda, não 50/50.
    casTitulo: "Quanto cada um paga?",
    casRendaA: "Renda de um dos dois por mês",
    casRendaAHint: "Líquida, o que entra de verdade.",
    casRendaB: "Renda do outro por mês",
    casRendaBHint: "Líquida também.",
    casDespesas: "Despesas comuns do mês",
    casDespesasHint: "Aluguel, mercado, contas da casa: o custo do time, não o gasto individual de cada jogador.",
    casDespesasSugestao: (valor) => `O time gastou ${valor} este mês`,
    casPctLabel: "Já combinaram outro percentual? (opcional)",
    casPctSufixo: "% pro outro",
    casPctVoltar: (pct) => `Voltar pro cálculo da renda (${pct}%)`,
    casPctDica: "Em branco, o app calcula pela renda de cada um.",
    casSemRenda: "Preencha a renda dos dois pra liberar o cálculo.",
    casHeaderAuto: "Divisão proporcional à renda",
    casHeaderManual: "Percentual combinado pelo time",
    casTextoManual: "Vocês definiram o percentual. O cálculo segue esse número, não o da renda.",
    casContribA: "Um dos dois entra com",
    casContribB: "O outro entra com",
    casContribPct: (pct) => `${pct}% das despesas comuns`,
    casSobraLivre: (valor) => `Sobra livre: ${valor}`,
    casComparandoTitulo: "Comparando com 50/50",
    casComparandoIgual: (valor) => `Dividindo igual, cada um pagaria ${valor}.`,
    casComparandoMenos: (valor) => `Do jeito que está, quem ganha menos paga ${valor} a menos por mês.`,
    casComparandoMais: (valor) => `Do jeito que está, quem ganha menos paga ${valor} a mais por mês.`,
    casComparandoParecido: "Rendas parecidas: dá quase no mesmo que 50/50.",
    casComparandoManualNota: (pct) => `Pela renda, seria ${pct}% pro outro.`,
    casRendaConjunta: (valor) => `Renda conjunta do time: ${valor}. Não fica salvo — é só pra decidir esse mês.`,

    // Empresa: vale a pena investir? Payback contra a aplicação, como um confronto direto.
    invTitulo: "Vale a pena investir na empresa?",
    invCusto: "Quanto custa o investimento?",
    invCustoHint: "Máquina, reforma, ponto novo, contratação: o valor à vista.",
    invTipoLabel: "O que ele traz por mês?",
    invTipoVenda: "Mais vendas",
    invTipoEconomia: "Economia de custo",
    invReceitaLabelVenda: "Receita a mais por mês",
    invReceitaLabelEconomia: "Economia por mês",
    invReceitaHintVenda: "O que você espera vender a mais por causa dele. Usa a média, não o melhor mês da temporada.",
    invReceitaHintEconomia: "O que deixa de gastar por mês (energia, terceiro, retrabalho).",
    invMargemLabel: "Quanto sobra de cada venda, depois dos custos dela",
    invMargemHint: "A margem de contribuição da empresa, pela DRE. Vender mais só vale o que sobra depois de mercadoria, taxa e frete.",
    invCustoMensal: "Custo fixo novo por mês",
    invCustoMensalHint: "O que o investimento passa a custar todo mês: manutenção, salário, aluguel maior, software. Zero se não tiver.",
    invPrazoLabel: "Prazo pra avaliar",
    invTaxaLabel: "Aplicação rende ao ano",
    invVeredictoEyebrow: "Veredito",
    invVeredictoValeTitulo: "Vale a pena 🏆",
    invVeredictoValeTexto: (meses) => `Se paga em ${meses} ${meses === 1 ? "mês" : "meses"} e vence a aplicação. Ponto pra empresa.`,
    invVeredictoEmpataTitulo: "Empate com a aplicação",
    invVeredictoNaoValeTitulo: "Não vale, por enquanto",
    invVeredictoNaoValeTextoForaDoPrazo: (meses, horizonte) => `Só se paga em ${meses} meses, além dos ${horizonte} que você deu de prazo.`,
    invVeredictoNaoValeTextoRendeMais: "A aplicação vence esse confronto: rende mais do que o investimento devolve no prazo.",
    invVeredictoNuncaSePagaTitulo: "Não se paga",
    invVeredictoNuncaSePagaTexto: "O custo novo por mês consome toda a margem que a receita nova traz. Esse investimento nunca fecha o combo.",
    invGanhoMes: "Ganho por mês",
    invGanhoMesNota: "já tirando o custo novo",
    invSePagaEm: "Se paga em",
    invSePagaNunca: "nunca",
    invSePagaNota: "payback",
    invResultadoEm: (horizonte) => `Resultado em ${horizonte} meses`,
    invResultadoNota: (pct) => `${pct}% sobre o investido`,
    invNaAplicacao: "Na aplicação, renderia",
    invNaAplicacaoNota: (taxa) => `${taxa}% ao ano, sem IR`,
    invGraficoTitulo: "Empresa × aplicação, mês a mês",
    invGraficoDescSupera: (mes) => `A empresa ultrapassa a aplicação no mês ${mes}. Virada de jogo.`,
    invGraficoDescNaoSupera: "No prazo dado, a aplicação vence esse round.",
    invGraficoLegendaEmpresa: "Na empresa",
    invGraficoLegendaAplicacao: "Na aplicação",
    invReceitaNecessariaAntes: (horizonte) => `Pra vencer em ${horizonte} meses, esse investimento precisa trazer pelo menos `,
    invReceitaNecessariaDepois: " de vendas a mais por mês.",
    invReceitaAbaixo: " Sua estimativa está abaixo disso.",
    invReceitaAcima: " Sua estimativa está acima disso.",

    // E-mail: o placar da temporada por e-mail e o convite pra abrir a próxima.
    emailSaudacao: (nome) => (nome ? `Oi, ${nome}!` : "Oi!"),
    emailRecapAssunto: (mes) => `Seu placar de ${mes} saiu`,
    emailRecapIntro: (mes) => `Temporada de ${mes} encerrada. Confira o placar:`,
    emailRecapSobrou: "Saldo positivo",
    emailRecapFaltou: "Saldo negativo",
    emailRecapPrimeiroMes: "Primeira temporada registrada — a próxima já entra com comparação.",
    emailRecapGastosIguais: "Gastos no mesmo nível da temporada anterior.",
    emailRecapGastosMenos: (valor) => `Você gastou ${valor} que na temporada anterior. Boa jogada.`,
    emailRecapGastosMais: (valor) => `Seus gastos ficaram ${valor} da temporada anterior. Hora de recuperar.`,
    emailMaiorGasto: "Categoria que mais pesou",
    emailRecapBotao: "Ver o placar completo",
    emailRecapRodape: "Esse placar cai uma vez por mês.",
    emailConviteAssunto: (mes) => `Temporada de ${mes} começou`,
    emailConviteIntro1: (mes) => `${mes} começou: nova temporada, placar zerado. É o melhor momento pra jogar, porque você acompanha do início ao fim.`,
    emailConviteIntro2:
      "Não precisa jogar tudo de uma vez. <strong>Registre um gasto hoje</strong>, só um, e o placar já começa a rodar: pra onde o dinheiro foi, quanto sobrou, quanto dá pra guardar.",
    emailConviteBotao: "Registrar e abrir a temporada",
    ...GAME_COMPRA,
  },
};
