import { TITULOS_PADRAO, simuladoresDoTema, inteiro, semDiaria, estadoParaFrase, type Voz, type Titulos, numeros } from "../voice-base";

/**
 * Os catálogos por área, na voz do Girly. Cada bloco é um Partial: o que não está aqui sai
 * na voz do Padrão. A regra da Dani vale em todos: zero financês — "guardar" no lugar de
 * aportar, "tudo que você tem" no lugar de patrimônio, "quanto rende" no lugar de
 * rentabilidade — e a cobrança fala do número, nunca da pessoa.
 */
const s = (n: number) => (n === 1 ? "" : "s");

// Simuladores: o assistente, guardar e as seis calculadoras. Nomes de mercado (SAC, Price,
// CET, Duration, IPCA) ficam como são — é o nome da coisa, não a voz.
const GIRLY_SIM: Partial<Titulos> = {
  simContinuar: "Próxima 💕",
  simVerResultado: "Ver o resultado ✨",
  simAjustarRespostas: "Mudar minhas respostas ✏️",
  simResultado: "Deu isso aqui 👀",
  simSalvarBotao: "Guardar essa simulação 📝",
  simSalva: "Simulação guardada 💕",
  simSalvaToast: "Guardei sua simulação, amiga! Ela fica na lista das calculadoras 💕",
  simSalvarErro: "Não consegui guardar essa simulação 🫣 Tenta de novo?",
  simSalvarNomePlaceholder: "Dá um nome pra ela (se quiser) 🎀",
  simSalvando: "Guardando…",
  simSalvar: "Guardar 💕",
  simSalvasTitulo: "Suas simulações guardadas 📝",
  simPaywallNome: "Calculadoras",

  // Financiar vs. Alugar
  simFinValorImovel: "Quanto custa o apê? 🏠",
  simFinValorImovelHint: "O preço de venda do imóvel que você tá de olho 👀",
  simFinEntrada: "Entrada 💸",
  simFinEntradaHint: "Quanto você paga à vista. O resto é o que o banco financia.",
  simFinCetHint: "O custo de verdade do financiamento por ano: juros mais tarifas e seguros (o CET).",
  simFinValorizacao: "Quanto o apê valoriza ✨",
  simFinValorizacaoHint: "Quanto o imóvel sobe de valor por ano, em média.",
  simFinPrazo: "Por quanto tempo ⏳",
  simFinPrazoHint: "Em quantos meses você paga o financiamento (ex.: 360 = 30 anos).",
  simFinSistemaHint: "SAC: as parcelas começam maiores e vão caindo. Price: parcelas iguaizinhas do começo ao fim.",
  simFinAluguel: "Aluguel por mês 🔑",
  simFinAluguelHint: "Quanto custaria alugar o mesmo apê por mês (o outro caminho).",
  simFinReajuste: "Quanto o aluguel sobe por ano 📈",
  simFinReajusteHint: "O reajuste anual do aluguel (ex.: IGP-M ou IPCA).",
  simFinRentabilidadeHint: "Quanto rende por ano o dinheiro que você investiria em vez de comprar.",
  simFinVenceFinanciar: "Financiar sai na frente 🏠✨",
  simFinVenceAlugar: "Alugar e investir sai na frente 🔑✨",
  simFinValorFinanciado: "O que o banco financia",

  // Amortizar vs. Investir
  simAmortSaldo: "Quanto você ainda deve 💳",
  simAmortSaldoHint: "O que falta pagar do financiamento hoje.",
  simAmortCetHint: "O custo de verdade da dívida por ano: juros mais tarifas e seguros (o CET).",
  simAmortPrazoRestante: "Quanto tempo falta ⏳",
  simAmortPrazoRestanteHint: "Quantos meses faltam pra quitar o financiamento.",
  simAmortSistemaHint: "SAC: parcelas que vão caindo. Price: parcelas iguaizinhas.",
  simAmortValorDisponivel: "Quanto sobrou pra decidir 💸",
  simAmortValorDisponivelHint: "O dinheiro que sobrou e que você vai usar pra quitar antes OU investir.",
  simAmortRentabilidadeHint: "Quanto o investimento rende por ano, antes de descontar o Imposto de Renda.",
  simAmortIr: "Imposto de Renda do investimento",
  simAmortIrHint: "O imposto sobre o que rende (ex.: 15% pra prazos longos).",
  simAmortVenceAmortizar: "Melhor quitar antes 💳✨",
  simAmortVenceInvestir: "Melhor investir 🐷✨",
  simAmortBarraAmortizar: "Quitar a dívida antes",
  simAmortBarraAmortizarHint: (meses) => `Juros que você economiza · quita em ${meses} meses`,
  simAmortBarraInvestir: "Investir o dinheiro",
  simAmortBarraInvestirHint: (taxa) => `Ganho já sem o imposto · ${taxa} ao ano`,
  simAmortVeredito: (vencedor, valor) => `${vencedor === "AMORTIZAR" ? "Quitar antes" : "Investir"} te deixa com ${valor} a mais, amiga 💕`,
  simAmortNota: (semMeses, semJuros, comMeses, comJuros) =>
    `Sem quitar antes: ${semMeses} meses pela frente e ${semJuros} de juros no total. Quitando: acaba em ${comMeses} meses, com ${comJuros} de juros.`,

  // Consórcio vs. Financiamento
  simConsValorBem: "Quanto custa o que você quer? ✨",
  simConsValorBemHint: "O valor da carta de crédito do consórcio / o preço da coisa que você quer.",
  simConsTaxaAdm: "Taxa de administração do consórcio",
  simConsTaxaAdmHint: "O total que a administradora cobra ao longo do consórcio (ex.: 18%).",
  simConsPrazo: "Prazo do consórcio ⏳",
  simConsPrazoHint: "Em quantos meses você paga o consórcio.",
  simConsEntrada: "Entrada do financiamento 💸",
  simConsEntradaHint: "Quanto você daria de entrada se fosse pelo financiamento.",
  simConsCetHint: "O custo de verdade do financiamento por ano (o CET).",
  simConsPrazoFin: "Prazo do financiamento ⏳",
  simConsPrazoFinHint: "Em quantos meses você paga o financiamento.",
  simConsSistemaHint: "Price: parcelas iguaizinhas. SAC: parcelas que vão caindo.",
  simConsOportunidade: "Quanto a entrada renderia ✨",
  simConsOportunidadeHint: "Quanto renderia por ano o dinheiro da entrada se ficasse investido (consórcio não pede entrada).",
  simConsVenceConsorcio: "Consórcio sai mais barato 🎉",
  simConsVenceFinanciamento: "Financiamento sai mais barato 🎉",
  simConsBarraConsorcioHint: (parcela) => `Total pago · parcela de ${parcela}`,
  simConsBarraFinanciamentoHint: "Custo total, já contando o que a entrada deixou de render",
  simConsVeredito: (vencedor, valor) => `${vencedor === "CONSORCIO" ? "Consórcio" : "Financiamento"} sai ${valor} mais barato, amiga 💕`,
  simConsCustoOportunidade: "O que a entrada deixou de render",

  // Marcação a Mercado
  simMarcAnbimaAntes: "Dá uma olhada no valor atualizado em",
  simMarcValorFaceHint: "Quanto o título vale no dia do vencimento.",
  simMarcTaxaContratadaHint: "A taxa que você travou quando comprou o título 🔒",
  simMarcNovaTaxaHint: "A taxa que o mercado tá pagando hoje pra esse título — é ela que muda o preço.",
  simMarcPrazoTotalHint: "Prazo do título, do começo até o vencimento.",
  simMarcAnosRestantes: "Anos até vencer ⏳",
  simMarcAnosRestantesHint: "Quanto falta até o vencimento, contando de hoje.",
  simMarcCupons: "Paga juros a cada seis meses?",
  simMarcCuponsHint: "Alguns títulos pagam um pouquinho a cada semestre em vez de tudo no fim. Nesses, use a duration pra medir o impacto.",
  simMarcDurationHint: "O prazo médio dos pagamentos do título, mais curto que o vencimento por causa dos juros semestrais.",
  simMarcInvestido: "Quanto você colocou (se quiser) 💸",
  simMarcInvestidoHint: "Quanto você tem nesse título, pra ver o resultado em reais. Pode deixar zerado.",
  simMarcLucro: "Vender antes da hora daria lucro 🥳",
  simMarcPrejuizo: "Vender antes da hora daria prejuízo 🫣",
  simMarcSub: "Levando até o vencimento, esse risco some ✨",
  simMarcLucroVenda: "Lucro ou prejuízo se vender antes",
  simMarcSensibilidade: "Mais ou menos quanto muda",
  simMarcValorMercado: "Quanto vale hoje",
  simMarcLucroInvestido: "Lucro ou prejuízo sobre o que você colocou",

  // Carro: Assinar vs. Comprar
  simCarroValor: "Quanto custa o carro 0km 🚗",
  simCarroValorHint: "O preço do carro novo à vista.",
  simCarroRevenda1: "Revenda em 1 ano",
  simCarroRevenda1Hint: "Por quanto você venderia o carro depois de 1 ano.",
  simCarroRevenda2: "Revenda em 2 anos",
  simCarroRevenda2Hint: "Por quanto você venderia o carro depois de 2 anos.",
  simCarroCombustivel: "Combustível por mês ⛽",
  simCarroCombustivelHint: "Quanto você gasta de combustível por mês, em média.",
  simCarroAssinatura: "Mensalidade da assinatura 📝",
  simCarroAssinaturaHint: "O valor por mês do carro por assinatura (já vem com seguro, manutenção e IPVA).",
  simCarroCustosFixos: "Gastos fixos por ano",
  simCarroCustosFixosHint: "IPVA, seguro, manutenção e licenciamento por ano, se você comprar.",
  simCarroOportunidade: "O que o dinheiro renderia ✨",
  simCarroOportunidadeHint: "Quanto renderia por mês o dinheiro da compra se ficasse investido.",
  simCarroResultado: "Deu isso em 24 meses 👀",
  simCarroVenceAssinar: "Assinar sai mais barato 🎉",
  simCarroVenceComprar: "Comprar sai mais barato 🎉",
  simCarroBarraAssinaturaHint: "Custo de verdade em 24 meses",
  simCarroBarraComprarHint: "Custo de verdade, já contando a desvalorização e o que o dinheiro deixou de render",
  simCarroVeredito: (vencedor, valor) => `${vencedor === "ASSINATURA" ? "Assinar" : "Comprar"} sai ${valor} mais barato em 24 meses, amiga 💕`,
  simCarroCaixaAssinatura: "O que sai do bolso, assinando",
  simCarroCaixaCompra: "O que sai do bolso, comprando",
  simCarroCustoOportunidade: "O que o dinheiro da compra deixou de render",

  // Vale a pena comprar?
  simValePasso1Titulo: "Quanto custa esse mimo? 🛍️",
  simValePasso1Sub: "Me conta o preço da coisa que você tá pensando em comprar 💕",
  simValePreco: "Preço 💸",
  simValeSimularRenda: "Simular com uma renda de",
  simValeRendaIntro: "Calculei sua hora de trabalho com",
  simValeRendaSua: "o que entrou pra você em",
  simValeRendaSimulada: "uma renda de mentirinha de",
  simValeRendaMes: (mes) => `em ${mes} (Meu mês)`,
  simValeAlterar: "mudar",
  simValeUsarCadastrada: "usar a renda que eu anotei",
  simValeSemRenda: (mes) => `Você ainda não me contou o que entrou em ${mes} 🌸`,
  simValeSimuleValor: "chuta um valor",
  simValeSemRendaMeio: "pra ver quantas horas de trabalho isso custa, ou",
  simValeCadastre: "anota no Meu mês",
  simValePasso2Titulo: "Que tipo de compra é? 🤔",
  simValePasso2Sub: "Isso muda como eu calculo o que você deixaria de ganhar 💕",
  simValeCompraUnica: "Uma vez só",
  simValeCompraUnicaDesc: "Uma coisa pontual: uma roupa, um eletrônico, uma viagem 👗",
  simValeHabito: "Todo mês",
  simValeHabitoDesc: "Se repete todo mês: assinatura, delivery, cafezinho ☕",
  simValeTitulo: "Vale a pena? 👀",
  simValeTempoUnico: "Quantas horas de trabalho custa",
  simValeTempoMensal: "Horas de trabalho por mês",
  simValeHorizontePergunta: "Se você não comprar e guardar, por quanto tempo? ⏳",
  simValeBarraInvestirUnico: "Guardar esse dinheiro 🐷",
  simValeBarraInvestirMensal: "Resistir e guardar 💪",
  simValeBarraInvestirHint: (anos, taxa) => `Em ${anos} ${anos === "1" ? "ano" : "anos"}, rendendo ${taxa}% ao ano`,
  simValeBarraGastar: "Comprar agora 🛍️",
  simValeBarraGastarUnicoHint: "O preço de hoje",
  simValeBarraGastarMensalHint: "O que você pagaria nesse tempo todo",
  simValeVeredito: (valor) => `Guardando, você teria ${valor} a mais no fim, amiga 💕`,
  simValeComprar: "Vou comprar 🛍️",
  simValeNaoComprar: "Não vou comprar 💅",
  simValeAindaNaoSei: "Ainda não sei 🤔",
  simValeEscolhaComprar: "Se é importante pra você, ótimo! Só garante que cabe no seu combinado do mês 💕",
  simValeEscolhaNao: "Boaaaa 👏 Isso te deixa mais perto dos seus sonhos ✨",
  simValeEscolhaDuvida: "Tudo bem, amiga 🫂 Volta aqui quando tiver mais certeza. Se bateu a dúvida, já é sinal de que vale pensar mais um pouquinho.",
};

// Formulários: meta, investimento, o assistente do orçamento, reserva, liberdade, estratégia
// e o lançamento. As tuplas continuam tuplas; o negrito continua onde o componente põe.
const GIRLY_FORM: Partial<Titulos> = {
  formSalvar: "Salvar 💕",
  formSalvando: "Salvando…",
  formVoltar: "← Voltar",
  formContinuar: "Próxima 💕",
  formSelecione: "Escolhe aqui…",
  formOpcional: "(se quiser)",
  formEditar: "Mexer ✏️",
  formRemover: "Tirar",

  formMetaNova: "Novo sonho 🌸",
  formMetaEditar: "Mexer no sonho ✏️",
  formMetaAdicionar: "Anotar sonho 💕",
  formMetaSalvar: "Salvar 💕",
  formMetaCriada: "Sonho anotado, amiga! 🌸✨",
  formMetaAtualizada: "Sonho atualizado 💕",
  formMetaNome: "Qual é o sonho? 🌸",
  formMetaNomePlaceholder: "Ex.: Viagem, Entrada do apê, Trocar de carro",
  formMetaIcone: "Ícone 🎀",
  formMetaIcones: { VIAGEM: "Viagem ✈️", CASA: "Casa 🏠", CARRO: "Carro 🚗", APOSENTADORIA: "Liberdade ✨", GENERICO: "Outro 🌸" },
  formMetaValorAlvo: "Quanto custa esse sonho 💸",
  formMetaJaGuardado: "Já tenho guardado 💗",
  formMetaMesAno: "Pra quando? 🗓️",
  formMetaRende: "Quanto o dinheiro guardado rende por ano ✨",
  formMetaRendeHint: "Poupança rende perto de 6%. CDB e Tesouro Selic, perto de 10%. Se não sabe, deixa 10% 💕",

  formAtivoAdicionar: "Adicionar 💕",
  formAtivoSalvar: "Salvar 💕",
  formAtivoAdicionado: "Investimento adicionado, amiga! 🐷✨",
  formAtivoAtualizado: "Investimento atualizado 💕",
  formAtivoClasse: "Tipo",
  formAtivoQual: "Qual investimento? 🐷",
  formAtivoQualPlaceholder: "Nome ou código",
  formAtivoTicker: "Código (se quiser)",
  formAtivoNomePlaceholderLista: "Preenche sozinho quando você escolhe na lista",
  formAtivoObjetivo: "Pra que serve? 🎯",
  formAtivoObjetivos: { OUTRO: "Outro", RESERVA_EMERGENCIA: "Minha reserva 🛟", LIBERDADE_FINANCEIRA: "Minha liberdade ✨", META: "Um sonho 🌸" },
  formAtivoMetaVinculada: "Qual sonho? 🌸",
  formAtivoQuantidade: "Quantos",
  formAtivoPrecoMedio: "Preço médio que você pagou",
  formAtivoValorAtualOpcional: "Quanto vale hoje (se quiser)",
  formAtivoValorAtualHint: "Deixa em branco que eu busco o preço de hoje e multiplico pela quantidade ✨",
  formAtivoValorInvestido: "Quanto você colocou",
  formAtivoValorAtual: "Quanto vale hoje",

  formOrcPasso: (passo, total) => `Passo ${passo} de ${total} 🎀`,
  formOrcSalvo: "Combinado salvo pro ano inteiro! 🎉",
  formOrcTitulo: "Bora combinar seu mês? 🎀",
  formOrcSub: "Três perguntinhas. Parte das respostas eu já sei pelo que você anotou 💕",
  formOrcQuantoEntra: "Quanto entra por mês? 💸",
  formOrcRenda: "Entra por mês",
  formOrcRendaSugestao: (mes, valor) => `Em ${mes} entraram ${valor} 👀`,
  formOrcQuantoGuardar: "Quanto você quer guardar? 🐷",
  formOrcGuardarPorMes: "Guardar por mês 🐷",
  formOrcCursoNota: (pct, liberdade) =>
    `No curso, a conta é ${pct}%: ${liberdade}% pra sua liberdade e 8% pros sonhos. Quem tá começando costuma conseguir 10% — se apertar, dá pra mudar depois 💕 Nada aqui é promessa, tá?`,
  formOrcSobraTitulo: "Sobra pra gastar 💅",
  formOrcSobraSub: (valor) => `por mês, depois de guardar ${valor} 🐷`,
  formOrcDividir: (valor) => `Dividir os ${valor} →`,
  formOrcDividaTitulo: (valor) => `Divide os ${valor} 🎀`,
  formOrcDistribuido: "Já dividido",
  formOrcSobram: (valor) => `Ainda sobram ${valor} pra dividir 💗`,
  formOrcPassou: (valor) => `Passou ${valor} do que sobra 🫣`,
  formOrcSugerir: "Sugere pra mim ✨",
  formOrcCopiar: (mes) => `Copiar de ${mes}`,
  formOrcSugestaoNota: (moradia, alimentacao, saude, pct) =>
    `A sugestão segue a divisão do curso: moradia ${moradia}% do que entra, alimentação ${alimentacao}%, saúde ${saude}%, e por aí vai. Guardando menos que ${pct}% sobra uma folguinha; guardando mais, tudo encolhe junto. É só um começo, amiga: mexe à vontade 💕`,
  formOrcCustomNota: "Pet, academia, filhos: o que é grande na sua vida e não cabe nas de cima 🐶 O que vem uma vez por ano, divide por 12.",
  formOrcVerPlano: "Ver meu combinado →",
  formOrcSeuPlano: (ano) => `Seu combinado de ${ano} 🎀`,
  formOrcProntoPlano: (ano) => `Prontinho! Seu combinado de ${ano} 🎀✨`,
  formOrcLegGuardados: (pct) => `${pct} guardados 🐷`,
  formOrcLegLivres: (pct) => `${pct} livres 💅`,
  formOrcFimDoAno: "O que isso vira no fim do ano ✨",
  formOrcFimDoAnoValor: (valor) => `${valor} guardados 🐷`,
  formOrcFimDoAnoSub: (valor, meses) => `${valor} por mês nos ${meses} meses que faltam, mais o que sobrar 💕`,
  formOrcPraOnde: "Pra onde vai o que você guarda 💸",
  formOrcPraOndeNota: "Primeiro a reserva, depois os sonhos por data. O resto fica livre 🌸",
  formOrcEntra: "Entra",
  formOrcGuarda: "Guarda",
  formOrcGasta: (categorias) => `Gasta (${categorias} categorias)`,
  formOrcFicaLivre: "Fica livre",
  formOrcEstourou: "As categorias somam mais do que sobra 🫣 Volta e ajusta, ou guarda um pouquinho menos.",
  formOrcSalvar: "Salvar meu combinado 💕",
  formOrcAjustar: "Ajustar as categorias ✏️",
  formOrcRendaEAporte: "O que entra e o que você guarda",
  formOrcPorMes: "Por mês",
  formOrcSemGasto: "nadinha mês passado",
  formOrcApagarTitulo: "Apagar categoria? 🫣",
  formOrcApagarAntes: "Tem certeza que quer apagar",
  formOrcApagarDepois: "? O que você já anotou nela continua existindo, só fica sem categoria.",
  formOrcApagando: "Apagando…",
  formOrcApagar: "Apagar categoria",

  formReservaMediaSugestao: (n) => `Seus gastos ${n === 1 ? "do último mês fechado dão" : `dos últimos ${n} meses fechados dão`} essa média 👀`,
  formReservaCarteiraSugestao: "Nos seus investimentos, isso tá marcado como reserva 🛟",

  formApVidaPergunta: "Quanto custa a vida que você quer? ✨",
  formApVidaHelp: "Quanto você gostaria de gastar por mês vivendo só do que o dinheiro rende, em dinheiro de hoje 💕",
  formApVidaCampo: "Quanto quer gastar por mês",
  formApVidaHint: "Por mês, em dinheiro de hoje.",
  formApOutrasPergunta: "Já tem outras rendas? 💸",
  formApOutrasHelp: "Aluguel, INSS, pensão: o que vai continuar entrando quando você parar de trabalhar. Deixa zerado se não tiver.",
  formApOutrasCampo: "Outras rendas por mês",
  formApInvestidoPergunta: "Quanto você já tem investido? 🐷",
  formApInvestidoHelp: "Tudo que já tá investido hoje e vai fazer parte desse bolo ✨",
  formApInvestidoCampo: "Quanto já tem investido",
  formApAportePergunta: "Quanto consegue guardar por mês? 🐷",
  formApAporteHelp: "O valor que você consegue investir todo mês, em média, enquanto tá guardando 💕",
  formApAporteCampo: "Guardo por mês, em média",
  formApIdadePergunta: "Sua idade e quando quer parar 🗓️",
  formApIdadeHelp: "A idade que você quer chegar na sua liberdade. Até que idade viver disso é opcional 💕",
  formApIdadeAtual: "Idade hoje",
  formApIdadeObjetivo: "Quer parar aos",
  formApExpectativa: "Viver até os",
  formApPremissasPergunta: "Quanto rende, quanto sobe ✨",
  formApPremissasHelp: "Já preenchi com valores comuns, mexe se quiser. Taxas por ano 💕",
  formApRendAcumulo: "Quanto rende enquanto você guarda",
  formApInflacao: "Inflação média",
  formApRendUsufruto: "Quanto rende vivendo de renda",
  formApCalculando: "Fazendo a conta… 🧮",
  formApVerPlano: "Ver meu plano ✨",
  formApGuardarPergunta: "Quanto consegue guardar por mês? 🐷",
  formApGuardarHint: "Vale por esse valor em dinheiro de hoje: o plano assume que você acompanha a inflação 💕",
  formApIdadeHoje: "Sua idade hoje",
  formApPararAos: "Quer parar aos",
  formApPremissas: "As contas por trás 🔍",
  formApPremissasSub: "Os números mais técnicos. Já vieram preenchidos — só abre se quiser mexer 💕",
  formApPremissasNota: "Nenhum desses números é promessa, tá? É o cenário que você escolhe simular ✨",
  formApRendem: "Quanto seus investimentos rendem por ano",
  formApRendemHint: "Antes de descontar a inflação. Se você investe perto do CDI, usa a taxa do CDI 💕",
  formApInflacaoAssume: "A inflação que você imagina",
  formApInflacaoHint: "É ela que traz o dinheiro do futuro pro que ele compra hoje.",
  formApRendVivendo: "Quanto rende já vivendo de renda",
  formApRendVivendoHint: "Um pouco mais cauteloso que o de quando você tá guardando, porque aí você vai depender dele pra viver 🫂",
  formApAteIdade: "Até que idade (se quiser)",
  formApOutrasRendas: "Outras rendas por mês (se quiser)",

  formEstSalva: "Estratégia salva, amiga! 💅✨",
  // Os nomes dos perfis são os do mercado (ficam); só a descrição ganha a voz.
  formEstPerfis: {
    conservador: { nome: "Conservador", descricao: "Prefere saber o que esperar: a maior parte em renda fixa 🛟" },
    moderado: { nome: "Moderado", descricao: "Um pouco de renda fixa, um pouco de renda variável ⚖️" },
    arrojado: { nome: "Arrojado", descricao: "Quer crescer no longo prazo: a maior parte em renda variável 🚀" },
  },
  formEstQuizTitulo: "Não sabe por onde começar? Três perguntinhas 💕",
  formEstAbrir: "abrir",
  formEstFechar: "fechar",
  formEstPrazoPergunta: "Quando você vai precisar desse dinheiro? 🗓️",
  formEstQuedaPergunta: "Se seus investimentos caíssem 15% num mês, você… 🫣",
  formEstQuedaOpcoes: ["Venderia tudo, não ia dormir", "Ficaria tensa, mas seguraria", "Aproveitaria pra comprar mais"],
  formEstReservaPergunta: "Sua reserva já tá completa? 🛟",
  formEstReservaOpcoes: ["Ainda não", "Quase lá", "Sim!"],
  formEstPelasMetasAntes: "Pelos seus sonhos, você vai precisar do dinheiro em",
  formEstNaoEIsso: "Não é isso, quero responder",
  formEstPerfilAntes: "Pelas suas respostas, seu perfil é",
  formEstUsarPerfil: "Usar esse perfil 💕",
  formEstPronto: "Ou começa de um perfil pronto (dá pra mexer depois) 🎀",
  formEstComoFicaria: "Como seus investimentos ficariam ✨",
  formEstFecha: "✓ fecha em 100% 🥳",
  formEstNaoFecha: "— precisa somar 100%",
  formEstSalvar: "Salvar estratégia 💕",

  formLancDescricao: "O que foi? (se quiser)",
  formLancDescricaoPlaceholder: "Ex.: o nome do lugar, o que você comprou",
  formLancValor: "Quanto 💸",
  formLancData: "Quando 🗓️",
  formLancMetaVinculada: "É de algum sonho? (se quiser) 🌸",
  formLancNenhuma: "Nenhum",
  formLancRepetir: (ano) => `Repetir todo mês (gasto fixo) até dezembro de ${ano} 🔁`,
  formLancSalvar: "Salvar 💕",
  formLancLancar: "Anotar 💕",
};

// Importação: a gaveta Anotar, o fluxo de voz, os importadores, o histórico, "Parece que se
// repete" e o Resumo Mensal. Instruções e avisos continuam dizendo o que fazer.
const GIRLY_IMP: Partial<Titulos> = {
  impVoltar: "Voltar",
  impDigitar: "Digitar 📝",
  impGravarAudio: "Me contar por voz 🎤",
  impImportarArquivo: "Mandar o extrato ou a fatura (PDF, Excel, CSV, OFX) 📄",
  impConectarBanco: "Conectar meu banco 🏦",
  impConectarBancoSub: "Open Finance · o que você gasta chega sozinho, todo dia ✨",
  impVozSegure: "Segura pra falar 🎤",
  impVozSolte: "Solta que eu anoto ✨",
  impVozNaoSuportado: "Seu navegador não sabe ouvir voz 🫣 Usa a opção de digitar, amiga.",
  impVozNaoEntendi: "Não entendi o que você disse 🫣 Fala de novo?",
  impVozErroPermissao: "Libera o microfone nas configurações do navegador e tenta de novo 🎤",
  impVozErroSemFala: "Não consegui te ouvir 🫣 Chega mais perto do microfone e tenta de novo.",
  impVozErroRede: "A internet caiu no meio da gravação 🫣 Tenta de novo?",
  impVozErroSemMicrofone: "Não achei nenhum microfone nesse aparelho 🎤",
  impVozErroGenerico: "Não deu pra gravar agora 🫣 Tenta de novo?",
  impVozSafariDica: "Cansada de liberar o microfone toda vez? O Safari pergunta de novo a cada visita 🙄",
  impLendoArquivo: "Lendo seu arquivo… 👀",
  impErroEnvio: "Não consegui enviar o arquivo 🫣 Dá uma olhada na internet e tenta de novo.",
  impErroSalvar: "Não consegui salvar 🫣 Dá uma olhada na internet e tenta de novo.",
  impProtegido: "Esse arquivo tem senha 🔒",
  impSenhaPlaceholder: "Senha do arquivo",
  impAbrindo: "Abrindo…",
  impDesbloquear: "Abrir e continuar ✨",
  impOutroArquivo: "Escolher outro arquivo",
  impAplicando: "Aplicando…",
  impPular: "Pular",
  impRemover: "Tirar",
  impConcluir: "Prontinho ✨",
  impArquivoGrande: "Arquivo grande demais (o máximo são 4 MB) 🫣 Exporta um período menor, ou salva em Excel (.xlsx) ou CSV, que pesam bem menos que PDF.",
  impOQueSubindo: "O que você tá me mandando? 📄",
  impTipoExtrato: "Extrato do banco",
  impTipoFatura: "Fatura do cartão",
  impExtratoDica: "O que entrou vira renda e o que saiu vira gasto, pelo sinal do valor ✨",
  impFaturaDica: "Todas as linhas entram como gasto (as compras do cartão) 💳",
  impFaturaMes: "Essa fatura é de qual mês? 🗓️",
  impFaturaMesDica: (mes) =>
    `Todas as compras dessa fatura vão entrar em ${mes}, até as que aconteceram no mês anterior (a fatura costuma fechar cruzando dois meses) 💕`,
  impEscolherExtrato: "Escolher o extrato 📄",
  impFormatosBanco: "CSV, OFX, Excel ou PDF do seu banco",
  impSenhaDicaBanco: "Quase sempre é o seu CPF, só os números 💕 Se não for, a senha vem escrita no e-mail em que o banco mandou o arquivo.",
  impPareceOutroTipo: (sugerido, atual, motivo) =>
    `Amiga, esse arquivo parece ${sugerido === "fatura" ? "uma fatura de cartão" : "um extrato do banco"}${motivo ? ` (${motivo})` : ""}, não ${atual === "fatura" ? "uma fatura" : "um extrato"} 🤔`,
  impPareceFaturaAviso: "Se entrar como extrato, cada compra do cartão vira renda no seu mês 🫣",
  impPareceExtratoAviso: "Se entrar como fatura, cada entrada da conta vira gasto 🫣",
  impImportarComo: (tipo) => `Entrar como ${tipo === "fatura" ? "fatura" : "extrato"}`,
  impEMesmo: (tipo) => `É ${tipo === "fatura" ? "fatura" : "extrato"} mesmo 💕`,
  impRevisar: (atual, total) => `Conferindo ${atual} de ${total} 👀`,
  impParcela: (atual, total, restantes) => `Parcela ${atual} de ${total}: as ${restantes} seguintes entram sozinhas nos próximos meses ✨`,
  impQualCategoria: "Isso é o quê? 🤔",
  impOutra: "Outra",
  impNovaCategoriaPlaceholder: "Nome da categoria (ex.: Fatura, Pet, Farmácia)",
  impCriando: "Criando…",
  impCriarEUsar: "Criar e usar 💕",
  impNovaCategoriaDica: "A categoria nova já aparece no seu combinado pra você dizer quanto quer gastar nela 🎀",
  impSemCategoriaTitulo: (n) => `${n} gasto${s(n)} sem categoria ${n === 1 ? "ficou" : "ficaram"} de fora 🫣`,
  impSemCategoriaSub: (n, soma) => `${n === 1 ? "Ele não entra" : "Eles não entram"} na importação. ${n === 1 ? "Dá" : "Somam"} ${soma}.`,
  impCategorizar: (n) => `Dizer o que ${n === 1 ? "é esse gasto" : "são esses gastos"} →`,
  impNumerosErrados: "Esses números parecem errados 🤔",
  impNumerosErradosDica:
    "Confere a lista aqui embaixo antes de confirmar. Se tiver errado mesmo, fala comigo — já guardei uma cópia do arquivo e ensino o app a ler esse banco 💕",
  impFalarComAGente: "Falar comigo 💬",
  impResumoLancamentos: (n, valor) => `${n} anotaç${n === 1 ? "ão" : "ões"} · ${valor}`,
  impEntendiComo: (resumo) => `Entendi assim: ${resumo} 💕`,
  impLinhasLidas: (lidas, total) => `Li ${lidas} de ${total} linhas com valor no arquivo 👀`,
  impTotalImpresso: (valor) => `Total escrito na fatura: ${valor}.`,
  impCoberturaBaixa: "Menos da metade das linhas com valor virou anotação 🫣 Confere se não ficou faltando alguma coisa.",
  impFaltouCoisa: "Faltou coisa, me ajuda 🙋‍♀️",
  impSomaDiferente: (abaixo, diferenca) =>
    `A soma que eu li ${abaixo ? "ficou" : "passou"} ${diferenca} ${abaixo ? "abaixo" : "acima"} do total escrito na fatura 🤔 Pode estar faltando (ou sobrando) alguma linha.`,
  impRepetidos: "Repetidos no arquivo 👯‍♀️",
  impRepetidosDica: "Mesma data, valor e descrição mais de uma vez. Se foi compra de verdade, deixa; se é o arquivo repetindo, deixa só uma 💕",
  impDeixarSo1: "Deixar só 1",
  impImportando: "Anotando tudo…",
  impImportarN: (n) => `Anotar ${n} lançamento${s(n)} 💕`,
  impImportadosSucesso: (n) => `${n} lançamentos anotados! Boaaaa 🎉`,
  impToastImportados: (n) => `${n} lançamentos anotados 💕`,
  impToastJaExistiam: (n) => `${n} já estavam aqui (pulei) 💅`,
  impPagamentoFatura: (n) =>
    `Achei ${n === 1 ? "esse lançamento" : "esses lançamentos"} no seu extrato que ${n === 1 ? "pode ser" : "podem ser"} o pagamento dessa fatura 👀 Quer tirar pra não contar o gasto duas vezes?`,
  impSemData: "sem data",
  impRemovidoExtrato: "Tirei do extrato ✨",
  impManter: "Deixar",
  impCarteiraArquivoGrande: "Arquivo grande demais (o máximo é uns 7 MB) 🫣 Exporta um relatório menor e tenta de novo.",
  impCarteiraEscolher: "Escolher o arquivo da corretora 📄",
  impCarteiraFormato: "Posição da corretora ou da B3 (CSV, Excel ou PDF)",
  impSenhaDicaCorretora: "Digita a senha do arquivo (a mesma que a corretora pede pra abrir). Ela só serve pra abrir e não fica salva, prometo 💕",
  impCarteiraLiTudo: (resumo) => `Li o arquivo inteirinho: ${resumo} ✨`,
  impCarteiraEmDia: (n) => `Seus investimentos já estão em dia com esse extrato: conferi ${n} e não mudou nadinha 🎉`,
  impCarteiraNovos: "Novos nos seus investimentos ✨",
  impCarteiraSemValor: "sem valor",
  impCarteiraMudancas: "O que mudou 👀",
  impCarteiraSemMudanca: (n) => `${n} sem mudança: já ${n === 1 ? "está" : "estão"} nos seus investimentos e ${n === 1 ? "fica" : "ficam"} como ${n === 1 ? "está" : "estão"} 💕`,
  impCarteiraFeito: (criados, atualizados) =>
    [criados > 0 ? `${criados} novo${s(criados)} nos seus investimentos` : null, atualizados > 0 ? `${atualizados} atualizado${s(atualizados)}` : null]
      .filter(Boolean)
      .join(" · ") || "Nada pra mudar, já tava tudo em dia 💅",
  impIrpfArquivoGrande: "Arquivo grande demais (o máximo é uns 7 MB) 🫣",
  impIrpfSelecioneUm: "Escolhe pelo menos um investimento pra aplicar o preço médio 💕",
  impIrpfIntro: [
    "Sua declaração de IR tem o ",
    "preço médio",
    " de cada ação e FII (quanto você pagou), que os extratos da corretora não trazem. Manda o PDF do recibo da declaração que eu preencho quanto você colocou em cada um, pra o lucro ou prejuízo calcular certinho ✨",
  ],
  impIrpfLendo: "Lendo a declaração… 👀",
  impIrpfEscolher: "Escolher o PDF da declaração 📄",
  impIrpfEncontrei: (n) => `Achei ${n} investimento${s(n)} com preço médio ✨`,
  impIrpfConfira: "Confere em cada linha qual dos seus investimentos é (as que a declaração só traz o nome da empresa vêm sem par — escolhe à mão ou deixa de fora) 💕",
  impIrpfInvestido: "colocado",
  impIrpfNaoAplicar: "Não aplicar",
  impIrpfComoFunciona: "O preço médio vira o quanto você colocou (preço médio × quantidade). O preço de hoje não muda, só o que você colocou, que é a base do lucro ou prejuízo.",
  impIrpfAplicarEm: (n) => `Aplicar em ${n} investimento${s(n)} 💕`,
  impIrpfConcluido: (n) => `Preço médio preenchido em ${n} investimento${s(n)}! Agora o lucro ou prejuízo deles calcula certinho 🎉`,
  impHistoricoTitulo: "O que você já me mandou 📄",
  impHistoricoExtrato: "Extrato",
  impHistoricoFatura: "Fatura",
  impHistoricoBanco: "Banco conectado",
  impHistoricoLancamentos: (n) => `${n} lançamento${s(n)}`,
  impHistoricoDesfazer: "Desfazer",
  impHistoricoConfirmar: "Apaga mesmo? 🫣",
  impHistoricoDesfeita: (n) => `Desfiz a importação: ${n} lançamento${s(n)} apagado${s(n)}.`,
  impHistoricoNota: "Desfazer uma importação apaga tudo que aquele arquivo anotou. As que você mandou antes desse histórico existir não aparecem aqui 💕",
  impRepeteTitulo: "Acho que isso se repete 🔁",
  impRepeteSub: "Tava nos meses anteriores e ainda não tá nesse. Um toque e eu anoto 💕",
  impRepeteLancamento: "Lançamento",
  impRepeteCostumaCair: (dia) => `costuma cair dia ${dia}`,
  impRepeteVistoEm: (n) => `${n} dos últimos 3 meses`,
  impRepeteLancar: "Anotar 💕",
  impRepeteTodoMes: "Todo mês 🔁",
  impRepeteLancado: "Anotado! 💕",
  impRepeteLancadoAteDezembro: "Anotei nesse mês e nos próximos até dezembro ✨",
  impRepeteErro: "Não consegui anotar 🫣 Tenta de novo?",
  impResumoPronto: "Seu resumo do mês tá pronto! 🎀",
  impResumoProntoSub: "Vem ver o que aconteceu com o seu dinheiro esse mês 💕",
  impStoryTitulo: "Resumo do mês 🎀",
  impStorySub: "O que aconteceu com o seu dinheiro esse mês, amiga 💕",
  impStoryGastou: "Esse mês você gastou",
  impStoryMaiorParte: "A maior parte foi com",
  impStoryComparado: "Comparando com o mês passado, você gastou",
  impStoryDelta: (pct, menos) => `${pct}% ${menos ? "a menos 👏" : "a mais 🫣"}`,
  impStoryEsteMes: "Esse mês",
  impStoryMesPassado: "Mês passado",
  impStoryDiaEconomico: "Seu dia da semana mais econômico foi",
  impStoryDiaGastador: "O dia da semana que mais saiu dinheiro foi",
  impStoryDiaGastadorCom: (valor) => `com ${valor} 🛍️`,
  impStoryDesdeQueChegou: (meses, positivo) =>
    `Desde que você chegou aqui (${meses} ${meses === 1 ? "mês" : "meses"}),${positivo ? " ficou no seu bolso" : " o saldo ficou"}`,
  impStoryAcumuladoRuim: "Mês a mês dá pra virar esse jogo, amiga 🫂 O primeiro passo é olhar o número.",
  impStoryProjecaoUnica: "Se você investisse hoje, de uma vez, tudo que já juntou, em 10 anos isso vira até… ✨",
  impStoryProjecaoUnicaNota: (valor) => `*${valor} investidos de uma vez, rendendo 10% ao ano. É uma estimativa pra te dar uma ideia, não promessa 💕`,
  impStoryProjecaoMensal: "Guardando todo mês o que você costuma guardar, e deixando render, em 10 anos isso vira até… ✨",
  impStoryProjecaoMensalNota: (valor) =>
    `*${valor}/mês (o que você guardou no ano ÷ meses preenchidos), rendendo 10% ao ano. É uma estimativa pra te dar uma ideia, não promessa 💕`,
  impStoryDestaques: "Destaques ✨",
  impStoryGastosDoMes: "Gastos do mês 💸",
  impStoryNoBolso: "No bolso desde o início 💗",
  impStoryPotencial: "Em 10 anos, guardando o que você costuma guardar ✨",
  impStoryGerando: "Montando sua imagem… 🎀",
  impStoryCompartilhar: "Compartilhar meu resumo 💕",
  impShareTitulo: "Meu resumo do mês 🎀",
  impShareImagemTitulo: ["Meu resumo", "do mês 🎀"],
  impShareGastei: "Gastei esse mês",
  impShareFicouNoBolso: "Ficou no meu bolso desde o início 💗",
  impShareSaldo: "Saldo desde o início",
  impSharePotencial: "Em 10 anos, guardando o que eu costumo guardar ✨",
  impShareTexto: (periodo, gastei, positivo, saldo, potencial) =>
    [
      `Meu resumo do mês (${periodo}) 🎀`,
      `• Gastei ${gastei}`,
      `• ${positivo ? "Ficou no bolso" : "Saldo"} desde o início: ${saldo}`,
      `• Em 10 anos pode virar: ${potencial} ✨`,
    ].join("\n"),
};

// Shell: primeiros passos, o tour, os cartões do mês, a lista de lançamentos, instalar no
// celular, o cartão do curso e as telas de erro. Os passos de instalar ficam no Padrão: são
// instrução, e o caminho muda entre Safari e Chrome.
const GIRLY_UI: Partial<Titulos> = {
  uiPrimeirosPassos: "Seus primeiros passos 🌸",
  uiPassoRegistrar: "Anota seu primeiro gasto, ou o que entrou 📝",
  uiPassoOrcamento: "Combina comigo quanto quer gastar no mês 🎀",
  uiPassoCarteira: "Me conta o que você já tem investido 🐷",
  uiDispensarGuia: "Já sei me virar 💅",

  uiTourBoasVindasTitulo: "Oii, bem-vinda ao SPI Finance 💕",
  uiTourBoasVindasTexto: "Um tour rapidinho mostrando ONDE fica cada coisa: vou destacar os botões um por um. Pula quando quiser 🎀",
  uiTourRegistrarTitulo: "Esse + é o coração do app 💗",
  uiTourRegistrarTexto: "É por aqui que você me conta tudo: digita um gasto, fala por voz ou manda o extrato do banco. Começa sempre por ele 💕",
  uiTourFluxoTitulo: "Aqui é o seu mês 💸",
  uiTourFluxoTexto: "Seu mês num lugar só: o que entrou, o que saiu e o combinado por categoria, com um aviso quando o cartão tá correndo demais 💳🫣",
  uiTourMetasTitulo: "Aqui são seus sonhos 🌸",
  uiTourMetasTexto: "Anota seus sonhos (viagem, casa), sua reserva e sua liberdade. Eu te digo quanto guardar por mês pra chegar lá ✨",
  uiTourCarteiraTitulo: "Aqui são seus investimentos 🐷",
  uiTourCarteiraTexto: "Tudo que você tem investido e quanto cada um rendeu. Dá até pra puxar o preço médio direto da sua declaração de Imposto de Renda ✨",
  uiTourMaisTitulo: "E tem mais aqui 💕",
  uiTourMaisTexto: "Visão geral, Calculadoras e Análises ficam nesse menu.",
  uiTourFimTitulo: "Tudo pronto, amiga! 🎉🥳",
  uiTourFimTexto: "Bora? Toca no + e anota seu primeiro gasto: em segundos você já vê seu mês tomando forma ✨",
  uiTourPular: "Pular",
  uiTourAvancar: "Próximo 💕",
  uiTourComecar: "Bora! ✨",

  uiFluxoTituloFuturo: (mes) => `O que já tá marcado pra ${mes} 🗓️`,
  uiFluxoTituloCorrente: (mes) => `Como ${mes} tá indo 👀`,
  uiFluxoTituloFechado: (mes) => `Como foi ${mes} 🌸`,
  uiFluxoDicaFuturo: "O que se repete e o que já tá agendado. O mês ainda nem começou 💕",
  uiFluxoDicaCorrente: "A faixa entre as duas linhas é o que sobrou até agora 💗",
  uiFluxoDicaFechado: "A faixa entre as duas linhas é o que sobrou 💗",
  uiFluxoSemData: (quantos, valor) =>
    quantos === 1
      ? `1 lançamento sem data (${valor}) não entra nessa curva, mas conta no total do mês 💕`
      : `${quantos} lançamentos sem data (${valor}) não entram nessa curva, mas contam no total do mês 💕`,

  uiRendaDividida: "Pra onde foi o que entrou 💸",
  uiRendaCentro: "Entrou",
  uiRendaFatiaGastos: "Gastos",
  uiRendaFatiaAportes: "Guardou",
  uiRendaFatiaSobrou: "Sobrou",
  uiRendaGastouAMais: (valor) => `Saiu ${valor} a mais do que entrou esse mês 🫣`,
  uiRendaManteve: (pct) => `Você segurou **${pct}** do que entrou (entre o que guardou e o que sobrou) 💗`,

  uiMaioresGastos: "Onde mais saiu dinheiro 🛍️",
  uiSetaCompara: "A setinha compara com o mês passado. Diferença menor que 8% não aparece, é oscilação normal 💕",

  uiHeatmapDica: "Um quadradinho por dia, mais forte onde saiu mais dinheiro 🌸",
  uiHeatmapPico: (dia, valor) => `Dia que mais saiu: ${dia} · ${valor} 🫣`,

  uiSelecionar: "Escolher",
  uiVerMaisLancamentos: (quantos) => `Ver mais ${quantos} 👀`,
  uiSairDaSelecao: "Deixa pra lá",
  uiEditar: "Mexer ✏️",
  uiRemover: "Tirar",
  uiEditarLancamento: "Mexer no lançamento ✏️",
  uiRemoverLancamento: "Tirar lançamento",
  uiTipoRenda: "Entrou",
  uiTipoGasto: "Gasto",
  uiTipoAporte: "Guardou",
  uiExcluido: (quantos) => (quantos === 1 ? "Tirei o lançamento ✨" : `Tirei ${quantos} lançamentos ✨`),
  uiExcluidoContinuaNaCarteira: "O que já tava dividido nos seus investimentos continua lá 💕",
  uiDesfazer: "Desfazer",
  uiRestaurado: (quantos) => (quantos === 1 ? "Voltou! 💕" : `Os ${quantos} voltaram! 💕`),
  uiRestaurarFalhou: "Não consegui trazer de volta 🫣 Anota de novo, amiga.",

  uiInstalarConviteTitulo: "Coloca no seu celular 📲",
  uiInstalarConviteSub: "Abre em tela cheia, com ícone próprio ✨",
  uiInstalarVerComo: "Me mostra como",
  uiInstalarFecharConvite: "Agora não",
  uiInstalarTitulo: "Colocar na tela de início 📲",
  uiInstalarIntro:
    "O SPI Finance funciona como um app: ícone próprio na tela inicial e tela cheia, sem a barra do navegador. Não ocupa espaço como app de loja e se atualiza sozinho ✨",
  uiInstalarAgora: "Instalar agora 💕",
  uiInstalando: "Instalando…",
  uiInstalarNativoDica: "Seu navegador deixa instalar direto: toca no botão e confirma na janelinha que aparecer ✨",
  uiInstalarNoComputador: "Você tá no computador 💻 Pra ter o app no celular, abre o site pelo navegador do telefone e repete esses passos por lá.",

  uiPaywallTitulo: (recurso) => `${recurso} é coisa do curso 🎀`,
  uiPaywallTexto:
    "Essa parte faz parte do curso de investimentos, amiga 💕 Se você já é aluna e tá vendo essa mensagem por engano, fala com o suporte — pode ser só o e-mail de cadastro diferente do e-mail da compra.",
  uiPaywallBotao: "Conhecer o curso ✨",

  uiMudarParaEscuro: "Mudar pro tema escuro 🌙",
  uiMudarParaClaro: "Mudar pro tema claro ☀️",
  uiAparencia: "Aparência 🎀",

  uiErroTitulo: "Ops, deu ruim aqui 🫣",
  uiErroTexto: "Foi erro meu, não seu, e seus dados estão seguros 💕 Tenta recarregar; se continuar, sai e entra de novo.",
  uiErroTentarDeNovo: "Tentar de novo 💕",
  uiNaoEncontradoTitulo: "Essa página não existe 🫣",
  uiNaoEncontradoTexto: "Confere o endereço ou volta pro início, amiga — seu dinheirinho tá te esperando lá 💕",
  uiNaoEncontradoVoltar: "Voltar pro início 🏠",
};

// Configurações, perfis e o planejador de viagem. O que é nome de aba, campo técnico (taxas
// do sistema, base de cálculo) ou aviso de segurança fica no Padrão, ou só ganha o tom.
const GIRLY_CFG: Partial<Titulos> = {
  cfgBreadcrumb: "Ajustes",
  cfgAbaPerfil: "Você 💕",
  cfgAbaPreferencias: "Do seu jeito",
  cfgAbaTaxas: "Taxas",
  cfgSalvar: "Salvar 💕",
  cfgSalvando: "Salvando…",
  cfgPerfilTitulo: "Você 💕",
  cfgPerfilSub: "Suas informações, amiga 🎀",
  cfgPerfilNomePlaceholder: "Seu nome",
  cfgPerfilEmailDica: "É o e-mail que você usa pra entrar. Pra trocar, fala com o suporte 💕",
  cfgPerfilFoto: "Link da sua foto (se quiser) 📸",
  cfgPreferenciasTitulo: "Do seu jeito 🎀",
  cfgPreferenciasSub: "Moeda e o tema da tela ✨",
  cfgModoDecididoPeloTema: "Claro ou escuro quem decide é o tema do perfil que você tá usando. Pra escolher, muda o tema em Seus perfis — só o Padrão tem os dois 💕",
  cfgMoedaAviso: ["Trocar a moeda ", "não converte seus valores", ", tá? 🫣"],
  cfgMoedaAvisoTexto1: (exemploNovo, exemploAntigo) =>
    `Os números continuam exatamente os mesmos, só o símbolo muda. Um lançamento de 3.000 passa a aparecer como "${exemploNovo}" em vez de "${exemploAntigo}". Usa se a sua vida financeira é toda em outra moeda 💕`,
  cfgMoedaAvisoTexto2:
    "Se só uma parte é em outra moeda (um salário em euro, um aluguel em real), deixa a moeda principal aqui e escolhe a moeda na hora de anotar: aí sim eu converto pela cotação do dia ✨",
  cfgAplicadoAoSalvar: "Moeda e tema mudam assim que você salva 💕",
  cfgCategoriasTitulo: "Categorias 🎀",
  cfgCategoriasSub: "As categorias e subcategorias que já vêm prontas pra você dizer onde cada gasto foi. Em qualquer lançamento, o chip 'Outro' deixa você escrever uma subcategoria sua 💕",
  cfgNotificacoesTitulo: "Avisos 🔔",
  cfgNotificacoesSub: "Avisos no celular, o resumo por e-mail e o que aparece em Análises 💕",
  cfgResumoEmail: "Resumo do mês por e-mail 💌",
  cfgResumoEmailDica: "Uma vez por mês, no comecinho: quanto entrou, quanto saiu e o que mudou 💕",
  cfgAlertasOrcamento: "Avisos do combinado 🎀",
  cfgAlertasOrcamentoDica: "Quando uma categoria já gastou 80% do combinado com metade do mês pela frente, ou já passou. Chega no celular (se ligado) ou por e-mail 💕",
  cfgMetasAtrasadas: "Sonhos atrasadinhos 🫣",
  cfgMetasAtrasadasDica: "Quando um sonho fica pra trás do ritmo. Um aviso por sonho por mês 💕",
  cfgPushTitulo: "Avisos no celular 📲",
  cfgPushDica: "Uma mensagem no celular, como as de um app: quando uma categoria tá perto de passar do combinado e ainda falta metade do mês, ou um sonho ficou pra trás. Sem e-mail 💕",
  cfgPushLigadoEm: (n) => `Ligado em ${n} aparelho${s(n)} ✨`,
  cfgPushVerificando: "Olhando esse aparelho…",
  cfgPushIos: "No iPhone, os avisos só funcionam com o app na tela de início 📲 Toca em Compartilhar › Adicionar à Tela de Início, abre por lá e volta aqui 💕",
  cfgPushNaoSuportado: "Esse navegador não recebe avisos 🫣 No celular, coloca o app na tela de início.",
  cfgPushBloqueado: "Você bloqueou os avisos desse site 🫣 Libera nas configurações do navegador pra ligar de novo.",
  cfgPushLigar: "Ligar avisos nesse aparelho 🔔",
  cfgPushLigando: "Ligando…",
  cfgPushLigadoAqui: "Ligado aqui ✨",
  cfgPushDesligar: "Desligar nesse aparelho",
  cfgPushLigadoToast: "Avisos ligados nesse aparelho 💕",
  cfgPushFalhouToast: "Não consegui ligar os avisos aqui 🫣 Tenta de novo?",
  cfgConexoesTitulo: "Conectar meu banco 🏦",
  cfgConexoesSub: "Open Finance: o que entra e sai da conta e do cartão chega sozinho, toda noite ✨",
  cfgConexoesDesligada: "Conectar banco ainda não tá ligado nesse app 🫣 Por enquanto, o caminho é Anotar › Manda o extrato ou a fatura.",
  cfgConexaoConectado: (banco) => `${banco} conectado ✨`,
  cfgConexaoConectadoToast: (banco) => `${banco} conectado! 🎉`,
  cfgConexaoNadaNovo: "Nada novo por enquanto 🌸 Eu olho de novo toda noite.",
  cfgConexaoChegaram: (novos, semCategoria) => `Chegaram ${novos} lançamentos dos últimos 90 dias${semCategoria > 0 ? `, ${semCategoria} sem categoria` : ""} 💕`,
  cfgConexoesIntro: "Pelo Open Finance oficial, através do Meu Pluggy, um site parceiro gratuito. Depois de conectado, eu busco seus lançamentos toda noite. Nada de arquivo ✨",
  cfgConexoesPasso1: "Cria sua conta no Meu Pluggy",
  cfgConexoesPasso1Dica: "É um site parceiro, gratuito. Abre em outra aba e volta aqui 💕",
  cfgConexoesPasso2: "Conecta seu banco lá",
  cfgConexoesPasso2Dica: "Nubank, Itaú, Inter, C6… O banco pede sua autorização pelo app dele. Cartão entra junto 💳",
  cfgConexoesPasso3: "Deixa o SPI ler",
  cfgConexoesPasso3Dica: "Volta pra cá e toca em autorizar. Só leitura: o SPI não mexe no seu dinheiro, prometo 💕",
  cfgConexoesAutorizar: "Já conectei lá → deixar o SPI ler",
  cfgConexoesRodape: "Seus dados do banco passam pela Pluggy, empresa regulada pelo Banco Central, e chegam ao SPI só como lançamentos. Você desconecta quando quiser aqui. Se preferir, continua mandando o extrato 💕",
  cfgBancosConectados: "Seus bancos conectados 🏦",
  cfgConexaoAindaNaoBuscou: "ainda não buscou",
  cfgConexaoReautorizar: "precisa autorizar de novo",
  cfgBuscarAgora: "Buscar agora ✨",
  cfgConexaoNovos: (novos) => `${novos} lançamento${s(novos)} novo${s(novos)} 💕`,
  cfgDesconectarConfirma: (banco) => `Desconectar ${banco}? O que já entrou fica 💕`,
  cfgDesconectadoToast: "Desconectado ✨",
  cfgConexaoNaoDeu: (motivo) => `Não deu 🫣 ${motivo}`,
  cfgConexaoNaoConcluida: "A conexão não terminou 🫣",
  cfgConexaoNaoAbriu: "Não consegui abrir a conexão agora 🫣",
  cfgDadosTitulo: "Seus dados 📝",
  cfgDadosSub: "Baixa seus dados ou apaga sua conta.",
  cfgExportLancamentosDica: "Gera um arquivo CSV com tudo que você anotou (o que entrou, gastos e o que guardou), com categoria e subcategoria 💕",
  cfgExportLancamentos: "Baixar meus lançamentos (CSV)",
  cfgExportCarteiraDica: "Gera um arquivo CSV com todos os seus investimentos (nome, código, tipo, quantidade, quanto colocou e quanto vale hoje) 💕",
  cfgExportCarteira: "Baixar meus investimentos (CSV)",
  cfgExportando: "Baixando…",
  cfgExportFalhou: "Não consegui baixar seus dados 🫣 Tenta de novo?",
  cfgExcluirContaTitulo: "Apagar minha conta 🫣",
  cfgExcluirContaTexto: ["Apaga a conta e ", "todos os seus dados", " (lançamentos, combinados, sonhos, investimentos) de vez. Não tem volta, amiga: se quiser guardar algo, baixa antes 💕"],
  cfgExcluirContaQuero: "Quero apagar minha conta",
  cfgExcluirContaSenha: "Digita sua senha pra confirmar",
  cfgExcluirContaBotao: "Apagar tudo de vez",
  cfgExcluindo: "Apagando…",
  cfgTaxasSub: "As taxas que eu uso como referência nos planos e nas calculadoras ✨",
  cfgTaxaSua: "Sua taxa 💕",
  cfgTaxaAdicionadaToast: "Taxa adicionada ✨",
  cfgTaxasVazio: "Nenhuma taxa por aqui ainda 🌸",
  cfgPerfisTitulo: "Seus perfis 🎀",
  cfgPerfisSub: "Cada perfil é um dinheiro separado: lançamentos, sonhos e investimentos não se misturam entre eles 💕",
  cfgPerfisGerenciar: "Mexer nos perfis ✏️",
  cfgPerfisEmUso: "usando agora ✨",
  cfgPerfisUsar: "Usar 💕",
  cfgPerfisEditar: "Mexer ✏️",
  cfgPerfisNovo: "Novo perfil 🎀",
  cfgPerfisEditarTitulo: "Mexer no perfil ✏️",
  cfgPerfisCriar: "Criar perfil 💕",
  cfgPerfisTrocouToast: (nome) => `Agora você tá no ${nome} 💕`,
  cfgPerfisAtualizadoToast: "Perfil atualizado ✨",
  cfgPerfisCriadoToast: (nome) => `Perfil ${nome} criado! Você já tá nele 🎉`,
  cfgPerfisExcluidoToast: (nome) => `Perfil ${nome} apagado.`,
  cfgPerfisFalhou: "Não consegui fazer isso agora 🫣",
  cfgPerfisNomePlaceholder: "Empresa, Casal, Casa…",
  cfgPerfisTema: "Tema 🎀",
  cfgPerfisIcone: "Ícone",
  cfgPerfisExcluirTitulo: "Apagar perfil 🫣",
  cfgPerfisExcluirTexto: ["Apagar ", " apaga junto tudo que tá dentro dele: lançamentos, combinado, sonhos e investimentos. Isso não tem como desfazer, amiga."],
  cfgPerfisEscrevaParaConfirmar: (nome) => `Escreve ${nome} pra confirmar`,
  cfgPerfisExcluirParaSempre: "Apagar pra sempre",
  viagemTitulo: "Planejar viagem ✈️",
  viagemSub: "Eu te digo mais ou menos quanto custa o destino dos seus sonhos e transformo num sonho com valor pra guardar por mês 💕",
  viagemRoteiro: "Roteiro 🗺️",
  viagemMaxDestinos: (max) => `Dá pra colocar até ${max} destinos na mesma viagem 💕`,
  viagemVazio: "Busca o primeiro destino ali em cima ✈️ Dá pra somar vários lugares na mesma viagem e dizer quantos dias fica em cada um 💕",
  viagemBuscarPlaceholder: "Buscar destino (ex.: Paris, Jeri, Japão)",
  viagemNenhumDestino: "Não achei esse destino 🫣 Tenta outro nome ou o país.",
  viagemQuantasPessoas: "Quantas pessoas vão? 👯‍♀️",
  viagemEstilo: "Estilo da viagem 🎀",
  viagemQuando: "Quando você pretende ir? 🗓️",
  viagemAltaTemporada: "Alta temporada 🫣",
  viagemAltaTemporadaDica: (pct) => `— passagem e hospedagem ficam uns ${pct}% mais caras nesse mês.`,
  viagemBaixaTemporada: "Baixa temporada 💅",
  viagemBaixaTemporadaDica: (pct) => `— boa época: passagem e hospedagem saem uns ${pct}% mais baratas.`,
  viagemMesMaisBarato: ["Em ", " a mesma viagem sai ", " mais barata 👀"],
  viagemTrocar: "Trocar",
  viagemMediaDica: "Esses valores são a média pra uma viagem como a sua. Se o seu bolso for diferente, é só tocar no número e ajustar — o total refaz a conta na hora ✨",
  viagemExtraPlaceholder: "Ex.: comprinhas, seguro…",
  viagemAdicionarCategoria: "Adicionar categoria 💕",
  viagemMargem: "Folga pra imprevistos (10%)",
  viagemDiariasPorDestino: "Por dia em cada destino (sem passagem)",
  viagemDeOndeVemCusto: "De onde vem o custo 👀",
  viagemCustoEstimado: "Mais ou menos quanto custa a viagem ✈️",
  viagemPorPessoa: (porPessoa, porMes, meses) => `${porPessoa} por pessoa · guardando ${porMes}/mês, você chega lá em ${meses} ${meses === 1 ? "mês" : "meses"} 💕`,
  viagemMetaCriadaToast: "Sonho da viagem anotado! Vê em Sonhos 🌸",
  viagemVerMeta: "Ver meu sonho em Sonhos 🌸",
  viagemCriarMeta: "Transformar em sonho 🌸",
  viagemCriandoMeta: "Anotando o sonho…",
  viagemRodape: "São estimativas médias pra planejar (valores de 2026, saindo do Brasil) — não é cotação, tá? A passagem considera uma ida e volta principal mais as conexões entre os destinos. Ajusta os valores ao seu bolso; mudar o roteiro, as pessoas ou o estilo refaz tudo 💕",
};

// Carteira: a lista de investimentos, "você guardou X, foi pra onde?", por sonho, Análises, a
// página de um sonho e os gráficos. Tickers e nomes de mercado ficam.
const GIRLY_CART: Partial<Titulos> = {
  cartSuaCarteira: (n) => `Seus investimentos · ${n} 🐷`,
  cartMostrarValores: "Mostrar valores 👀",
  cartOcultarValores: "Esconder valores 🙈",
  cartDesdeACompra: (v) => `${v} desde que você comprou`,
  cartNovoAtivo: "Novo investimento 💕",
  cartImportar: "Mandar arquivo 📄",
  cartPrecoMedioIR: "Preço médio (IR)",
  cartAtualizando: "Atualizando…",
  cartAtualizarCotacoes: "Atualizar preços ✨",
  cartCotacoesAtualizadas: (n) => `${n} preços atualizados ✨`,
  cartCotacoesNaoAchei: (n, lista) => `${n} preços atualizados · não achei: ${lista} 🫣`,
  cartVinculados: (n, rotulo) => `${n} investimentos agora são ${rotulo} 💕`,
  cartRotuloMeta: (nome) => `do sonho "${nome}"`,
  cartPorTipo: "Como tá dividido hoje, por tipo 🐷",
  cartOndeVoceEsta: "Como tá × como você quer 🎯",
  cartTracinhoAlvo: "O tracinho é onde você quer chegar. Quem tá atrás dele é o que comprar da próxima vez 💕",
  cartAbaixoDoAlvo: (n) => `${n} abaixo do que você quer`,
  cartAcimaDoAlvo: (n) => `${n} acima do que você quer`,
  cartNaEstrategia: "Tudo do jeitinho que você quer 💅✨",
  cartDefinaQuanto: "Me conta quanto quer ter em cada tipo e eu comparo com o que você tem hoje 💕",
  cartDefinirEstrategia: "Montar minha estratégia →",
  cartPraFicarNoAlvo: "Pra ficar do jeito que você quer:",
  cartVerRebalanceamento: "Ver o que ajustar →",
  cartDaCarteira: (pct) => `${pct} do que você tem`,
  cartAplicando: "Aplicando…",
  cartDefinirObjetivoDos: (n) => `Dar um sonho pros ${n}…`,
  cartSuasMetas: "Seus sonhos 🌸",
  cartObjetivosGerais: "Os de sempre",
  cartObjMeta: "Sonho",
  cartMetaPrefixo: (nome) => `Sonho: ${nome}`,
  cartEditar: "Mexer ✏️",
  cartEditarAria: (nome) => `Mexer em ${nome}`,
  cartAdicionar: "Adicionar 💕",
  cartSalvarAlteracoes: "Salvar 💕",
  cartImportarCarteira: "Mandar o arquivo da corretora 📄",
  cartPrecoMedioDeclaracao: "Preço médio pela declaração de IR",
  cartEditarAtivo: "Mexer no investimento ✏️",
  cartAporteProntoTitulo: "Prontinho, tá tudo batendo ✨",
  cartAporteEntrouEm: (mes, n) => `O que você guardou em ${mes} entrou em ${n} investimento${s(n)} 🐷`,
  cartMetasAndaram: (lista) => `Seus sonhos andaram junto: ${lista} 🌸`,
  cartVoceAportou: (valor, mes) => `Você guardou ${valor} em ${mes} 🐷`,
  cartCadastreAtivo: "Me conta em qual investimento esse dinheiro entrou, que aí seus investimentos batem com o que você anotou no mês 💕",
  cartDigaQuanto: "Me diz quanto entrou em cada um 💕",
  cartToquePraDizer: "Toca pra me dizer em quais investimentos entrou 💕",
  cartEnquantoNaoDisser: (meta) => `Enquanto você não me diz, seus investimentos ficam com um valor e o mês com outro${meta ? `, e o sonho ${meta} não anda junto` : ""} 🫣`,
  cartMetaDoAtivo: (nome) => `sonho: ${nome}`,
  cartQuantoEntrouEm: (nome) => `Quanto entrou em ${nome}`,
  cartVerOutros: (n) => `Ver os outros ${n} 👀`,
  cartFaltaDizer: (valor) => `Falta me dizer pra onde foram ${valor} 🤔`,
  cartPassouDoAporte: (valor) => `Passou ${valor} do que você guardou 🫣`,
  cartTudoDistribuido: "Tudo dividido! Boaaaa 👏",
  cartAporteAplicado: "Investimentos e sonhos atualizados com o que você guardou no mês 💕",
  cartAplicandoAporte: "Aplicando…",
  cartAtualizarCarteira: "É isso, pode atualizar ✨",
  cartAtivoNaoEstaAqui: "O investimento ainda não tá aqui? Adiciona ele primeiro 💕",
  cartDaMeta: (pct, valor) => `${pct} do sonho (${valor})`,
  cartEditarEstrategia: "mexer na estratégia",
  cartDefinirEstrategiaCurto: "montar estratégia",
  cartSemAtivos: "Nada investido ainda 🌸",
  cartColMeta: "Sonho",
  cartColAlocado: "Você tem",
  cartColAlvo: "Você quer",
  cartColAtingimento: "Quanto já chegou",
  cartSemEstrategiaAntes: "Você ainda não montou sua",
  cartSemEstrategiaLink: "estratégia",
  cartSemEstrategiaDepois: ". Me conta quanto quer em cada tipo pra eu te mostrar aqui a comparação e o que ajustar 💕",
  cartReferenciaMatematica: "É só a conta feita com a sua estratégia, tá? Não é recomendação de comprar ou vender 💕",
  fichasSub: "Como tá sua saúde financeira e o que precisa de um olhar agora 👀",
  fichasInsightsVazio: "Combina seu mês, anota seus sonhos, sua reserva e sua estratégia que eu começo a te dar dicas aqui automaticamente 💕",
  fichasAtencaoTitulo: "O que precisa de um olhar 👀",
  fichasTabInsights: "Dicas ✨",
  fichasVerMais: "Ver mais 👀",
  fichasAcoesSub: "Digita o nome ou o código que eu leio os números pra você 💕",
  fichasFiisSub: "Digita o nome ou o código que eu leio o fundo pra você 💕",
  fichasStocksSub: "Ações lá de fora: digita o nome ou o código que eu leio pra você 💕",
  fichasEtfsSub: "Digita o nome ou o código que eu leio o fundo pra você 💕",
  fichasAnalisesVazio: "Nenhuma análise ainda 🌸 Digita um código ali em cima que eu leio pra você 💕",
  fichasSuasAnalises: "Suas análises 🔍",
  fichasNaCarteira: "você tem ✨",
  fichasNaoLida: "ainda não li",
  fichasFichaCriada: "Análise criada! ✨",
  fichasLendo: "Lendo… 👀",
  fichasAnalisar: "Analisar 🔍",
  fichasNotaDetalhadaSub: "A ficha completa, com nota de 0 a 10 por critério, pra quem quer escrever a própria análise 📝",
  fichasTentarDeNovo: "Tentar de novo 💕",
  fichasLendoNumeros: (ticker) => `Lendo os números de ${ticker}… 👀`,
  fichasMudou: "Mudou desde a última vez 👀",
  fichasEsconderNumeros: "Esconder os números",
  fichasVerNumeros: (n) => `Ver os ${n} números ›`,
  fichasComoLer: "Como ler esses sinais 💕",
  fichasReanalisar: "Ler de novo agora ✨",
  fichasSoVoce: "Só você responde 💕",
  fichasParaVoce: "E pra você, amiga? 💕",
  fichasNaSuaCarteira: (ticker) => `${ticker} nos seus investimentos`,
  fichasEstrategiaPede: (classe, pct) => `${classe}: você quer ${pct}`,
  fichasHoje: (pct) => `hoje tem ${pct}`,
  fichasConcentra: "Comprar mais te deixa ainda mais concentrada do que você quer 🫣",
  fichasPorMil: (mil) => `por mês a cada ${mil}, pelo que ele paga hoje 💰`,
  fichasNaoRecomendacao: "Não é recomendação, tá? É o que você tem lido junto com os números 💕",
  metaBreadcrumbPlanejamento: "Meus planos 🌸",
  metaRitmo: { NOT_STARTED: "Não dá tempo 🫣", ON_TRACK: "No ritmo 💪", BEHIND: "Tá atrasadinha 🫣", ACHIEVED: "Chegou lá!! 🥳" },
  metaRitmoLabel: "Ritmo",
  metaMesesRestantes: "Meses que faltam 🗓️",
  metaFaltaGuardar: "Falta guardar 🐷",
  metaGuardarPorMes: "Guardar por mês 💗",
  metaTrajetoria: "O caminho até o sonho 🌸",
  metaSalvarAlteracoes: "Salvar 💕",
  metaDaquiAMeses: (n) => `Daqui a ${n} meses ✨`,
  grafSemDados: "Nada por aqui ainda 🌸",
  grafAtual: "Como tá",
  grafIdeal: "Como você quer",
  grafEntrou: "Entrou",
  grafSaiu: "Saiu",
  grafSobrouChip: (sobrou, mesAtual, valor) => `${sobrou ? "Sobrou" : "Faltou"} ${mesAtual ? "até agora" : "no mês"}: ${valor} ${sobrou ? "💗" : "🫣"}`,
  grafRenda: "Entrou",
  grafAportes: "Guardou",
  grafPlanejado: "Combinado",
  grafPrevisto: "(previsto)",
  grafReserva: "Reserva 🛟",
  grafMetaLinha: (valor) => `sonho ${valor}`,
  grafPronta: (pct) => `${pct}% pronta ✨`,
  grafFalta: (valor) => `Falta ${valor}`,
  grafCompletaEm: (quando) => `Completa em ${quando} 🎉`,
  grafNenhumGasto: "Nenhum gasto nesse período 🌸",
  grafVereditoAlugar: (diferenca, anos) => `Alugar e investir sai ${diferenca} na frente em ${anos} anos 🔑✨`,
  grafVereditoFinanciar: (diferenca, anos) => `Financiar sai ${diferenca} na frente em ${anos} anos 🏠✨`,
};

/** O menu na voz do Girly, por rota. */
const GIRLY_SECOES: Record<string, string> = {
  "/dashboard": "Visão geral 💖",
  "/mensal": "Meu mês 💸",
  "/planejamento": "Meus planos 🌸",
  "/viagem": "Minha viagem ✈️",
  "/carteira": "Meus investimentos 🐷",
  "/simuladores": "Calculadoras 🧮",
  "/fichas": "Análises 🔍",
  "/configuracoes": "Ajustes ⚙️",
  "/divisao": "Quem paga quanto 💕",
  "/investir": "Vale investir? 💼",
};
const GIRLY_FILHOS: Record<string, string> = {
  "/mensal/gastos": "Pra onde foi",
  "/orcamento": "Combinado",
  "/planejamento/metas": "Sonhos",
  "/planejamento/reserva-emergencia": "Reserva",
  "/planejamento/acumulo": "Liberdade",
  "/carteira": "Meus investimentos",
  "/carteira/por-objetivo": "Por sonho",
  "/perfis": "Seus perfis 🎀",
};

/** A lista da semana, como uma amiga escreveria. Os números vêm do texto original. */
function tarefaGirly(chave: string, texto: string, feita: boolean): string {
  const [n, m] = numeros(texto);
  switch (chave) {
    case "lancamentos": return feita ? `Anotou os gastos da semana (${n ?? 0}) 👏` : "Anotar os gastos da semana 📝";
    case "orcamento-definir": return "Combinar quanto quer gastar por categoria 🎀";
    case "orcamento-estourado": return `Dar uma olhada em ${n ?? 1} categoria${n === "1" ? "" : "s"} que passou do combinado 👀`;
    case "orcamento-ok": return "Combinado do mês sob controle 💅";
    case "reserva-configurar": return "Combinar sua reserva 🛟";
    case "reserva-completar": return `Avançar na sua reserva (${n ?? m ?? 0}%) 🛟`;
    case "reserva-ok": return "Reserva completa!! 🎉";
    case "meta-criar": return "Anotar seu primeiro sonho 🌸";
    case "meta-atrasada": return `Retomar ${n ?? 1} sonho${n === "1" ? "" : "s"} atrasadinho${n === "1" ? "" : "s"} 💪`;
    case "meta-ok": return "Sonhos no ritmo 💖";
    case "aporte": return feita ? "Guardou o do mês. Boaaaa 🐷" : "Separar o dinheirinho do mês pra guardar 🐷";
    case "reuniao-casal": return "15 minutinhos pra olhar as contas do mês juntos 💕";
    default: return texto;
  }
}

export const girly: Voz = {
  // Como se uma amiga tivesse escrito. Simples, sem financês, com emoji — e "boaaaa" quando
  // merece. A Dani: "você precisa guardar, me dá R$ 300 pra eu chegar lá". É esse o tom.
  saudacao: (_p, nome) => `Oii${nome ? `, ${nome}` : ""} 💕`,
  subSaudacao: () => null,
  tituloPainel: null,
  // "Sobrou pra você", e não "guardou": a linha de cima já é o que ela guardou pra investir,
  // e chamar as duas de guardado confundia. Sobrou é a palavra que qualquer pessoa entende.
  rotuloResultado: "Sobrou pra você 💖",
  fraseResultado: (estadoBruto, d) => {
    const estado = estadoParaFrase(estadoBruto, d.resultado);
    const v = inteiro(d.money, d.resultado);
    if (estado === "bom") return `Amiga, sobrou ${v}!! 💖✨ Tá voando, hein.`;
    if (estado === "normal") return `Sobrou ${v} 💗 Pouquinho, mas é seu. Boaaaa.`;
    if (estado === "ruim") return "Esse mês apertou, né? 🫂 Relaxa, no próximo a gente ajusta juntas 💕";
    return null;
  },
  ritmo: { rapido: "Calma no cartão, amiga 💳🫣", limite: "No limite, hein 💅", dentro: "Tá sobrando, arrasou 💅✨" },
  tituloOrcamento: (mes) => `Seu combinado de ${mes} 🎀`,
  fraseOrcamento: (d) => {
    const pronta = semDiaria(d);
    if (pronta) return pronta;
    const dia = `${inteiro(d.money, d.porDia!)} por dia até dia ${d.ultimoDia}`;
    if (d.situacao === "estourou") return `Passou ${inteiro(d.money, d.restante)} do combinado 🫣 Bora ajustar juntas 💕`;
    if (d.situacao === "adiantado") return `Calma no cartão, amiga 💳 Dá ${dia}.`;
    if (d.situacao === "folgado") return `Tá sobrando 💅 ${dia}. Arrasou ✨`;
    return `Sobram ${dia} 💗 Boaaaa.`;
  },
  mesVazio: "Nada anotado ainda 🌸 Toca no + e me conta o primeiro gasto, ou o que entrou 💕",
  metaBatida: (nome) => `ARRASOU!! 🎉🥳 ${nome} concluída, amiga!`,
  rodape: () => "Progresso, não perfeição 💗",
  nav: { metas: "Sonhos", flowTabs: ["Visão mensal", "Só gastos", "Combinado"] },
  titulos: {
    ...TITULOS_PADRAO,
    ...GIRLY_SIM,
    ...GIRLY_FORM,
    ...GIRLY_IMP,
    ...GIRLY_UI,
    ...GIRLY_CFG,
    ...GIRLY_CART,
    comparacao: (tipo, valor, mes) =>
      tipo === "sem" ? `Nadinha em ${mes} 🌸` : tipo === "igual" ? `Igualzinho a ${mes} 💕` : tipo === "mais" ? `${valor} a mais que ${mes} 🫣` : `${valor} a menos que ${mes}! Boaaaa 👏`,
    simuladores: "Bora simular? 🧮✨",
    simuladoresSub: "Calculadoras pra você decidir com calma, amiga 💕",
    simulador: simuladoresDoTema({
      "/simuladores/financiar-vs-alugar": { subtitle: "Financiar o apê ou alugar e investir a diferença? Eu faço a conta 🏠" },
      "/simuladores/amortizar-vs-investir": { subtitle: "Sobrou dinheiro: quita antes ou investe? 🤔" },
      "/simuladores/consorcio": { subtitle: "Consórcio ou financiamento? O custo de verdade de cada um 💸" },
      "/simuladores/marcacao-mercado": { subtitle: "Vender o título antes da hora dá lucro ou prejuízo? 📈" },
      "/simuladores/carro": { subtitle: "Assinar ou comprar o carro? Qual sai mais em conta 🚗" },
      "/simuladores/vale-a-pena": { subtitle: "Quantas horas de trabalho custa esse mimo? 👀" },
    }),
    registrar: "Anotar 💕",
    registrarNovo: "Anota aí 📝",
    registrarFalar: "Me conta por voz 🎤",
    registrarImportar: "Manda o extrato 📄",
    lancamentoSalvo: "Anotado, amiga! 💕",
    visaoGeral: "Visão geral 💖",
    visaoGeralSub: "Seu {ano} inteiro, amiga 💕",
    patrimonio: "Tudo que você tem ✨",
    rendaNoAno: "Entrou no ano 💸",
    gastosNoAno: "Saiu no ano 🛍️",
    sobrouNoAno: "Sobrou no ano 💗",
    sobrouNoAnoDica: (cem, manteve, pct) =>
      pct >= 20
        ? `De cada ${cem} que entraram, você segurou ${manteve}!! Orgulho de você, amiga 💅✨`
        : pct > 0
          ? `De cada ${cem} que entraram, você segurou ${manteve}. Bora subir isso juntas 💪💕`
          : `Esse ano ainda não sobrou 🫂 Tá tudo bem, a gente ajusta juntas.`,
    statusModulos: "Como estão seus planos 🌸",
    modReserva: "Sua reserva 🛟",
    modMetas: "Seus sonhos 🎯",
    modAposentadoria: "Sua liberdade ✨",
    modDividendos: "Dinheirinho que caiu 💰",
    economiaNoMes: "Sobrou este mês 💗",
    economiaAbaixo: "Abaixo do combinado. Arrasou, amiga 👏✨",
    economiaAcima: "Passou do combinado 🫣 No próximo a gente ajusta 💕",
    categoriaEstourou: "Onde você mais gastou 🫣",
    categoriaEstourouDica: (pct) => `${pct} além do combinado, amiga 👀`,
    nenhumaEstourou: "Nenhuma estourou!! Parabéns, amiga 🎉",
    economizouMaisEm: "Onde você mais economizou 👏",
    economizouMaisEmDica: (pct) => `${pct} abaixo do combinado. Boaaaa 🥳`,
    semLancamento: "Faltou anotar 📝",
    soGastos: "Pra onde foi? 💸",
    soGastosSub: "Cada real tem um destino, amiga 💕",
    orcamento: "Seu combinado 🎀",
    orcamentoSub: "Quanto você combinou comigo, e quanto já foi 👀",
    orcamentoPorCategoria: "Por categoria 🎀",
    paraOndeFoi: "Pra onde foi seu dinheiro 💸",
    oQueMudou: "O que mudou 👀",
    ritmoDoMes: "Ritmo do mês 💅",
    anoMesAMes: "Seu ano, mês a mês 🌸",
    caiuNaConta: "Caiu na conta!! 💰",
    caiuNaContaSub: "Olha, amiga, o dinheirinho que seus investimentos te pagaram esses dias 🥰 Um toque e ele entra como renda ✨",
    planejamento: "Combinado",
    poupanca: "Guardou",
    aportou: "Guardou pra investir 🐷",
    metas: "Seus sonhos 🎯",
    metasSub: "Cada meta é um sonho com data, amiga 💕 Eu te conto quanto guardar por mês pra chegar lá ✨",
    metasVazio: "Nenhum sonho anotado ainda 🌸 Cria o primeiro e eu te digo quanto guardar por mês 💕",
    reserva: "Sua reserva 🛟",
    reservaSub: "O dinheiro que fica separado pros imprevistos, amiga 💕 Se a vida apertar, é ele que te segura 🫂",
    reservaMeta: "Quanto você quer ter guardado 🎯",
    reservaAtual: "Quanto já tem 💗",
    reservaTempo: "Falta quanto tempo ⏳",
    reservaRendimento: "Quanto rende por mês ✨",
    reservaProjecao: "Até chegar lá 🌸",
    aposentadoria: "Sua liberdade ✨",
    aposentadoriaSub: "Do guardar de hoje até viver do que o dinheiro rende — o caminho inteiro, amiga 💕",
    aposentadoriaWizardSub: "Vamos montar seu plano juntas, em poucos passos 💗",
    metaStatus: { ahead: "Adiantada, arrasou 🎉", onTrack: "No ritmo 💪", behind: "Tá atrasadinha 🫣", achieved: "Chegou lá!! 🥳" },
    metaGuardar: (v) => `Me dá ${v} esse mês e a gente chega lá 💪✨`,
    metaMeses: (n) => (n === 1 ? "falta 1 mês 🗓️" : `faltam ${n} meses 🗓️`),
    metaAporteFeito: (mes) => `Guardou em ${mes}. Boaaaa 🎉`,
    metaAporteToast: (mes) => `Anotei o que você guardou em ${mes} 💕`,
    metaMarcar: (mes) => `Guardei em ${mes} ✓`,
    metaOutroValor: "foi outro valor",
    splitTitulo: (mes) => `Pra onde vai o que você guarda em ${mes} 💸`,
    splitSub: (v) => `${v} por mês, do seu combinado. Primeiro a reserva, depois os sonhos 🌸`,
    splitVazioTitulo: "Pra onde vai o que você guarda? 🤔",
    splitVazioSub: "Me conta no combinado quanto quer guardar por mês, que eu divido entre reserva e sonhos 💕",
    formCusto: "Quanto custa um mês da sua vida? 💸",
    formCustoHint: "É isso que a reserva precisa cobrir enquanto a renda não volta, amiga 🫂",
    formMeses: "Quantos meses quer ter guardados? 🗓️",
    formMesesHint: "Salário fixo costuma pedir 6. Autônoma ou renda que varia, 12 💕",
    formJaTenho: "Já tenho guardado 💗",
    formGuardoPorMes: "Guardo por mês 🐷",
    formRende: "Quanto rende por ano ✨",
    formRendeHint: "Reserva fica em aplicação que dá pra sacar no mesmo dia, então rende perto do CDI 📈",
    apSeNadaMudar: (idade) => `Se nada mudar, aos ${idade} anos você vai ter 💫`,
    apHoje: "em dinheiro de hoje",
    apDaPe: "Dá pé!! 🙌",
    apNaoDaPe: "Ainda não dá pé 🫣",
    apVereditoIntro: "É o que esse dinheiro te paga todo mês sem você gastar ele ✨ Você quer",
    apSobram: "— sobram",
    apFaltam: "— faltam",
    apTodoMes: "todo mês 💕",
    apDeOndeVem: "De onde vem esse dinheiro 💰",
    apDeOndeVemHint: "Em dinheiro de hoje, a mesma moeda do número lá em cima.",
    apBolso: (anos) => `Você coloca do seu bolso em ${anos} anos`,
    apJuros: "Os juros colocam pra você 🪄",
    apJurosNota: (um, mais) => `Pra cada ${um} seu, os juros botam mais ${mais}. Mágica? Quase 🪄✨`,
    apPremissas: "Ver as contas por trás 🔍",
    apEditar: "Mexer nos meus dados ✏️",
    apProjecao: "Como seu dinheiro cresce 📈",
    apProjecaoSub: (idade, vida) => `Guardando até os ${idade}${vida ? `, vivendo de renda até os ${vida} ✨` : " ✨"}`,
    apAcumulo: "Guardando",
    apAcumuloDesc: "você ainda tá guardando, o bolo só cresce 🐷",
    apUsufruto: "Vivendo de renda",
    apUsufrutoDesc: "você para de guardar e começa a viver do que rende ✨",
    apAnoAAno: "Ver ano a ano 📅",
    apNominal: "Se o dinheiro não perdesse valor",
    apReal: "Em dinheiro de hoje",
    planTabs: ["Sonhos", "Reserva", "Liberdade"],
    carteiraTabs: ["Meus investimentos", "Por sonho", "Estratégia"],
    visaoGeralLink: "Ver meu mês 💸",
    semanaTitulo: "Sua lista da semana 📝",
    tarefa: tarefaGirly,
    navSecao: (b, texto) => GIRLY_SECOES[b] ?? texto,
    navFilho: (h, texto) => GIRLY_FILHOS[h] ?? texto,
    navMais: "Mais 💕",
    navPerfis: "Seus perfis 🎀",
    navInstalar: "Colocar na tela de início 📲",
    navWhatsapp: "Falar comigo no WhatsApp 💬",
    navSair: "Sair 👋",
    carteira: "Seus investimentos 🐷",
    carteiraSub: "Tudo que você tem investido, e pra que serve cada um 💕",
    carteiraLink: "Ver por sonho →",
    carteiraVazio: "Nada investido ainda 🌸 Adiciona o primeiro e eu acompanho pra você 💕",
    porObjetivo: "Por sonho 🎯",
    porObjetivoSub: "Quanto você tem em cada sonho, e como tá dividido 💕",
    porObjetivoEditar: "← mexer nos investimentos",
    posicaoPorObjetivo: "Quanto tem em cada sonho 💗",
    objReserva: "Sua reserva 🛟",
    objLiberdade: "Sua liberdade ✨",
    objSem: "Ainda sem sonho 🤔",
    objSemMetaHint: "Você ainda não combinou sua reserva 🛟",
    secaoMetas: "Seus sonhos 🎯",
    estrategiaVsAlvo: "Como tá × como você quer 🎯",
    alocacaoPorClasse: "Como tá dividido × o ideal 💅",
    estrategia: "Sua estratégia 💅",
    estrategiaSub: "Quanto você quer em cada tipo de investimento, somando 100% 💕",
    contribTitulo: (mes) => `Quanto você vai guardar em ${mes}? 🐷`,
    contribSub: "Eu te digo onde colocar pra sua carteira ficar do jeito que você quer 💕",
    contribLabel: "Vou guardar",
    contribSemAtivo: " · ainda não tem nada desse tipo",
    contribVazio: "Você ainda não tem investimentos, então a divisão segue só a estratégia 🌸",
    contribSemEstrategiaTitulo: "Onde colocar o que você vai guardar esse mês? 🤔",
    contribSemEstrategiaSub: "Me conta sua estratégia e eu te digo quanto vai pra cada tipo de investimento. São três perguntinhas 💕",
    contribDefinir: "Montar minha estratégia →",
    divTitulo: (total) => `Dinheirinho que vem aí 💰 · ${total}`,
    divDatas: (dataCom, pagamento) => `Precisa ter até ${dataCom} · Cai em ${pagamento}`,
    divLiquido: "já sem imposto",
    divBruto: "sem descontar imposto",
    divNota: "É uma estimativa com o que você tem hoje — se comprar ou vender antes da data, o valor muda. JSCP já vem sem os 15% de imposto; dividendos e rendimento de FII costumam ser isentos ✨ Fonte: investidor10.",
    compHint: "O tracinho é onde você quer chegar. Quem tá atrás dele é o que comprar da próxima vez 💕",
    compVoceTem: "Você tem",
    compDeveriaTer: "Você quer",
    compAportar: "Colocar mais",
    compReduzir: "Colocar menos",
    objNenhumTitulo: "Seus investimentos ainda não têm sonho 🤔",
    objNenhumTexto: (valor) => `Seus ${valor} estão todos "sem sonho". Me conta o que cada um é — reserva, liberdade ou um sonho — que aí eu te digo quanto falta, em vez de só somar 💕`,
    objNenhumLink: "Dar um sonho pra cada um →",

    // Casal: quem paga quanto, na proporção da renda de cada um.
    casTitulo: "Quem paga quanto? 💕",
    casSub: "Quando a renda é diferente, o mais justo é cada um entrar na mesma proporção que representa na renda do casal — não 50/50, amiga 💕",
    casRendaA: "Quanto um dos dois recebe por mês 💸",
    casRendaAHint: "A renda de uma pessoa do casal, já líquida.",
    casRendaB: "Quanto o outro recebe por mês 💸",
    casRendaBHint: "A renda da outra pessoa, já líquida.",
    casDespesas: "Contas da casa no mês 🏠",
    casDespesasHint: "Aluguel, mercado, luz: o que é dos dois, não o gastinho individual de cada um.",
    casDespesasSugestao: (valor) => `Vocês gastaram ${valor} este mês 👀`,
    casPctLabel: "Já combinaram outro percentual? (se quiser)",
    casPctSufixo: "% pro outro",
    casPctVoltar: (pct) => `Voltar pra sugestão da renda (${pct}%) ✨`,
    casPctDica: "Em branco, eu sugiro pela renda de cada um 💕",
    casSemRenda: "Preenche a renda dos dois pra eu calcular quanto cada um contribui 💕",
    casHeaderAuto: "Divisão proporcional à renda",
    casHeaderManual: "O percentual que vocês combinaram",
    casTextoAuto: "Quem ganha mais, contribui mais — na mesma proporção da renda do casal. Não é 50/50 💕",
    casTextoManual: "Vocês já combinaram esse número entre vocês. Eu sigo o combinado, não a conta da renda.",
    casContribA: "Um dos dois entra com",
    casContribB: "O outro entra com",
    casContribPct: (pct) => `${pct}% das contas comuns`,
    casSobraLivre: (valor) => `Sobra livre: ${valor} 💗`,
    casComparandoTitulo: "Comparando com 50/50",
    casComparandoIgual: (valor) => `Se dividissem igual, cada um pagaria ${valor}.`,
    casComparandoMenos: (valor) => `Do jeito que tá, quem ganha menos paga ${valor} a menos por mês 💗`,
    casComparandoMais: (valor) => `Do jeito que tá, quem ganha menos paga ${valor} a mais por mês.`,
    casComparandoParecido: "As rendas de vocês são parecidas, então dá quase no mesmo que 50/50 💕",
    casComparandoManualNota: (pct) => `Pela renda, seria ${pct}% pro outro — só pra vocês compararem.`,
    casRendaConjunta: (valor) => `Renda dos dois somada: ${valor}. Não fica salvo, é só pra decidir esse mês 💕`,

    // Empresa: vale a pena investir? Sem financês, só o que interessa pra decidir.
    invTitulo: "Vale a pena investir na sua empresa? 💼✨",
    invSub: "Uma máquina, uma reforma, um espacinho novo, uma contratação: em quanto tempo isso se paga, e se rende mais do que deixar o dinheiro guardado.",
    invCusto: "Quanto custa esse investimento? 💸",
    invCustoHint: "Máquina, reforma, espaço novo, contratação: o valor à vista.",
    invTipoLabel: "O que ele traz por mês?",
    invTipoVenda: "Mais vendas",
    invTipoEconomia: "Economia de custo",
    invReceitaLabelVenda: "Receita a mais por mês",
    invReceitaLabelEconomia: "Economia por mês",
    invReceitaHintVenda: "Quanto você espera vender a mais por causa dele. Seja realista: a média, não o melhor mês.",
    invReceitaHintEconomia: "Quanto deixa de gastar por mês (energia, terceiro, retrabalho).",
    invMargemLabel: "Quanto sobra de cada venda, depois dos custos dela",
    invMargemHint: "A margem que sobra pela sua DRE. Vender mais só vale o que sobra depois de mercadoria, taxa e frete.",
    invCustoMensal: "Custo fixo novo por mês",
    invCustoMensalHint: "O que o investimento passa a custar todo mês: manutenção, salário, aluguel maior, sistema novo. Zero se não tiver.",
    invPrazoLabel: "Prazo pra avaliar",
    invTaxaLabel: "Quanto rende deixando guardado, ao ano",
    invVeredictoEyebrow: "Veredito",
    invVeredictoValeTitulo: "Vale a pena 🎉",
    invVeredictoValeTexto: (meses) => `Se paga em ${meses} ${meses === 1 ? "mês" : "meses"} e rende mais do que deixar o dinheiro parado. Bora! 💪`,
    invVeredictoEmpataTitulo: "Empata com deixar guardado",
    invVeredictoEmpataTexto: (meses) => `Se paga em ${meses} meses, mas o ganho fica parecido com o de deixar guardado. Decide pelo que isso traz pra sua empresa, não só pelo número 💕`,
    invVeredictoNaoValeTitulo: "Não vale, por enquanto",
    invVeredictoNaoValeTextoForaDoPrazo: (meses, horizonte) => `Só se paga em ${meses} meses, além dos ${horizonte} que você deu de prazo.`,
    invVeredictoNaoValeTextoRendeMais: "Deixar o dinheiro guardado rende mais do que esse investimento devolve no prazo.",
    invVeredictoNuncaSePagaTitulo: "Não se paga 🫣",
    invVeredictoNuncaSePagaTexto: "O custo novo por mês come toda a margem que a receita nova traz. Assim esse investimento nunca se paga.",
    invGanhoMes: "Ganho por mês",
    invGanhoMesNota: "já tirando o custo novo",
    invSePagaEm: "Se paga em",
    invSePagaNunca: "nunca",
    invSePagaNota: "tempo pra se pagar",
    invResultadoEm: (horizonte) => `Resultado em ${horizonte} meses`,
    invResultadoNota: (pct) => `${pct}% sobre o que você investiu`,
    invNaAplicacao: "Deixando guardado, renderia",
    invNaAplicacaoNota: (taxa) => `${taxa}% ao ano, sem imposto`,
    invGraficoTitulo: "Na empresa × guardado, mês a mês",
    invGraficoDescSupera: (mes) => `A empresa passa a render mais no mês ${mes} ✨`,
    invGraficoDescNaoSupera: "No prazo que você deu, deixar guardado rende mais.",
    invGraficoLegendaEmpresa: "Na empresa",
    invGraficoLegendaAplicacao: "Guardado",
    invReceitaNecessariaAntes: (horizonte) => `Pra se pagar em ${horizonte} meses, esse investimento precisa trazer pelo menos `,
    invReceitaNecessariaDepois: " de vendas a mais por mês.",
    invReceitaAbaixo: " Você estimou menos que isso.",
    invReceitaAcima: " Você estimou acima disso 💪",
    invRodapeNota: "Conta simples, sem inflação nem imposto sobre o que fica guardado, só pra te dar uma ideia. Se a decisão for apertada, fala com seu contador antes de assinar qualquer coisa 💕",

    // E-mail: o resumo do mês e o convite pra voltar, do jeito que uma amiga escreveria.
    emailSaudacao: (nome) => (nome ? `Oii, ${nome}! 💕` : "Oii! 💕"),
    emailRecapAssunto: (mes) => `Seu resumo de ${mes} chegou 🎀`,
    emailRecapIntro: (mes) => `${mes} terminou! Vem ver como foi 💕`,
    emailRecapSobrou: "Sobrou pra você 💖",
    emailRecapFaltou: "Faltou no mês 🫣",
    emailRecapPrimeiroMes: "Esse foi seu primeiro mês anotando comigo — no próximo já dá pra comparar 💕",
    emailRecapGastosIguais: "Seus gastos ficaram bem parecidos com o mês passado.",
    emailRecapGastosMenos: (valor) => `Você gastou ${valor} que no mês passado. Arrasou 👏`,
    emailRecapGastosMais: (valor) => `Seus gastos ficaram ${valor} do mês passado. Bora ficar de olho 👀`,
    emailMaiorGasto: "Onde mais saiu dinheiro",
    emailRecapBotao: "Ver meu mês completo 💕",
    emailRecapRodape: "Você recebe esse resumo uma vez por mês 🎀",
    emailConviteAssunto: (mes) => `${mes} começou, bora organizar? 🌸`,
    emailConviteIntro1: (mes) => `Começou ${mes}! Mês novo é a melhor hora pra começar, porque você me conta ele inteirinho, do começo ao fim 💕`,
    emailConviteIntro2:
      "Não precisa organizar tudo de uma vez, amiga. <strong>Me conta um gasto de hoje</strong>, só um, que eu já começo a montar o resto: pra onde seu dinheiro tá indo, quanto sobra, quanto dá pra guardar 🐷",
    emailConviteBotao: "Anotar meu primeiro gasto 📝",
  },
};
