import { TITULOS_PADRAO, simuladoresDoTema, tarefasDoTema, inteiro, semDiaria, estadoParaFrase, type Voz } from "../voice-base";

/** O menu na voz do Manifestação, por rota. */
const SECOES: Record<string, string> = {
  "/planejamento": "Sonhos",
  "/viagem": "Próxima viagem",
  "/carteira": "O que você construiu",
  "/divisao": "Nosso caminho ✨",
  "/investir": "Vale investir? ✨",
};
const FILHOS: Record<string, string> = {
  "/planejamento/metas": "Sonhos",
  "/planejamento/acumulo": "Liberdade",
  "/planejamento/reserva-emergencia": "Segurança",
  "/carteira": "O que você tem",
  "/carteira/por-objetivo": "Por sonho",
};

const s = (n: number) => (n === 1 ? "" : "s");

export const manifestacao: Voz = {
  saudacao: (_p, nome) => `Oi${nome ? `, ${nome}` : ""} ✨`,
  subSaudacao: () => null,
  tituloPainel: null,
  rotuloResultado: "Sobrou",
  fraseResultado: (estadoBruto, d) => {
    const estado = estadoParaFrase(estadoBruto, d.resultado);
    const v = inteiro(d.money, d.resultado);
    if (estado === "bom") return `${v} financiando a vida que você quer ✨`;
    if (estado === "normal") return `${v} a mais construindo seu futuro.`;
    if (estado === "ruim") return "Esse mês não sobrou. Seu sonho continua lá, esperando.";
    return null;
  },
  ritmo: { rapido: "Seu sonho pede calma", limite: "No limite", dentro: "No caminho ✨" },
  tituloOrcamento: (mes) => `Seu orçamento de ${mes}`,
  fraseOrcamento: (d) => {
    const pronta = semDiaria(d);
    if (pronta) return pronta;
    const porDia = inteiro(d.money, d.porDia!);
    if (d.situacao === "estourou") return `${inteiro(d.money, d.restante)} além do plano. Amanhã é um novo começo.`;
    if (d.situacao === "adiantado") return `${porDia} por dia. Sua vida dos sonhos também precisa de orçamento.`;
    if (d.situacao === "folgado") return `${porDia} por dia. Sobra pra sonhar um pouco mais alto.`;
    return `${porDia} por dia até dia ${d.ultimoDia}.`;
  },
  mesVazio: "Todo plano começa com o primeiro registro.",
  metaBatida: (nome) => `${nome}: você chegou lá ✨`,
  rodape: () => "Você está financiando a vida que quer.",
  nav: { metas: "Sonhos", flowTabs: ["Visão mensal", "Só gastos", "Orçamento"] },
  titulos: {
    ...TITULOS_PADRAO,
    comparacao: (tipo, valor, mes) =>
      tipo === "sem" ? `Nada em ${mes}` : tipo === "igual" ? `Igual a ${mes}` : tipo === "mais" ? `${valor} a mais que ${mes}` : `${valor} a menos que ${mes} ✨`,
    simuladores: "Simule a vida que você quer ✨",
    simuladoresSub: "Calculadoras pra cada decisão grande no caminho.",
    simulador: simuladoresDoTema({
      "/simuladores/financiar-vs-alugar": { subtitle: "A casa dos sonhos: financiar ou alugar e investir a diferença?" },
      "/simuladores/amortizar-vs-investir": { subtitle: "Sobrou dinheiro: quitar a dívida antes ou investir no seu futuro?" },
      "/simuladores/consorcio": { subtitle: "O bem que você quer: consórcio ou financiamento, o custo real de cada caminho." },
      "/simuladores/marcacao-mercado": { subtitle: "Vender o título antes da hora daria lucro ou prejuízo?" },
      "/simuladores/carro": { subtitle: "O carro que você quer: assinar ou comprar, qual pesa menos no plano." },
      "/simuladores/vale-a-pena": { subtitle: "Quantas horas da sua vida custa — e o que renderia investido no seu futuro." },
    }),
    registrar: "Registrar ✨",
    registrarNovo: "Novo registro",
    registrarFalar: "Falar o registro",
    lancamentoSalvo: "Registrado. Um passo a mais ✨",
    campeaoTitulo: "Pra onde mais foi este mês",
    campeaoPergunta: (_k, label) => `Quanto foi pra ${label.toLowerCase()}?`,
    // Aspiracional: futuro, sonho, a vida que ela quer. Um ✨ aqui e ali, nunca mais que isso.
    visaoGeral: "Sua vida em números ✨",
    visaoGeralSub: "{ano} até aqui.",
    patrimonio: "O que você já construiu",
    rendaNoAno: "Entrou",
    gastosNoAno: "Saiu",
    sobrouNoAno: "Ficou pro seu futuro",
    sobrouNoAnoDica: (cem, manteve, pct) =>
      pct >= 20 ? `De cada ${cem}, ${manteve} foram pro seu futuro ✨`
      : pct > 0 ? `De cada ${cem}, ${manteve} foram pro seu futuro. Dá pra sonhar mais alto.`
      : "Este ano ainda não sobrou. Seu sonho continua lá.",
    statusModulos: "Seus sonhos",
    modReserva: "Sua segurança",
    modMetas: "Sonhos",
    modAposentadoria: "Sua liberdade",
    modDividendos: "Renda que chega sozinha",
    economiaNoMes: "Guardado pro futuro",
    economiaAbaixo: "Abaixo do planejado ✨",
    economiaAcima: "Acima do planejado. Amanhã é um novo começo.",
    categoriaEstourou: "Onde o plano escorregou",
    categoriaEstourouDica: (pct) => `${pct} além do combinado`,
    nenhumaEstourou: "Nada escorregou. Você está no caminho ✨",
    economizouMaisEm: "Onde você ficou mais perto",
    economizouMaisEmDica: (pct) => `${pct} abaixo do plano`,
    semLancamento: "Ainda sem registro",
    soGastos: "Pra onde foi",
    soGastosSub: "Cada real conta uma escolha.",
    orcamento: "Seu plano ✨",
    orcamentoSub: "O que você combinou com o seu futuro.",
    orcamentoPorCategoria: "Por categoria",
    paraOndeFoi: "Pra onde foi seu dinheiro",
    oQueMudou: "O que mudou no caminho",
    ritmoDoMes: "Seu ritmo este mês",
    anoMesAMes: "Seu ano, mês a mês",
    caiuNaConta: "Renda que chegou sozinha ✨",
    caiuNaContaSub: "Seus investimentos te pagaram. Um toque e vira renda.",
    planejamento: "Plano",
    poupanca: "Pro futuro",
    aportou: "Investiu",
    metas: "Seus sonhos ✨",
    metasSub: "Cada sonho com data e um número por mês. É assim que ele vira real.",
    metasVazio: "Todo plano começa com o primeiro sonho. Qual é o seu?",
    reserva: "Sua segurança",
    reservaSub: "O que te deixa sonhar sem medo: se a vida apertar, isso te segura.",
    reservaMeta: "Segurança completa",
    reservaAtual: "Já guardado",
    reservaTempo: "Tempo até chegar lá",
    reservaRendimento: "Rende por mês",
    reservaProjecao: "Até chegar lá ✨",
    aposentadoria: "Sua liberdade ✨",
    aposentadoriaSub: "Do guardar de hoje até viver da renda que você construiu.",
    aposentadoriaWizardSub: "Vamos desenhar sua liberdade em poucos passos.",
    metaStatus: { ahead: "Adiantada ✨", onTrack: "No ritmo", behind: "Atrasada", achieved: "Realizado ✨" },
    metaGuardar: (v) => `${v} este mês, e você fica mais perto`,
    metaMeses: (n) => `${n} ${n === 1 ? "mês" : "meses"} até lá`,
    metaAporteFeito: (mes) => `${mes} guardado. Mais perto ✨`,
    metaAporteToast: (mes) => `Você ficou mais perto em ${mes} ✨`,
    metaMarcar: (mes) => `Guardei em ${mes}`,
    splitTitulo: (mes) => `O que você guarda em ${mes}, e pra onde vai`,
    splitSub: (v) => `${v} por mês, do seu plano. Segurança primeiro, depois os sonhos.`,
    splitVazioTitulo: "Pra onde vai o que você guarda?",
    splitVazioSub: "Diga no seu plano quanto quer guardar por mês, e o app divide entre a sua segurança e os seus sonhos.",
    formCustoHint: "É isso que a sua segurança precisa cobrir enquanto a renda não volta.",
    formRende: "Quanto a sua segurança rende por ano",
    formRendeHint: "A segurança fica em aplicação de liquidez diária, então costuma render perto do CDI.",
    apSeNadaMudar: (idade) => `Se nada mudar, aos ${idade} anos você terá`,
    apDaPe: "Sua liberdade fecha ✨",
    apNaoDaPe: "Ainda não fecha",
    apVereditoIntro: "É a renda que esse patrimônio te paga sem consumir o principal. A vida que você quer custa",
    apDeOndeVem: "De onde vem a sua liberdade",
    apBolso: (anos) => `O que você põe do bolso em ${anos} anos`,
    apJuros: "O que o tempo põe",
    apJurosNota: (um, mais) => `Pra cada ${um} seu, o tempo coloca ${mais}. Comece cedo.`,
    apProjecao: "A vida que você está construindo",
    apProjecaoSub: (idade, vida) => `Construindo até os ${idade} anos${vida ? `, vivendo da renda até os ${vida} anos` : ""}.`,
    apAcumulo: "Construindo",
    apAcumuloDesc: "você ainda guarda, e o patrimônio só cresce.",
    apUsufruto: "Vivendo a liberdade",
    apUsufrutoDesc: "os aportes param e você passa a viver do que construiu.",
    planTabs: ["Sonhos", "Segurança", "Liberdade"],
    carteiraTabs: ["O que você tem", "Por sonho", "Estratégia"],
    visaoGeralLink: "Ver o mês →",
    semanaTitulo: "Seus passos desta semana",
    tarefa: tarefasDoTema({
      lancamentos: (n, feita) => (feita ? `Gastos da semana registrados (${n ?? 0}) ✨` : "Registrar os gastos da semana"),
      "orcamento-definir": () => "Desenhar o plano do mês",
      "orcamento-estourado": (n, _f, pl) => `Rever ${n ?? 1} categoria${pl ? "s" : ""} acima do plano`,
      "orcamento-ok": () => "Plano do mês em dia ✨",
      "reserva-configurar": () => "Definir a sua segurança",
      "reserva-completar": (n) => `Avançar na sua segurança (${n ?? 0}%)`,
      "reserva-ok": () => "Segurança completa ✨",
      "meta-criar": () => "Escrever seu primeiro sonho",
      "meta-atrasada": (n, _f, pl) => `Retomar ${n ?? 1} sonho${pl ? "s" : ""}`,
      "meta-ok": () => "Sonhos no ritmo ✨",
      aporte: (_n, feita) => (feita ? "Guardou pro futuro este mês ✨" : "Separar o que vai pro futuro este mês"),
      "reuniao-casal": () => "15 min pra sonhar junto: olhar os gastos do mês a dois ✨",
    }),
    navSecao: (b, t) => SECOES[b] ?? t,
    navFilho: (h, t) => FILHOS[h] ?? t,
    carteira: "O que você construiu ✨",
    carteiraSub: "Cada investimento ligado a um sonho.",
    carteiraLink: "Ver por sonho →",
    carteiraVazio: "Nada construído por aqui ainda. Adicione o primeiro investimento e ele começa a aparecer.",
    porObjetivo: "Carteira por sonho",
    porObjetivoSub: "Quanto você já tem em cada sonho, e como está dividido em relação ao ideal.",
    porObjetivoEditar: "← editar investimentos",
    posicaoPorObjetivo: "Quanto tem em cada sonho",
    objReserva: "Sua segurança",
    objLiberdade: "Sua liberdade",
    objSem: "Ainda sem sonho",
    objSemMetaHint: "Sua segurança ainda não tem um valor definido",
    secaoMetas: "Seus sonhos",
    estrategiaVsAlvo: "Onde você está × onde quer chegar",
    alocacaoPorClasse: "Como está × o ideal, por classe",
    estrategia: "Sua estratégia",
    estrategiaSub: "Quanto você quer ter em cada classe (somando 100%), independente do ideal de cada ativo.",
    contribTitulo: (mes) => `Quanto vai pro futuro em ${mes}?`,
    contribSub: "Onde colocar pra sua carteira ficar do jeito que você desenhou.",
    contribLabel: "Vou guardar",
    contribVazio: "Você ainda não tem investimentos por aqui, então a divisão segue só a estratégia.",
    contribSemEstrategiaTitulo: "Onde colocar o que vai pro futuro este mês?",
    contribSemEstrategiaSub: "Com uma estratégia, o app diz quanto vai pra cada tipo de investimento pra sua carteira chegar onde você quer. São três perguntas.",
    contribDefinir: "Desenhar minha estratégia →",
    divTitulo: (total) => `Renda que chega sozinha · ${total}`,
    compHint: "O tracinho é onde você quer chegar. Quem está atrás dele é o que comprar no próximo aporte.",
    compDeveriaTer: "Quer ter",
    objNenhumTitulo: "Seus investimentos ainda não têm um sonho.",
    objNenhumTexto: (valor) =>
      `Seus ${valor} estão todos "sem sonho". Dizer o que cada um é — segurança, liberdade ou um sonho — é o que deixa esta tela responder "quanto falta" em vez de só somar.`,
    objNenhumLink: "Dar um sonho a cada investimento →",

    // Simuladores: a matemática fica; muda só o que fala com ela.
    simSalvaToast: "Simulação salva. Ela fica te esperando na lista de simuladores.",
    simSalvarNomePlaceholder: "Dê um nome a esse plano (opcional)",
    simFinValorImovelHint: "O preço de venda do imóvel dos seus sonhos.",
    simValePasso1Sub: "Digite o preço do que você está pensando em comprar.",
    simValeCompraUnicaDesc: "Algo pontual: uma roupa, um eletrônico, uma viagem.",
    simValeHabitoDesc: "Se repete todo mês: assinatura, delivery, café.",
    simValeHorizontePergunta: "Se você não comprar e investir no seu futuro, por quanto tempo?",
    simValeBarraInvestirUnico: "Investir no seu futuro",
    simValeBarraGastar: "Comprar agora",
    simValeVeredito: (valor) => `Investindo, você teria ${valor} a mais lá na frente.`,
    simValeEscolhaComprar: "Se faz parte da vida que você quer, ótimo — só garanta que cabe no plano do mês.",
    simValeEscolhaNao: "Boa escolha. Isso te deixa mais perto dos seus sonhos ✨",
    simValeEscolhaDuvida: "Sem pressa. Dá pra voltar aqui quando tiver mais clareza — a dúvida já é um sinal de que vale pensar mais um pouco.",

    // Formulários: meta vira sonho, reserva vira segurança, aposentadoria vira liberdade.
    formMetaNova: "Novo sonho",
    formMetaEditar: "Editar sonho",
    formMetaAdicionar: "Adicionar sonho",
    formMetaCriada: "Sonho registrado. Agora ele tem data ✨",
    formMetaAtualizada: "Sonho atualizado.",
    formMetaNome: "Nome do sonho",
    formMetaValorAlvo: "Quanto custa o sonho",
    formMetaMesAno: "Quando quer realizar",
    formAtivoObjetivos: { OUTRO: "Outro", RESERVA_EMERGENCIA: "Sua segurança", LIBERDADE_FINANCEIRA: "Sua liberdade", META: "Um sonho" },
    formAtivoMetaVinculada: "Sonho vinculado",
    formOrcSalvo: "Plano salvo pro ano inteiro ✨",
    formOrcTitulo: "Vamos desenhar o seu plano",
    formOrcSub: "Três perguntas. O app já sabe parte das respostas pelos seus registros.",
    formOrcQuantoGuardar: "Quanto vai pro seu futuro?",
    formOrcGuardarPorMes: "Pro futuro, por mês",
    formOrcCursoNota: (pct, liberdade) =>
      `No curso, a conta é ${pct}%: ${liberdade}% pra sua liberdade e 8% pros sonhos. Quem está começando costuma conseguir 10% — se ficar apertado, dá pra mudar depois. Nada aqui é promessa.`,
    formOrcSobraTitulo: "Sobra pra viver",
    formOrcSobraSub: (valor) => `por mês, depois de guardar ${valor} pro futuro`,
    formOrcProntoPlano: (ano) => `Pronto. Seu plano de ${ano} ✨`,
    formOrcLegGuardados: (pct) => `${pct} pro futuro`,
    formOrcFimDoAno: "O que isso vira no fim do ano",
    formOrcFimDoAnoValor: (valor) => `${valor} pro futuro`,
    formOrcPraOndeNota: "Sua segurança primeiro, depois os sonhos por prazo. O resto fica livre.",
    formOrcEstourou: "As categorias somam mais do que sobra. Volte e ajuste, ou guarde um pouco menos por enquanto.",
    formOrcRendaEAporte: "Renda e o que vai pro futuro",
    formReservaCarteiraSugestao: "Na sua carteira, isso está marcado como segurança.",
    formApVidaCampo: "A vida que você quer, por mês",
    formApInvestidoPergunta: "Quanto você já construiu?",
    formApInvestidoHelp: "Tudo que já está investido hoje e vai compor a sua liberdade.",
    formApInvestidoCampo: "Já investido hoje",
    formApAportePergunta: "Quanto consegue guardar por mês?",
    formApAporteHelp: "O valor médio que você consegue investir todo mês enquanto constrói.",
    formApAporteCampo: "Por mês, em média",
    formApIdadePergunta: "Sua idade e quando quer ser livre",
    formApIdadeHelp: "A idade objetivo é quando você quer viver da renda que construiu. A expectativa de vida é opcional.",
    formApIdadeObjetivo: "Livre aos",
    formApRendAcumulo: "Rendimento enquanto constrói",
    formApRendUsufruto: "Rendimento vivendo da renda",
    formApVerPlano: "Ver minha liberdade",
    formApPararAos: "Quer ser livre aos",
    formApRendVivendo: "Rendimento já vivendo da renda",
    formApRendVivendoHint: "Mais conservador que o de construir, porque agora você depende dele pra viver.",
    formEstSalva: "Estratégia salva. Sua carteira tem um desenho agora.",
    formEstReservaPergunta: "Sua segurança já está completa?",
    formEstPelasMetasAntes: "Pelos seus sonhos, você vai precisar do dinheiro em",
    formLancMetaVinculada: "Sonho vinculado (opcional)",
    formLancLancar: "Registrar",

    // Importação: as instruções ficam iguais; o que muda é o "pronto" e o resumo do mês.
    impNovaCategoriaDica: "A categoria nova já aparece no seu plano pra você combinar um valor pra ela.",
    impImportadosSucesso: (n) => `${n} lançamentos importados. Seu mês ganhou forma ✨`,
    impCarteiraEmDia: (n) =>
      `Sua carteira já está em dia com esse extrato: ${n} ativo${s(n)} conferido${s(n)}, nenhuma mudança encontrada ✨`,
    impRepeteLancado: "Registrado.",
    impRepeteLancadoAteDezembro: "Registrado neste mês e nos seguintes até dezembro.",
    impResumoPronto: "Seu resumo do mês está pronto ✨",
    impResumoProntoSub: "Veja o que o seu dinheiro fez por você este mês",
    impStorySub: "O que o seu dinheiro fez este mês.",
    impStoryAcumuladoRuim: "Mês a mês dá pra virar. O primeiro passo é ver o número — e amanhã é um novo começo.",
    impStoryProjecaoMensal: "Mantendo o que você guarda todo mês, reinvestindo, em 10 anos isso vira até…",
    impStoryNoBolso: "Ficou com você desde o início",
    impStoryPotencial: "Onde isso chega em 10 anos, mantendo o ritmo",

    // Shell: primeiros passos, tour, cartões do mês, avisos.
    uiPrimeirosPassos: "Seus primeiros passos ✨",
    uiPassoOrcamento: "Desenhe seu plano do mês",
    uiPassoCarteira: "Comece a sua carteira de investimentos",
    uiTourBoasVindasTitulo: "Boas-vindas ao SPI Finance ✨",
    uiTourBoasVindasTexto: "Um tour rápido mostrando onde fica cada coisa — vou destacar os botões um por um. Dá pra pular quando quiser.",
    uiTourRegistrarTitulo: "Este + é onde tudo começa",
    uiTourRegistrarTexto: "É por aqui que você registra tudo: digite um gasto, fale por áudio ou importe o extrato do banco. Todo plano começa por ele.",
    uiTourFluxoTexto: "Seu mês em um lugar: renda, gastos e o plano por categoria, com um aviso quando o ritmo acelera demais.",
    uiTourMetasTitulo: "Aqui são os Sonhos",
    uiTourMetasTexto: "Crie seus sonhos (viagem, casa), a sua segurança e a sua liberdade. O app calcula quanto guardar por mês pra você chegar lá.",
    uiTourCarteiraTitulo: "Aqui é o que você construiu",
    uiTourFimTitulo: "Tudo pronto ✨",
    uiTourFimTexto: "Vamos começar? Toque no + e faça o primeiro registro — em segundos você já vê seu mês tomando forma.",
    uiFluxoDicaCorrente: "A faixa entre as duas linhas é o que ficou com você até aqui",
    uiFluxoDicaFechado: "A faixa entre as duas linhas é o que ficou com você",
    uiRendaDividida: "Pra onde foi o que entrou",
    uiRendaFatiaAportes: "Pro futuro",
    uiRendaGastouAMais: (valor) => `Saiu ${valor} a mais do que entrou este mês. Amanhã é um novo começo.`,
    uiRendaManteve: (pct) => `**${pct}** do que entrou ficou com você (entre o que foi pro futuro e o que sobrou).`,
    uiMaioresGastos: "Pra onde mais foi este mês",
    uiInstalarConviteTitulo: "Leve o app no seu celular",
    uiNaoEncontradoTexto: "Verifique o endereço ou volte pro início — sua vida dos sonhos continua lá te esperando.",

    // Configurações e viagem.
    cfgAlertasOrcamento: "Avisos do plano",
    cfgAlertasOrcamentoDica:
      "Categoria com 80% do plano gasto e ainda com metade do mês pela frente, ou já além do plano. Chega no celular (se ligado) ou por e-mail.",
    cfgMetasAtrasadas: "Sonhos atrasados",
    cfgMetasAtrasadasDica: "Quando um sonho fica pra trás do ritmo. Um aviso por sonho por mês.",
    cfgPushDica:
      "Uma mensagem no celular, como as de um app: quando uma categoria está perto de passar do plano e ainda falta metade do mês, ou um sonho ficou pra trás. Sem e-mail.",
    cfgExcluirContaTexto: [
      "Apaga a conta e ",
      "todos os seus dados",
      " (registros, planos, sonhos, carteira) de forma definitiva. Não tem volta — se quiser guardar algo, exporte antes.",
    ],
    cfgPerfisSub: "Cada perfil é um dinheiro separado: registros, sonhos e carteira não se misturam entre eles.",
    cfgPerfisExcluirTexto: ["Excluir ", " apaga junto tudo que está dentro dele: registros, plano, sonhos e carteira. Isso não tem como desfazer."],
    viagemTitulo: "Sua próxima viagem ✨",
    viagemSub: "Estime quanto custa o destino dos seus sonhos e transforme em um sonho com data e valor por mês.",
    viagemPorPessoa: (porPessoa, porMes, meses) =>
      `${porPessoa} por pessoa · guardando ${porMes}/mês, você chega lá em ${meses} ${meses === 1 ? "mês" : "meses"} ✨`,
    viagemMetaCriadaToast: "Sua viagem virou um sonho com data. Veja em Sonhos ✨",
    viagemVerMeta: "Ver meu sonho em Sonhos",
    viagemCriarMeta: "Transformar esta viagem em sonho",
    viagemCriandoMeta: "Criando sonho...",

    // Carteira, análises, página do sonho e gráficos.
    cartSuaCarteira: (n) => `O que você construiu · ${n} ativo${s(n)}`,
    cartVinculados: (n, rotulo) => `${n} ativos ligados a ${rotulo}.`,
    cartRotuloMeta: (nome) => `sonho "${nome}"`,
    cartPorTipo: "O que você tem, por tipo",
    cartOndeVoceEsta: "Onde você está × onde quer chegar",
    cartTracinhoAlvo: "O tracinho é onde você quer chegar. Quem está atrás dele é o que comprar no próximo aporte.",
    cartNaEstrategia: "Carteira do jeito que você desenhou ✨",
    cartDefinaQuanto: "Diga quanto quer ter em cada tipo e compare com o que já tem.",
    cartDefinirEstrategia: "Desenhar estratégia →",
    cartSuasMetas: "Seus sonhos",
    cartObjMeta: "Sonho",
    cartMetaPrefixo: (nome) => `Sonho: ${nome}`,
    cartAporteProntoTitulo: "Pronto, tudo conversando ✨",
    cartAporteEntrouEm: (mes, n) => `O que foi pro futuro em ${mes} entrou em ${n} ativo${s(n)}.`,
    cartMetasAndaram: (lista) => `Seus sonhos andaram junto: ${lista}.`,
    cartVoceAportou: (valor, mes) => `Você guardou ${valor} em ${mes}`,
    cartCadastreAtivo: "Cadastre o ativo que recebeu esse dinheiro e a carteira passa a bater com o que você registrou no mês.",
    cartEnquantoNaoDisser: (meta) =>
      `Enquanto não disser, a carteira fica com um valor e o mês com outro${meta ? `, e o sonho ${meta} não anda junto` : ""}.`,
    cartMetaDoAtivo: (nome) => `sonho: ${nome}`,
    cartPassouDoAporte: (valor) => `Passou ${valor} do que você guardou`,
    cartAporteAplicado: "Carteira e sonhos atualizados com o que foi pro futuro este mês ✨",
    cartDaMeta: (pct, valor) => `${pct} do sonho (${valor})`,
    cartSemAtivos: "Nenhum investimento por aqui ainda.",
    cartColMeta: "Sonho",
    cartSemEstrategiaAntes: "Você ainda não desenhou uma",
    cartSemEstrategiaDepois: ". Diga os percentuais-alvo por classe pra ver aqui o comparativo e o rebalanceamento.",
    fichasSub: "Sua saúde financeira e o que pede atenção agora.",
    fichasInsightsVazio: "Cadastre seu plano, seus sonhos, sua segurança e uma estratégia de carteira pra começar a receber insights automáticos aqui.",
    fichasAtencaoTitulo: "O que pede atenção",
    metaBreadcrumbPlanejamento: "Sonhos",
    metaRitmo: { NOT_STARTED: "Sem prazo hábil", ON_TRACK: "No caminho", BEHIND: "Atrasada", ACHIEVED: "Realizado ✨" },
    metaMesesRestantes: "Meses até lá",
    metaGuardarPorMes: "Por mês, pra chegar lá",
    metaTrajetoria: "O caminho até o sonho",
    grafReserva: "Segurança",
    grafCompletaEm: (quando) => `Chega lá em ${quando}`,

    // Casal: construir junto, cada um na sua proporção.
    casTitulo: "Quanto cada um contribui? ✨",
    casSub: "Quando a renda é diferente, o caminho mais justo é cada um entrar na mesma proporção que representa na renda do casal — não 50/50.",
    casRendaA: "Quanto um dos dois recebe por mês",
    casRendaAHint: "A renda líquida de uma pessoa do casal.",
    casRendaB: "Quanto o outro recebe por mês",
    casRendaBHint: "A renda líquida da outra pessoa.",
    casDespesas: "Despesas comuns do mês",
    casDespesasHint: "Aluguel, mercado, contas da casa: o que é do sonho de vocês dois, não o gasto individual de cada um.",
    casDespesasSugestao: (valor) => `Vocês investiram ${valor} na vida de vocês este mês`,
    casPctLabel: "Já combinaram um percentual diferente? (opcional)",
    casPctSufixo: "% pro outro",
    casPctVoltar: (pct) => `Voltar pra proporção da renda (${pct}%)`,
    casPctDica: "Em branco, sigo a proporção da renda de cada um.",
    casSemRenda: "Preencham a renda dos dois pra ver o caminho de cada um.",
    casHeaderAuto: "Divisão proporcional à renda",
    casHeaderManual: "O percentual que vocês combinaram",
    casTextoAuto: "Quem ganha mais, contribui mais — na mesma proporção da renda do casal. Não é 50/50, é justo com a jornada de cada um.",
    casTextoManual: "Vocês já combinaram esse número entre vocês. Sigo o que foi decidido, não a proporção da renda.",
    casContribA: "Um dos dois contribui com",
    casContribB: "O outro contribui com",
    casContribPct: (pct) => `${pct}% das despesas comuns`,
    casSobraLivre: (valor) => `Sobra livre: ${valor}`,
    casComparandoTitulo: "Comparando com 50/50",
    casComparandoIgual: (valor) => `Se dividissem igual, cada um pagaria ${valor}.`,
    casComparandoMenos: (valor) => `Do jeito que está, quem ganha menos contribui com ${valor} a menos por mês.`,
    casComparandoMais: (valor) => `Do jeito que está, quem ganha menos contribui com ${valor} a mais por mês.`,
    casComparandoParecido: "As rendas de vocês são parecidas, então dá quase no mesmo que 50/50.",
    casComparandoManualNota: (pct) => `Pela proporção da renda, seria ${pct}% pro outro.`,
    casRendaConjunta: (valor) => `Renda conjunta: ${valor}. Não fica salvo — é só pra guiar a decisão desse mês.`,

    // Empresa: vale a pena investir no sonho que já virou negócio?
    invTitulo: "Vale a pena investir na empresa? ✨",
    invSub: "Uma máquina, uma reforma, um segundo ponto, uma contratação: em quanto tempo esse passo se paga, e se rende mais do que deixar o dinheiro aplicado.",
    invCusto: "Quanto custa esse investimento?",
    invCustoHint: "Máquina, reforma, ponto novo, contratação: o valor à vista.",
    invTipoLabel: "O que ele traz pra sua empresa por mês?",
    invTipoVenda: "Mais vendas",
    invTipoEconomia: "Economia de custo",
    invReceitaLabelVenda: "Receita a mais por mês",
    invReceitaLabelEconomia: "Economia por mês",
    invReceitaHintVenda: "Quanto você espera vender a mais por causa dele. Sonhe grande, mas use a média, não o melhor mês.",
    invReceitaHintEconomia: "Quanto deixa de gastar por mês (energia, terceiro, retrabalho).",
    invMargemLabel: "Quanto de cada venda sobra depois dos custos dela",
    invMargemHint: "A margem de contribuição da sua empresa, pela DRE. Vender mais só vale o que sobra depois de mercadoria, taxa e frete.",
    invCustoMensal: "Custo fixo novo por mês",
    invCustoMensalHint: "O que o investimento passa a custar todo mês: manutenção, salário, aluguel maior, software. Zero se não tiver.",
    invPrazoLabel: "Prazo pra avaliar",
    invTaxaLabel: "Aplicação rende ao ano",
    invVeredictoEyebrow: "Veredito",
    invVeredictoValeTitulo: "Vale a pena ✨",
    invVeredictoValeTexto: (meses) => `Se paga em ${meses} ${meses === 1 ? "mês" : "meses"} e rende mais que deixar o dinheiro aplicado. Um passo a mais no seu caminho.`,
    invVeredictoEmpataTitulo: "Empata com a aplicação",
    invVeredictoEmpataTexto: (meses) => `Se paga em ${meses} meses, mas o ganho fica parecido com o da aplicação. Decide pelo que esse passo traz pra sua empresa, não só pela conta.`,
    invVeredictoNaoValeTitulo: "Não vale, por enquanto",
    invVeredictoNaoValeTextoForaDoPrazo: (meses, horizonte) => `Só se paga em ${meses} meses, além dos ${horizonte} que você deu de prazo.`,
    invVeredictoNaoValeTextoRendeMais: "Deixar o dinheiro aplicado rende mais do que esse investimento devolve no prazo dado.",
    invVeredictoNuncaSePagaTitulo: "Não se paga",
    invVeredictoNuncaSePagaTexto: "O custo novo por mês consome toda a margem que a receita nova traz. Esse investimento não se paga do jeito que está.",
    invGanhoMes: "Ganho por mês",
    invGanhoMesNota: "já tirando o custo novo",
    invSePagaEm: "Se paga em",
    invSePagaNunca: "nunca",
    invSePagaNota: "payback",
    invResultadoEm: (horizonte) => `Resultado em ${horizonte} meses`,
    invResultadoNota: (pct) => `${pct}% sobre o investido`,
    invNaAplicacao: "Na aplicação, renderia",
    invNaAplicacaoNota: (taxa) => `${taxa}% ao ano, sem IR`,
    invGraficoTitulo: "Na empresa × na aplicação, mês a mês",
    invGraficoDescSupera: (mes) => `A empresa ultrapassa a aplicação no mês ${mes}. É aí que o investimento começa a valer.`,
    invGraficoDescNaoSupera: "No prazo dado, a aplicação rende mais.",
    invGraficoLegendaEmpresa: "Na empresa",
    invGraficoLegendaAplicacao: "Na aplicação",
    invReceitaNecessariaAntes: (horizonte) => `Pra se pagar dentro de ${horizonte} meses, esse investimento precisa trazer pelo menos `,
    invReceitaNecessariaDepois: " de vendas a mais por mês.",
    invReceitaAbaixo: " Você estimou menos que isso.",
    invReceitaAcima: " Você estimou acima disso.",
    invRodapeNota: "Conta simples, sem inflação nem imposto sobre a aplicação, pra dar a ordem de grandeza. Se a decisão for apertada, converse com o contador antes de assinar.",

    // E-mail: o resumo do mês e o convite pra voltar, no tom aspiracional de sempre.
    emailSaudacao: (nome) => (nome ? `Oi, ${nome} ✨` : "Oi ✨"),
    emailRecapAssunto: (mes) => `O que ${mes} revelou sobre você ✨`,
    emailRecapIntro: (mes) => `${mes} se foi. Veja o que ele revelou sobre sua jornada:`,
    emailRecapSobrou: "Guardado pro seu futuro",
    emailRecapFaltou: "Faltou no mês",
    emailRecapPrimeiroMes: "Esse foi seu primeiro passo registrado — o próximo já vem com comparação.",
    emailRecapGastosIguais: "Seus gastos seguiram no mesmo ritmo do mês anterior.",
    emailRecapGastosMenos: (valor) => `Você gastou ${valor} que no mês anterior. Um passo a mais na direção certa.`,
    emailRecapGastosMais: (valor) => `Seus gastos ficaram ${valor} do mês anterior. Um detalhe a ajustar no caminho.`,
    emailMaiorGasto: "Pra onde mais foi",
    emailRecapBotao: "Ver minha vida em números",
    emailRecapRodape: "Você recebe esse resumo uma vez por mês ✨",
    emailConviteAssunto: (mes) => `${mes} começou — hora de sonhar com números ✨`,
    emailConviteIntro1: (mes) => `Começou ${mes} — e mês novo é o convite certo pra recomeçar, porque você acompanha essa jornada inteira, do início ao fim.`,
    emailConviteIntro2:
      "Não precisa desenhar tudo de uma vez. <strong>Registre um gasto de hoje</strong>, só um, e o app já começa a montar o resto: pra onde seu dinheiro está indo, quanto sobra, quanto dá pra guardar.",
    emailConviteBotao: "Registrar meu primeiro passo",
  },
};
