import { TITULOS_PADRAO, CUMPRIMENTO, inteiro, pctDaRenda, semDiaria, simuladoresDoTema, tarefasDoTema, type Voz } from "../voice-base";

/** "1 ativo" / "2 ativos": o plural, sem repetir a conta em cada frase. */
const s = (n: number) => (n === 1 ? "" : "s");

export const minimalista: Voz = {
  saudacao: (p, nome) => `${CUMPRIMENTO[p]}${nome ? `, ${nome}` : ""}.`,
  subSaudacao: () => null,
  tituloPainel: null,
  rotuloResultado: "Sobrou",
  fraseResultado: (estado, d) => {
    const v = inteiro(d.money, d.resultado);
    if (estado === "ruim") return `Saldo negativo: −${v}.`;
    if (estado === "vazio") return null;
    const pct = pctDaRenda(d);
    return `Você economizou ${v} este mês.${pct ? ` ${pct} da renda.` : ""}`;
  },
  ritmo: { rapido: "Acima do ritmo", limite: "No limite", dentro: "No ritmo" },
  tituloOrcamento: (mes) => `Orçamento de ${mes}`,
  fraseOrcamento: (d) => {
    const pronta = semDiaria(d);
    if (pronta) return pronta;
    if (d.situacao === "estourou") return `${inteiro(d.money, d.restante)} acima do orçamento.`;
    return `${inteiro(d.money, d.porDia!)} disponíveis por dia até dia ${d.ultimoDia}.`;
  },
  mesVazio: "Sem dados. Registre o primeiro lançamento no +.",
  metaBatida: () => "Meta 100% concluída.",
  rodape: () => null,
  nav: { metas: "Metas", flowTabs: ["Visão mensal", "Só gastos", "Orçamento"] },
  titulos: {
    ...TITULOS_PADRAO,
    comparacao: (tipo, valor, mes) =>
      tipo === "sem" ? `Sem gasto em ${mes}` : tipo === "igual" ? `= ${mes}` : tipo === "mais" ? `+${valor} vs. ${mes}` : `−${valor} vs. ${mes}`,
    simuladores: "Simuladores",
    simuladoresSub: "Seis calculadoras.",
    simulador: simuladoresDoTema({
      "/simuladores/financiar-vs-alugar": { subtitle: "Financiar, ou alugar e investir a diferença." },
      "/simuladores/amortizar-vs-investir": { subtitle: "Quitar antes ou investir." },
      "/simuladores/consorcio": { subtitle: "Custo total de cada opção." },
      "/simuladores/marcacao-mercado": { subtitle: "Lucro ou prejuízo na venda antecipada de um prefixado." },
      "/simuladores/carro": { subtitle: "Custo de cada opção em 24 meses." },
      "/simuladores/vale-a-pena": { subtitle: "Preço em horas de trabalho e em rendimento." },
    }),
    registrar: "Registrar",
    registrarNovo: "Novo",
    registrarFalar: "Por voz",
    registrarImportar: "Importar",
    lancamentoSalvo: "Salvo.",
    campeaoTitulo: "Maior gasto",
    campeaoPergunta: (_k, label) => `Gasto em ${label.toLowerCase()}`,
    // Só o necessário. Nenhum emoji, nenhum adjetivo, frases de uma linha.
    visaoGeral: "Visão geral",
    visaoGeralSub: "{ano}.",
    patrimonio: "Patrimônio",
    rendaNoAno: "Renda",
    gastosNoAno: "Gastos",
    sobrouNoAno: "Saldo",
    sobrouNoAnoDica: (_cem, _manteve, pct) => `${pct}% da renda.`,
    statusModulos: "Módulos",
    modReserva: "Reserva",
    modDividendos: "Dividendos",
    economiaNoMes: "Economia",
    economiaAbaixo: "Abaixo do plano",
    economiaAcima: "Acima do plano",
    categoriaEstourou: "Maior desvio",
    categoriaEstourouDica: (pct) => `+${pct}`,
    nenhumaEstourou: "Sem desvios.",
    economizouMaisEm: "Maior economia",
    economizouMaisEmDica: (pct) => `−${pct}`,
    soGastos: "Gastos",
    soGastosSub: "Por categoria.",
    orcamentoSub: "Planejado e realizado.",
    orcamentoPorCategoria: "Por categoria",
    paraOndeFoi: "Gastos por categoria",
    oQueMudou: "Variação",
    ritmoDoMes: "Ritmo",
    anoMesAMes: "Por mês",
    caiuNaConta: "Proventos",
    caiuNaContaSub: "Pagos nos últimos dias. Um toque lança como renda.",
    planejamento: "Planejado",
    metasSub: "Valor, prazo e aporte mensal.",
    metasVazio: "Sem metas.",
    reserva: "Reserva",
    reservaSub: "Meses de proteção × custo mensal.",
    reservaMeta: "Meta",
    reservaAtual: "Atual",
    reservaTempo: "Prazo",
    reservaRendimento: "Rendimento mensal",
    reservaProjecao: "Projeção",
    aposentadoriaSub: "Acúmulo e renda.",
    aposentadoriaWizardSub: "Alguns passos.",
    metaGuardar: (v) => `${v} este mês`,
    metaMeses: (n) => `${n} ${n === 1 ? "mês" : "meses"}`,
    metaAporteToast: (mes) => `Aporte de ${mes} registrado.`,
    metaMarcar: (mes) => `Marcar ${mes}`,
    splitTitulo: (mes) => `Divisão do aporte · ${mes}`,
    splitSub: (v) => `${v} por mês. Reserva, depois metas.`,
    splitVazioTitulo: "Divisão do aporte",
    splitVazioSub: "Defina no orçamento quanto guardar por mês. O app divide entre reserva e metas.",
    // Formulário da reserva
    formCusto: "Custo mensal",
    formCustoHint: "O que a reserva cobre por mês sem renda.",
    formMeses: "Meses de proteção",
    formMesesHint: "Renda estável: 6. Variável: 12.",
    formJaTenho: "Guardado",
    formGuardoPorMes: "Por mês",
    formRende: "Rendimento anual",
    formRendeHint: "Liquidez diária costuma render perto do CDI.",
    // Aposentadoria
    apSeNadaMudar: (idade) => `Projeção aos ${idade} anos`,
    apDaPe: "Suficiente",
    apNaoDaPe: "Insuficiente",
    apVereditoIntro: "Renda do patrimônio sem consumir o principal. Gasto desejado:",
    apTodoMes: "por mês.",
    apDeOndeVem: "Origem",
    apDeOndeVemHint: "Em dinheiro de hoje.",
    apBolso: (anos) => `Do bolso em ${anos} anos`,
    apJuros: "Dos juros",
    apJurosNota: (um, mais) => `A cada ${um} do bolso, ${mais} de juros.`,
    apPremissas: "Premissas",
    apEditar: "Editar dados",
    apProjecao: "Projeção",
    apProjecaoSub: (idade, vida) => `Acúmulo até os ${idade} anos${vida ? `, usufruto até os ${vida}` : ""}.`,
    apAcumuloDesc: "aportes entram, patrimônio cresce.",
    apUsufrutoDesc: "aportes param, saques começam.",
    apAnoAAno: "Ano a ano",
    apNominal: "Nominal",
    apReal: "Real",
    // Abas, menu e semana
    carteiraTabs: ["Ativos", "Por objetivo", "Estratégia"],
    visaoGeralLink: "Ver fluxo",
    semanaTitulo: "Esta semana",
    tarefa: tarefasDoTema({
      lancamentos: (n, feita) => (feita ? `Gastos da semana registrados (${n ?? 0})` : "Registrar gastos da semana"),
      "orcamento-definir": () => "Definir orçamento por categoria",
      "orcamento-estourado": (n, _f, pl) => `Revisar ${n ?? 1} categoria${pl ? "s" : ""} acima do orçamento`,
      "orcamento-ok": () => "Orçamento no plano",
      "reserva-configurar": () => "Definir reserva",
      "reserva-completar": (n) => `Reserva em ${n ?? 0}%`,
      "reserva-ok": () => "Reserva completa",
      "meta-criar": () => "Criar meta",
      "meta-atrasada": (n, _f, pl) => `Retomar ${n ?? 1} meta${pl ? "s" : ""} atrasada${pl ? "s" : ""}`,
      "meta-ok": () => "Metas no ritmo",
      aporte: (_n, feita) => (feita ? "Aporte do mês registrado" : "Separar aporte do mês"),
      "reuniao-casal": () => "15 min olhando os gastos do mês, os dois",
    }),
    navSecao: (b, t) =>
      ({ "/mensal": "Fluxo", "/planejamento": "Planejamento", "/viagem": "Viagem", "/carteira": "Carteira", "/divisao": "Divisão do casal", "/investir": "Vale investir?" } as Record<
        string,
        string
      >)[b] ?? t,
    navFilho: (h, t) =>
      ({ "/planejamento/reserva-emergencia": "Reserva", "/carteira": "Ativos", "/carteira/por-objetivo": "Por objetivo" } as Record<string, string>)[h] ?? t,
    navPerfis: "Perfis",
    navInstalar: "Instalar",
    navWhatsapp: "WhatsApp",
    // Carteira
    carteira: "Carteira",
    carteiraSub: "Ativos e objetivos.",
    carteiraLink: "Por objetivo →",
    carteiraVazio: "Sem ativos. Adicione o primeiro.",
    porObjetivo: "Por objetivo",
    porObjetivoSub: "Posição por objetivo e alocação atual vs. ideal.",
    porObjetivoEditar: "← ativos",
    objSem: "Sem objetivo",
    objSemMetaHint: "Sem meta de reserva cadastrada",
    estrategiaVsAlvo: "Atual × alvo",
    alocacaoPorClasse: "Atual × ideal por classe",
    estrategia: "Estratégia",
    estrategiaSub: "Percentuais-alvo por classe, somando 100%.",
    contribTitulo: (mes) => `Aporte de ${mes}`,
    contribSub: "Sugestão de rebalanceamento.",
    contribLabel: "Aporte",
    contribSemAtivo: " · sem ativo desse tipo",
    contribVazio: "Carteira vazia. A divisão segue a estratégia.",
    contribSemEstrategiaTitulo: "Aporte do mês",
    contribSemEstrategiaSub: "Defina a estratégia e o app divide o aporte por tipo. Três perguntas.",
    contribDefinir: "Definir estratégia →",
    divTitulo: (total) => `Dividendos · ${total}`,
    divNota:
      "Estimativa com a quantidade de hoje; compra ou venda antes da data-com muda o valor. JSCP já líquido dos 15% de IR; dividendos e rendimentos de FII costumam ser isentos. Fonte: investidor10.",
    compHint: "O traço é o alvo. Abaixo dele, comprar no próximo aporte.",
    compVoceTem: "Atual",
    compDeveriaTer: "Alvo",
    objNenhumTitulo: "Sem objetivo definido.",
    objNenhumTexto: (valor) => `${valor} sem objetivo. Defina reserva, liberdade financeira ou meta pra ver quanto falta.`,
    objNenhumLink: "Definir objetivos →",

    // Simuladores
    simSalvarBotao: "Salvar simulação",
    simSalvaToast: "Salvo. Fica na lista de simuladores.",
    simSalvarErro: "Não salvou. Tente de novo.",
    simSalvarNomePlaceholder: "Nome (opcional)",
    simSalvasTitulo: "Salvas",
    simFinValorImovelHint: "Preço de venda do imóvel.",
    simFinEntradaHint: "Pago à vista. O resto é financiado.",
    simFinCetHint: "CET ao ano: juros, tarifas e seguros.",
    simFinValorizacaoHint: "Ao ano, em média.",
    simFinPrazoHint: "Em meses (360 = 30 anos).",
    simFinSistemaHint: "SAC: parcelas caem. Price: parcelas fixas.",
    simFinAluguelHint: "Aluguel do mesmo imóvel por mês.",
    simFinReajusteHint: "Ao ano (IGP-M ou IPCA).",
    simFinRentabilidadeHint: "Rendimento anual do dinheiro investido em vez de comprar.",
    simAmortSaldoHint: "Dívida restante hoje.",
    simAmortCetHint: "CET ao ano da dívida.",
    simAmortPrazoRestanteHint: "Meses até quitar.",
    simAmortValorDisponivelHint: "O valor pra amortizar ou investir.",
    simAmortRentabilidadeHint: "Ao ano, antes do IR.",
    simAmortIrHint: "IR sobre o rendimento (15% em prazos longos).",
    simAmortBarraAmortizar: "Amortizar",
    simAmortBarraAmortizarHint: (meses) => `Juros economizados · quita em ${meses} meses`,
    simAmortBarraInvestir: "Investir",
    simAmortBarraInvestirHint: (taxa) => `Líquido de IR · ${taxa} a.a.`,
    simAmortVeredito: (vencedor, valor) => `${vencedor === "AMORTIZAR" ? "Amortizar" : "Investir"}: ${valor} a mais.`,
    simAmortNota: (semMeses, semJuros, comMeses, comJuros) =>
      `Sem amortizar: ${semMeses} meses, ${semJuros} de juros. Amortizando: ${comMeses} meses, ${comJuros} de juros.`,
    simConsValorBemHint: "Carta de crédito ou preço do bem.",
    simConsTaxaAdm: "Taxa de administração",
    simConsTaxaAdmHint: "Total cobrado pela administradora (ex.: 18%).",
    simConsPrazoHint: "Em meses.",
    simConsEntradaHint: "Entrada no caso de financiar.",
    simConsCetHint: "CET ao ano.",
    simConsPrazoFinHint: "Em meses.",
    simConsOportunidadeHint: "Rendimento anual da entrada se investida (consórcio não exige entrada).",
    simConsBarraFinanciamentoHint: "Custo total com custo de oportunidade da entrada",
    simMarcValorFaceHint: "Valor nominal no vencimento.",
    simMarcTaxaContratadaHint: "Taxa travada na compra.",
    simMarcNovaTaxaHint: "Taxa de mercado hoje. É o que muda o preço.",
    simMarcPrazoTotalHint: "Do início ao vencimento.",
    simMarcAnosRestantesHint: "De hoje ao vencimento.",
    simMarcCupons: "Cupons semestrais?",
    simMarcCuponsHint: "Com cupons semestrais, use a duration pra medir a sensibilidade.",
    simMarcDurationHint: "Prazo médio ponderado dos fluxos; menor que o vencimento por causa dos cupons.",
    simMarcInvestidoHint: "Pra ver o resultado em reais. Pode ficar zerado.",
    simMarcLucro: "Venda antecipada: lucro",
    simMarcPrejuizo: "Venda antecipada: prejuízo",
    simMarcSub: "Até o vencimento, sem esse risco.",
    simMarcLucroVenda: "Resultado na venda antecipada",
    simMarcSensibilidade: "Sensibilidade",
    simMarcLucroInvestido: "Resultado sobre o investido",
    simCarroValorHint: "Preço à vista do 0km.",
    simCarroRevenda1Hint: "Valor de venda após 1 ano.",
    simCarroRevenda2Hint: "Valor de venda após 2 anos.",
    simCarroCombustivelHint: "Média mensal.",
    simCarroAssinaturaHint: "Mensalidade (inclui seguro, manutenção, IPVA).",
    simCarroCustosFixosHint: "IPVA, seguro, manutenção e licenciamento por ano, ao comprar.",
    simCarroOportunidadeHint: "Rendimento mensal do valor da compra se investido.",
    simCarroBarraAssinaturaHint: "Custo líquido em 24 meses",
    simCarroBarraComprarHint: "Custo líquido com depreciação e custo de oportunidade",
    simValePasso1Titulo: "Preço",
    simValePasso1Sub: "O preço do item.",
    simValeSemRenda: (mes) => `Sem renda lançada em ${mes}.`,
    simValeSemRendaMeio: "pra ver o tempo de trabalho, ou",
    simValeCadastre: "cadastre no Fluxo",
    simValePasso2Titulo: "Tipo de gasto",
    simValePasso2Sub: "Muda o cálculo do que deixa de ganhar.",
    simValeCompraUnicaDesc: "Pontual: roupa, eletrônico, viagem.",
    simValeHabitoDesc: "Mensal: assinatura, delivery, café.",
    simValeTempoUnico: "Tempo de trabalho",
    simValeHorizontePergunta: "Investindo em vez de comprar, por quanto tempo?",
    simValeBarraInvestirUnico: "Investir",
    simValeBarraInvestirMensal: "Investir",
    simValeBarraGastar: "Gastar",
    simValeBarraGastarUnicoHint: "Preço de hoje",
    simValeBarraGastarMensalHint: "Total no período",
    simValeVeredito: (valor) => `Investindo: ${valor} a mais no fim.`,
    simValeAindaNaoSei: "Sem decisão",
    simValeEscolhaComprar: "Confira se cabe no orçamento do mês.",
    simValeEscolhaNao: "Sem compra. Mais perto das metas.",
    simValeEscolhaDuvida: "Volte quando decidir.",

    // Formulários
    formSalvando: "Salvando…",
    formSelecione: "Selecione…",
    formMetaCriada: "Meta criada.",
    formMetaAtualizada: "Meta atualizada.",
    formMetaNome: "Nome",
    formMetaNomePlaceholder: "Ex.: Viagem, Apê, Carro",
    formMetaValorAlvo: "Alvo",
    formMetaJaGuardado: "Guardado",
    formMetaMesAno: "Prazo",
    formMetaRende: "Rendimento anual",
    formMetaRendeHint: "Poupança ~6%. CDB e Tesouro Selic ~10%. Na dúvida, 10%.",
    formAtivoAdicionado: "Ativo adicionado.",
    formAtivoAtualizado: "Ativo atualizado.",
    formAtivoQual: "Ativo",
    formAtivoValorAtualHint: "Em branco: cotação de hoje × quantidade.",
    formOrcSalvo: "Plano salvo para o ano.",
    formOrcTitulo: "Orçamento",
    formOrcSub: "Três perguntas. Parte já vem dos lançamentos.",
    formOrcQuantoEntra: "Renda mensal",
    formOrcRenda: "Renda",
    formOrcRendaSugestao: (mes, valor) => `${mes}: ${valor}.`,
    formOrcQuantoGuardar: "Quanto guardar",
    formOrcGuardarPorMes: "Por mês",
    formOrcCursoNota: (pct, liberdade) =>
      `No curso: ${pct}%, sendo ${liberdade}% pra liberdade financeira e 8% pra sonhos. Começando, 10% é comum; dá pra mudar depois. Não é promessa.`,
    formOrcSobraTitulo: "Livre pra gastar",
    formOrcSobraSub: (valor) => `por mês, após guardar ${valor}`,
    formOrcDividir: (valor) => `Dividir ${valor} →`,
    formOrcDividaTitulo: (valor) => `Dividir ${valor}`,
    formOrcSobram: (valor) => `${valor} a distribuir`,
    formOrcPassou: (valor) => `${valor} acima do disponível`,
    formOrcSugerir: "Sugerir",
    formOrcSugestaoNota: (moradia, alimentacao, saude, pct) =>
      `Distribuição do curso: moradia ${moradia}% da renda, alimentação ${alimentacao}%, saúde ${saude}%. Guardando menos que ${pct}%, sobra folga; mais, tudo encolhe. Ponto de partida, ajustável.`,
    formOrcCustomNota: "Pet, academia, filhos: o que é grande e não cabe acima. Anual ÷ 12.",
    formOrcVerPlano: "Ver plano →",
    formOrcSeuPlano: (ano) => `Plano de ${ano}`,
    formOrcProntoPlano: (ano) => `Plano de ${ano}`,
    formOrcFimDoAno: "No fim do ano",
    formOrcFimDoAnoSub: (valor, meses) => `${valor} por mês nos ${meses} meses restantes, mais a sobra.`,
    formOrcPraOnde: "Divisão do aporte",
    formOrcPraOndeNota: "Reserva, depois metas por prazo. O resto fica livre.",
    formOrcFicaLivre: "Livre",
    formOrcEstourou: "Categorias somam mais que o disponível. Ajuste ou guarde menos.",
    formOrcSalvar: "Salvar plano",
    formOrcAjustar: "Ajustar categorias",
    formOrcSemGasto: "sem gasto no mês passado",
    formOrcApagarTitulo: "Apagar categoria",
    formOrcApagarAntes: "Apagar",
    formOrcApagarDepois: "? Os lançamentos ficam, sem categoria.",
    formOrcApagando: "Apagando…",
    formOrcApagar: "Apagar",
    formReservaMediaSugestao: (n) => `Média dos últimos ${n === 1 ? "mês fechado" : `${n} meses fechados`}.`,
    formReservaCarteiraSugestao: "Marcado como reserva na carteira.",
    formApVidaPergunta: "Custo de vida desejado",
    formApVidaHelp: "Gasto mensal a bancar com renda passiva, em valores de hoje.",
    formApVidaCampo: "Gasto mensal",
    formApOutrasPergunta: "Outras rendas",
    formApOutrasHelp: "Aluguel, INSS, pensão: o que continua após parar. Zero se não houver.",
    formApOutrasCampo: "Outras rendas por mês",
    formApInvestidoPergunta: "Investido hoje",
    formApInvestidoHelp: "Tudo que já está aplicado.",
    formApInvestidoCampo: "Patrimônio investido",
    formApAportePergunta: "Aporte mensal",
    formApAporteHelp: "Média investida por mês na fase de acúmulo.",
    formApAporteCampo: "Aporte mensal",
    formApIdadePergunta: "Idade e prazo",
    formApIdadeHelp: "Idade objetivo: quando quer parar. Expectativa de vida é opcional.",
    formApPremissasPergunta: "Premissas",
    formApPremissasHelp: "Valores comuns já preenchidos. Taxas ao ano.",
    formApRendAcumulo: "Rendimento no acúmulo",
    formApInflacao: "Inflação",
    formApRendUsufruto: "Rendimento no usufruto",
    formApCalculando: "Calculando…",
    formApVerPlano: "Ver plano",
    formApGuardarPergunta: "Aporte mensal",
    formApGuardarHint: "Em dinheiro de hoje: o plano assume que acompanha a inflação.",
    formApIdadeHoje: "Idade hoje",
    formApPararAos: "Parar aos",
    formApPremissasSub: "Números técnicos, já preenchidos.",
    formApPremissasNota: "Cenário simulado, não promessa.",
    formApRendem: "Rendimento anual",
    formApRendemHint: "Antes da inflação. Perto do CDI, use o CDI.",
    formApInflacaoAssume: "Inflação",
    formApInflacaoHint: "Traz o dinheiro do futuro pro poder de compra de hoje.",
    formApRendVivendo: "Rendimento vivendo de renda",
    formApRendVivendoHint: "Menor que no acúmulo: agora é a fonte de renda.",
    formApAteIdade: "Até (opcional)",
    formApOutrasRendas: "Outras rendas mensais (opcional)",
    formEstSalva: "Estratégia salva.",
    formEstPerfis: {
      conservador: { nome: "Conservador", descricao: "Previsibilidade; maior parte em renda fixa." },
      moderado: { nome: "Moderado", descricao: "Equilíbrio entre renda fixa e variável." },
      arrojado: { nome: "Arrojado", descricao: "Crescimento no longo prazo; maior parte em renda variável." },
    },
    formEstQuizTitulo: "Três perguntas.",
    formEstPrazoPergunta: "Quando vai precisar do dinheiro?",
    formEstPrazoOpcoes: ["Menos de 2 anos", "2 a 5 anos", "Mais de 5 anos"],
    formEstQuedaPergunta: "Carteira cai 15% num mês. Você…",
    formEstQuedaOpcoes: ["Vende tudo", "Segura", "Compra mais"],
    formEstReservaPergunta: "Reserva de emergência completa?",
    formEstReservaOpcoes: ["Não", "Quase", "Sim"],
    formEstPelasMetasAntes: "Pelas metas, o dinheiro é pra",
    formEstNaoEIsso: "Responder",
    formEstPerfilAntes: "Perfil:",
    formEstUsarPerfil: "Usar",
    formEstPronto: "Ou um perfil pronto (ajustável depois)",
    formEstComoFicaria: "Resultado",
    formEstSalvar: "Salvar",
    formLancDescricaoPlaceholder: "Ex.: lugar, item",
    formLancRepetir: (ano) => `Repetir todo mês até dezembro de ${ano}`,
    formLancSalvar: "Salvar",

    // Importação e a gaveta Registrar
    impImportarArquivo: "Importar arquivo (PDF, Excel, CSV, OFX)",
    impConectarBanco: "Conectar banco",
    impConectarBancoSub: "Open Finance · lançamentos chegam todo dia",
    impVozNaoSuportado: "Sem reconhecimento de voz neste navegador. Use Digitar.",
    impVozNaoEntendi: "Não entendi. Fale de novo.",
    impVozErroPermissao: "Libere o microfone nas configurações do navegador.",
    impVozErroSemFala: "Nada ouvido. Aproxime o microfone.",
    impVozErroRede: "Sem conexão na gravação. Tente de novo.",
    impVozErroSemMicrofone: "Sem microfone neste aparelho.",
    impVozErroGenerico: "Falha na gravação. Tente de novo.",
    impVozSafariDica: "Autorizar o microfone toda vez? O Safari pergunta a cada visita.",
    impLendoArquivo: "Lendo…",
    impErroEnvio: "Falha no envio. Confira a internet.",
    impErroSalvar: "Falha ao salvar. Confira a internet.",
    impProtegido: "Arquivo com senha",
    impSenhaPlaceholder: "Senha",
    impAbrindo: "Abrindo…",
    impDesbloquear: "Desbloquear",
    impOutroArquivo: "Outro arquivo",
    impAplicando: "Aplicando…",
    impArquivoGrande: "Arquivo acima de ~7 MB. Exporte um período menor.",
    impOQueSubindo: "Tipo de arquivo",
    impExtratoDica: "Entradas viram renda, saídas viram gasto.",
    impFaturaDica: "Todas as linhas viram gasto.",
    impFaturaMes: "Mês da fatura",
    impFaturaMesDica: (mes) => `Todas as compras entram em ${mes}, mesmo as do mês anterior.`,
    impEscolherExtrato: "Escolher arquivo",
    impFormatosBanco: "CSV, OFX, Excel ou PDF do banco",
    impSenhaDicaBanco: "Em geral, o CPF só com números. Senão, está no e-mail do banco que enviou o arquivo.",
    impPareceFaturaAviso: "Como extrato, cada compra vira renda.",
    impPareceExtratoAviso: "Como fatura, cada entrada vira gasto.",
    impRevisar: (atual, total) => `${atual} de ${total}`,
    impParcela: (atual, total, restantes) => `Parcela ${atual} de ${total}. As ${restantes} seguintes entram nos próximos meses.`,
    impQualCategoria: "Categoria",
    impNovaCategoriaPlaceholder: "Nome (ex.: Fatura, Pet, Farmácia)",
    impCriando: "Criando…",
    impNovaCategoriaDica: "A categoria nova aparece no Orçamento.",
    impSemCategoriaTitulo: (n) => `${n} gasto${s(n)} sem categoria`,
    impSemCategoriaSub: (_n, soma) => `Fora da importação. Soma ${soma}.`,
    impCategorizar: () => "Categorizar →",
    impNumerosErrados: "Números incorretos?",
    impNumerosErradosDica:
      "Confira a lista antes de confirmar. Se estiver errado, fale com a gente: guardamos uma cópia do arquivo e ensinamos o app a ler esse banco.",
    impEntendiComo: (resumo) => `Lido como: ${resumo}.`,
    impLinhasLidas: (lidas, total) => `${lidas} de ${total} linhas com valor lidas.`,
    impTotalImpresso: (valor) => `Total impresso: ${valor}.`,
    impCoberturaBaixa: "Menos da metade das linhas virou lançamento. Confira.",
    impFaltouCoisa: "Faltou algo",
    impSomaDiferente: (abaixo, diferenca) => `Soma lida ${diferenca} ${abaixo ? "abaixo" : "acima"} do total impresso. Pode faltar ou sobrar linha.`,
    impRepetidos: "Repetidos",
    impRepetidosDica: "Mesma data, valor e descrição. Compra real: mantenha. Arquivo repetindo: deixe uma.",
    impImportando: "Importando…",
    impImportadosSucesso: (n) => `${n} lançamentos importados.`,
    impPagamentoFatura: (n) =>
      `${n === 1 ? "Este lançamento" : "Estes lançamentos"} do extrato ${n === 1 ? "parece" : "parecem"} o pagamento desta fatura. Remover pra não contar duas vezes?`,
    impRemovidoExtrato: "Removido.",
    impCarteiraArquivoGrande: "Arquivo acima de ~7 MB. Exporte um relatório menor.",
    impCarteiraEscolher: "Escolher arquivo",
    impSenhaDicaCorretora: "A senha da corretora. Usada só pra abrir, não fica salva.",
    impCarteiraLiTudo: (resumo) => `Arquivo lido: ${resumo}.`,
    impCarteiraEmDia: (n) => `Carteira em dia. ${n} ativo${s(n)} conferido${s(n)}, sem mudança.`,
    impCarteiraNovos: "Novos",
    impCarteiraSemMudanca: (n) => `${n} ativo${s(n)} sem mudança.`,
    impCarteiraFeito: (criados, atualizados) =>
      [criados > 0 ? `${criados} novo${s(criados)}` : null, atualizados > 0 ? `${atualizados} atualizado${s(atualizados)}` : null]
        .filter(Boolean)
        .join(" · ") || "Sem mudança.",
    impIrpfArquivoGrande: "Arquivo acima de ~7 MB.",
    impIrpfSelecioneUm: "Selecione ao menos um ativo.",
    impIrpfIntro: [
      "A declaração de IR traz o ",
      "preço médio",
      " de cada ação e FII, que os extratos de corretora não trazem. Suba o PDF do recibo e o investido de cada ativo é preenchido, pro lucro/prejuízo calcular certo.",
    ],
    impIrpfLendo: "Lendo…",
    impIrpfEscolher: "Escolher PDF",
    impIrpfEncontrei: (n) => `${n} ativo${s(n)} com preço médio.`,
    impIrpfConfira: "Confira o ativo da carteira em cada linha. Sem par: escolha à mão ou deixe de fora.",
    impIrpfComoFunciona: "Preço médio × quantidade vira o valor investido. A cotação não muda; só a base do lucro/prejuízo.",
    impIrpfConcluido: (n) => `Preço médio aplicado em ${n} ativo${s(n)}.`,
    impHistoricoTitulo: "Importações",
    impHistoricoConfirmar: "Confirmar?",
    impHistoricoDesfeita: (n) => `Desfeita. ${n} lançamento${s(n)} removido${s(n)}.`,
    impHistoricoNota: "Desfazer apaga todos os lançamentos do arquivo. Importações anteriores a este histórico não aparecem.",
    impRepeteTitulo: "Recorrentes",
    impRepeteSub: "Nos meses anteriores, não neste. Um toque lança.",
    impRepeteLancadoAteDezembro: "Lançado até dezembro.",
    impRepeteErro: "Não lançou. Tente de novo.",
    impResumoPronto: "Resumo do mês",
    impResumoProntoSub: "Ver",
    impStoryTitulo: "Resumo mensal",
    impStorySub: "O mês em números.",
    impStoryGastou: "Gastos do mês",
    impStoryMaiorParte: "Maior parte",
    impStoryComparado: "Vs. mês anterior",
    impStoryDiaEconomico: "Dia da semana com menos gasto",
    impStoryDiaGastador: "Dia da semana com mais gasto",
    impStoryDesdeQueChegou: (meses, positivo) => `Desde o início (${meses} ${meses === 1 ? "mês" : "meses"}),${positivo ? " no bolso" : " saldo"}`,
    impStoryAcumuladoRuim: "Muda mês a mês. Primeiro passo: ver o número.",
    impStoryProjecaoUnica: "Tudo que já juntou, investido hoje de uma vez, em 10 anos vira até…",
    impStoryProjecaoUnicaNota: (valor) => `*${valor} de uma vez a 10% a.a. Estimativa, não garantia.`,
    impStoryProjecaoMensal: "Poupança média mantida e reinvestida, em 10 anos vira até…",
    impStoryProjecaoMensalNota: (valor) => `*${valor}/mês (poupado no ano ÷ meses preenchidos) a 10% a.a. Estimativa, não garantia.`,
    impStoryPotencial: "Em 10 anos, mantendo a média",
    impStoryCompartilhar: "Compartilhar",
    impShareTitulo: "Resumo do mês",
    impShareImagemTitulo: ["Resumo", "do mês"],
    impShareGastei: "Gastos do mês",
    impShareFicouNoBolso: "No bolso desde o início",
    impSharePotencial: "Em 10 anos, mantendo a média",
    impShareTexto: (periodo, gastei, positivo, saldo, potencial) =>
      [`Resumo do mês (${periodo}):`, `• Gastos: ${gastei}`, `• ${positivo ? "No bolso" : "Saldo"} desde o início: ${saldo}`, `• Em 10 anos: ${potencial}`].join("\n"),

    // Shell: primeiros passos, tour, cartões do Fluxo, instalar, erros
    uiPassoRegistrar: "Registrar o primeiro lançamento",
    uiPassoOrcamento: "Definir o orçamento do mês",
    uiPassoCarteira: "Montar a carteira",
    uiDispensarGuia: "Dispensar",
    uiTourBoasVindasTitulo: "SPI Finance",
    uiTourBoasVindasTexto: "Um tour pelos botões. Dá pra pular.",
    uiTourRegistrarTitulo: "Registrar",
    uiTourRegistrarTexto: "Digitar, falar ou importar o extrato. Tudo começa aqui.",
    uiTourFluxoTitulo: "Fluxo",
    uiTourFluxoTexto: "Renda, gastos e orçamento por categoria, com alerta de ritmo.",
    uiTourMetasTitulo: "Metas",
    uiTourMetasTexto: "Metas, reserva e aposentadoria. O app calcula quanto guardar por mês.",
    uiTourCarteiraTitulo: "Carteira",
    uiTourCarteiraTexto: "Investimentos e o lucro de cada um. Preço médio direto da declaração de IR.",
    uiTourMaisTitulo: "Mais",
    uiTourMaisTexto: "Visão geral, simuladores e análises.",
    uiTourFimTitulo: "Fim do tour",
    uiTourFimTexto: "Toque no + e registre o primeiro lançamento.",
    uiFluxoTituloFuturo: (mes) => `Marcado para ${mes}`,
    uiFluxoTituloCorrente: (mes) => `${mes} até hoje`,
    uiFluxoTituloFechado: (mes) => mes,
    uiFluxoDicaFuturo: "Repetidos e agendados. O mês não começou.",
    uiFluxoDicaCorrente: "Entre as linhas: o que sobrou até aqui",
    uiFluxoDicaFechado: "Entre as linhas: o que sobrou",
    uiFluxoSemData: (quantos, valor) =>
      quantos === 1
        ? `1 lançamento sem data (${valor}) fora da curva; conta no total.`
        : `${quantos} lançamentos sem data (${valor}) fora da curva; contam no total.`,
    uiRendaDividida: "Divisão da renda",
    uiRendaGastouAMais: (valor) => `${valor} acima da renda este mês.`,
    uiRendaManteve: (pct) => `**${pct}** da renda mantidos (aportes e sobra).`,
    uiMaioresGastos: "Maiores gastos",
    uiSetaCompara: "Seta: vs. mês passado. Variação abaixo de 8% não aparece.",
    uiHeatmapDica: "Um quadrado por dia; mais forte, mais gasto.",
    uiHeatmapPico: (dia, valor) => `Pico: dia ${dia} · ${valor}`,
    uiVerMaisLancamentos: (quantos) => `Mais ${quantos}`,
    uiSairDaSelecao: "Sair",
    uiEditarLancamento: "Editar",
    uiRemoverLancamento: "Remover",
    uiExcluido: (quantos) => (quantos === 1 ? "Excluído." : `${quantos} excluídos.`),
    uiExcluidoContinuaNaCarteira: "O distribuído continua na carteira.",
    uiRestaurado: (quantos) => (quantos === 1 ? "Restaurado." : `${quantos} restaurados.`),
    uiRestaurarFalhou: "Não restaurou. Lance de novo.",
    uiInstalarConviteTitulo: "Instalar no celular",
    uiInstalarConviteSub: "Tela cheia, ícone próprio.",
    uiInstalarVerComo: "Como",
    uiInstalarFecharConvite: "Fechar",
    uiInstalarTitulo: "Instalar",
    uiInstalarIntro: "Ícone na tela inicial, tela cheia, sem barra do navegador. Não ocupa espaço de app de loja e atualiza sozinho.",
    uiInstalarAgora: "Instalar",
    uiInstalando: "Instalando…",
    uiInstalarNativoDica: "Toque no botão e confirme na janela.",
    uiInstalarNoComputador: "No computador. Pra instalar no celular, abra o site pelo navegador do telefone.",
    uiInstalarPassosSafari: [
      "Toque em **Compartilhar** (quadrado com seta pra cima, na barra de baixo).",
      "Role e toque em **Adicionar à Tela de Início**.",
      "Toque em **Adicionar**, no canto de cima.",
    ],
    uiInstalarPassosIosOutro: [
      "Toque no menu do navegador (**⋯** ou **⋮**).",
      "**Compartilhar** › **Adicionar à Tela de Início**.",
      "Confirme em **Adicionar**. Sem a opção, abra no **Safari**.",
    ],
    uiInstalarPassosAndroid: [
      "Toque no menu **⋮**, canto superior direito.",
      "Toque em **Instalar aplicativo** (ou **Adicionar à tela inicial**).",
      "Confirme em **Instalar**.",
    ],
    uiPaywallTitulo: (recurso) => `${recurso}: conteúdo do curso`,
    uiPaywallTexto: "Área do curso de investimentos. Aluna(o) vendo isso por engano: fale com o suporte; pode ser e-mail de cadastro diferente do da compra.",
    uiPaywallBotao: "Ver o curso",
    uiMudarParaEscuro: "Tema escuro",
    uiMudarParaClaro: "Tema claro",
    uiErroTitulo: "Erro",
    uiErroTexto: "Erro nosso; seus dados estão seguros. Recarregue. Se continuar, saia e entre de novo.",
    uiNaoEncontradoRotulo: "404",
    uiNaoEncontradoTitulo: "Página não encontrada.",
    uiNaoEncontradoTexto: "Confira o endereço ou volte ao início.",
    uiNaoEncontradoVoltar: "Início",

    // Configurações, perfis e viagem
    cfgSalvando: "Salvando…",
    cfgPerfilSub: "Dados pessoais.",
    cfgPerfilNomePlaceholder: "Nome",
    cfgPerfilEmailDica: "E-mail de acesso. Pra trocar, fale com o suporte.",
    cfgPerfilFoto: "Foto (URL, opcional)",
    cfgPreferenciasSub: "Moeda e tema.",
    cfgModoDecididoPeloTema: "Claro ou escuro vem do tema do perfil ativo. Mude em Perfis financeiros; só o Padrão tem os dois.",
    cfgMoedaAvisoTexto1: (exemploNovo, exemploAntigo) =>
      `Só o símbolo muda: 3.000 passa de "${exemploAntigo}" a "${exemploNovo}". Use se toda a vida financeira é em outra moeda.`,
    cfgMoedaAvisoTexto2: "Só uma parte em outra moeda? Mantenha a principal aqui e escolha a moeda ao lançar; aí o app converte pela cotação do dia.",
    cfgAplicadoAoSalvar: "Aplicado ao salvar.",
    cfgCategoriasSub: "Categorias-mãe e subcategorias usadas no Fluxo. Em qualquer lançamento, o chip 'Outro' aceita uma subcategoria livre.",
    cfgNotificacoesSub: "Celular, e-mail e Análises.",
    cfgResumoEmail: "Resumo mensal por e-mail",
    cfgResumoEmailDica: "No começo de cada mês: entrou, saiu e o que mudou.",
    cfgAlertasOrcamentoDica: "Categoria com 80% do planejado gasto antes da metade do mês, ou estourada. Celular (se ligado) ou e-mail.",
    cfgMetasAtrasadasDica: "Meta atrás do ritmo. Um aviso por meta por mês.",
    cfgPushDica: "Notificação no celular: categoria perto de estourar antes da metade do mês, ou meta atrás. Sem e-mail.",
    cfgPushVerificando: "Verificando…",
    cfgPushIos: "No iPhone, só com o app instalado na tela de início: Compartilhar › Adicionar à Tela de Início, abra por lá e volte aqui.",
    cfgPushNaoSuportado: "Este navegador não recebe notificações. No celular, instale o app.",
    cfgPushBloqueado: "Notificações bloqueadas. Libere nas configurações do navegador.",
    cfgPushLigar: "Ligar neste aparelho",
    cfgPushLigando: "Ligando…",
    cfgPushDesligar: "Desligar",
    cfgPushLigadoToast: "Ligado.",
    cfgPushFalhouToast: "Não ligou. Tente de novo.",
    cfgConexoesTitulo: "Conectar banco",
    cfgConexoesSub: "Open Finance: lançamentos da conta e do cartão chegam toda noite.",
    cfgConexoesDesligada: "Conexão com bancos ainda desligada. Enquanto isso: Registrar › Importar.",
    cfgConexaoNadaNovo: "Nada novo. Nova busca toda noite.",
    cfgConexaoChegaram: (novos, semCategoria) => `${novos} lançamentos dos últimos 90 dias${semCategoria > 0 ? `, ${semCategoria} sem categoria` : ""}.`,
    cfgConexaoVerNoMes: "Ver mês →",
    cfgConexoesIntro: "Open Finance via Meu Pluggy, site parceiro gratuito. Conectado, o SPI busca os lançamentos toda noite. Sem arquivo.",
    cfgConexoesPasso1: "Conta no Meu Pluggy",
    cfgConexoesPasso1Dica: "Site parceiro, gratuito. Abre em outra aba.",
    cfgConexoesPasso2: "Conectar o banco lá",
    cfgConexoesPasso2Dica: "Nubank, Itaú, Inter, C6… O banco pede autorização pelo app dele. Cartão incluso.",
    cfgConexoesPasso3: "Autorizar o SPI",
    cfgConexoesPasso3Dica: "Volte e toque em autorizar. Só leitura: o SPI não move dinheiro.",
    cfgConexoesCriarConta: "Criar conta ↗",
    cfgConexoesAutorizar: "Autorizar o SPI",
    cfgConexoesAbrindo: "Abrindo…",
    cfgConexoesRodape: "Os dados passam pela Pluggy, regulada pelo Banco Central, e chegam ao SPI como lançamentos. Desconecte aqui quando quiser. Ou continue subindo o extrato.",
    cfgConexaoAindaNaoBuscou: "sem busca",
    cfgConexaoReautorizar: "reautorizar",
    cfgDesconectarConfirma: (banco) => `Desconectar ${banco}? Os lançamentos ficam.`,
    cfgConexaoNaoDeu: (motivo) => `Falhou: ${motivo}`,
    cfgConexaoNaoConcluida: "Conexão não concluída.",
    cfgConexaoNaoAbriu: "Não abriu. Tente de novo.",
    cfgDadosSub: "Exportar ou excluir a conta.",
    cfgExportLancamentosDica: "CSV com todos os lançamentos (renda, gastos, aportes), com categoria-mãe e subcategoria.",
    cfgExportLancamentos: "Lançamentos (CSV)",
    cfgExportCarteiraDica: "CSV com todos os ativos (nome, ticker, classe, quantidade, investido, atual).",
    cfgExportCarteira: "Carteira (CSV)",
    cfgExportando: "Exportando…",
    cfgExportFalhou: "Não exportou. Tente de novo.",
    cfgExcluirContaTitulo: "Excluir conta",
    cfgExcluirContaTexto: ["Apaga a conta e ", "todos os dados", " (lançamentos, orçamentos, metas, carteira). Sem volta. Exporte antes se quiser guardar."],
    cfgExcluirContaQuero: "Excluir conta",
    cfgExcluirContaSenha: "Senha",
    cfgExcluirContaBotao: "Excluir definitivamente",
    cfgExcluindo: "Excluindo…",
    cfgTaxasTitulo: "Taxas",
    cfgTaxasSub: "Referência para planejamento e simuladores.",
    cfgTaxaSua: "Sua",
    cfgTaxaPadraoSistema: "Sistema",
    cfgTaxaAdicionadaToast: "Taxa adicionada.",
    cfgTaxasVazio: "Sem taxas.",
    cfgPerfisTitulo: "Perfis",
    cfgPerfisSub: "Cada perfil é um dinheiro separado: lançamentos, metas e carteira não se misturam.",
    cfgPerfisGerenciar: "Gerenciar",
    cfgPerfisEmUso: "em uso",
    cfgPerfisTrocouToast: (nome) => `Perfil: ${nome}.`,
    cfgPerfisCriadoToast: (nome) => `${nome} criado e em uso.`,
    cfgPerfisExcluidoToast: (nome) => `${nome} excluído.`,
    cfgPerfisFalhou: "Não deu. Tente de novo.",
    cfgPerfisExcluirTexto: ["Excluir ", " apaga tudo dentro dele: lançamentos, orçamento, metas e carteira. Sem volta."],
    cfgPerfisEscrevaParaConfirmar: (nome) => `Escreva ${nome}`,
    cfgPerfisExcluirParaSempre: "Excluir",
    viagemTitulo: "Viagem",
    viagemSub: "Custo estimado do destino, convertido em meta com aporte mensal.",
    viagemVazio: "Busque o primeiro destino. Vários lugares na mesma viagem, com dias em cada um.",
    viagemBuscarPlaceholder: "Destino (ex.: Paris, Jeri, Japão)",
    viagemNenhumDestino: "Nenhum destino. Tente outro nome ou o país.",
    viagemQuantasPessoas: "Pessoas",
    viagemEstilo: "Estilo",
    viagemQuando: "Quando",
    viagemAltaTemporadaDica: (pct) => `— passagem e hospedagem cerca de ${pct}% mais caras neste mês.`,
    viagemBaixaTemporadaDica: (pct) => `— passagem e hospedagem cerca de ${pct}% mais baratas.`,
    viagemMediaDica: "Média para uma viagem assim. Toque no número pra ajustar; o total recalcula.",
    viagemMargem: "Imprevistos (10%)",
    viagemDeOndeVemCusto: "Composição",
    viagemCustoEstimado: "Custo estimado",
    viagemPorPessoa: (porPessoa, porMes, meses) => `${porPessoa} por pessoa · ${porMes}/mês, ${meses} ${meses === 1 ? "mês" : "meses"}.`,
    viagemMetaCriadaToast: "Meta criada. Ver em Metas.",
    viagemVerMeta: "Ver meta",
    viagemCriarMeta: "Criar meta",
    viagemCriandoMeta: "Criando…",
    viagemRodape:
      "Estimativas médias (valores de 2026, saindo do Brasil), não cotação. Passagem: ida e volta principal mais conexões entre destinos. Mudar roteiro, pessoas ou estilo re-estima tudo.",

    // Carteira: ativos, aporte, por objetivo, Análises, meta e gráficos
    cartSuaCarteira: (n) => `Carteira · ${n} ativo${s(n)}`,
    cartMostrarValores: "Mostrar",
    cartOcultarValores: "Ocultar",
    cartAtualizando: "Atualizando…",
    cartAtualizarCotacoes: "Atualizar",
    cartCotacoesNaoAchei: (n, lista) => `${n} atualizadas · sem cotação: ${lista}`,
    cartVinculados: (n, rotulo) => `${n} ativos em ${rotulo}.`,
    cartPorTipo: "Por tipo",
    cartOndeVoceEsta: "Atual × estratégia",
    cartTracinhoAlvo: "O traço é o alvo. Abaixo dele, comprar no próximo aporte.",
    cartNaEstrategia: "No alvo",
    cartDefinaQuanto: "Defina o alvo por tipo e compare com a carteira.",
    cartPraFicarNoAlvo: "Pra chegar ao alvo:",
    cartVerRebalanceamento: "Rebalanceamento →",
    cartAplicando: "Aplicando…",
    cartDefinirObjetivoDos: (n) => `Objetivo dos ${n}…`,
    cartSuasMetas: "Metas",
    cartObjetivosGerais: "Gerais",
    cartSalvarAlteracoes: "Salvar",
    cartImportarCarteira: "Importar",
    cartPrecoMedioDeclaracao: "Preço médio pela declaração",
    cartEditarAtivo: "Editar",
    cartAporteProntoTitulo: "Aplicado.",
    cartAporteEntrouEm: (mes, n) => `Aporte de ${mes} em ${n} ativo${s(n)}.`,
    cartMetasAndaram: (lista) => `Metas atualizadas: ${lista}.`,
    cartVoceAportou: (valor, mes) => `Aporte de ${valor} em ${mes}`,
    cartCadastreAtivo: "Cadastre o ativo que recebeu o valor pra carteira bater com o mês.",
    cartDigaQuanto: "Valor por ativo.",
    cartToquePraDizer: "Toque pra distribuir.",
    cartEnquantoNaoDisser: (meta) => `Até lá, carteira e mês com valores diferentes${meta ? `; a meta ${meta} não avança` : ""}.`,
    cartQuantoEntrouEm: (nome) => `Em ${nome}`,
    cartVerOutros: (n) => `Outros ${n}`,
    cartFaltaDizer: (valor) => `Falta ${valor}`,
    cartPassouDoAporte: (valor) => `${valor} acima do aporte`,
    cartTudoDistribuido: "Distribuído",
    cartAporteAplicado: "Carteira e metas atualizadas.",
    cartAplicandoAporte: "Aplicando…",
    cartAtualizarCarteira: "Atualizar carteira",
    cartAtivoNaoEstaAqui: "Ativo não listado? Cadastre",
    cartEditarEstrategia: "editar",
    cartDefinirEstrategiaCurto: "definir",
    cartSemAtivos: "Sem ativos.",
    cartSemEstrategiaAntes: "Sem",
    cartSemEstrategiaDepois: ". Defina os percentuais-alvo por classe pra ver comparativo e rebalanceamento.",
    cartReferenciaMatematica: "Referência matemática pela estratégia; não é recomendação.",
    fichasSub: "Saúde financeira e pontos de atenção.",
    fichasInsightsVazio: "Cadastre orçamento, metas, reserva e estratégia pra receber insights.",
    fichasAtencaoTitulo: "Atenção",
    fichasAcoesTitulo: "Ações",
    fichasAcoesSub: "Nome ou código. O app lê os números.",
    fichasFiisTitulo: "FIIs",
    fichasFiisSub: "Nome ou código. O app lê o fundo.",
    fichasStocksTitulo: "Stocks",
    fichasStocksSub: "Ações no exterior. Nome ou código.",
    fichasEtfsTitulo: "ETFs",
    fichasEtfsSub: "Nome ou código. O app lê o fundo.",
    fichasAnalisesVazio: "Sem análises. Digite um código acima.",
    fichasSuasAnalises: "Análises",
    fichasNaCarteira: "na carteira",
    fichasNaoLida: "não lida",
    fichasFichaCriada: "Ficha criada.",
    fichasQualAcao: "Ação",
    fichasQualFii: "Fundo imobiliário",
    fichasQualEtf: "ETF",
    fichasQualEmpresa: "Empresa",
    fichasLendo: "Lendo…",
    fichasNotaDetalhada: "Nota detalhada",
    fichasNotaDetalhadaSub: "Ficha completa, nota de 0 a 10 por critério.",
    fichasLendoNumeros: (ticker) => `Lendo ${ticker}…`,
    fichasEsconderNumeros: "Esconder",
    fichasVerNumeros: (n) => `${n} números ›`,
    fichasComoLer: "Como ler",
    fichasReanalisar: "Reanalisar",
    fichasNotaAutomatica: (nota) => `Nota ${nota} de 10`,
    fichasSoVoce: "Sua resposta",
    fichasParaVoce: "Na sua carteira",
    fichasNaSuaCarteira: (ticker) => `${ticker} na carteira`,
    fichasEstrategiaPede: (classe, pct) => `${classe}: alvo ${pct}`,
    fichasConcentra: "Comprar mais concentra além do alvo da estratégia.",
    fichasNaoRecomendacao: "Não é recomendação: sua carteira lida com os números do ativo.",
    metaBreadcrumbPlanejamento: "Planejamento",
    metaRitmo: { NOT_STARTED: "Sem prazo", ON_TRACK: "No ritmo", BEHIND: "Atrasada", ACHIEVED: "Concluída" },
    metaFaltaGuardar: "Falta",
    metaGuardarPorMes: "Por mês",
    metaTrajetoria: "Projeção",
    metaSalvarAlteracoes: "Salvar",
    metaDaquiAMeses: (n) => `Em ${n} meses`,
    grafSemDados: "Sem dados.",
    grafSobrouChip: (sobrou, mesAtual, valor) => `${sobrou ? "Sobrou" : "Faltou"}${mesAtual ? " até aqui" : ""}: ${valor}`,
    grafPronta: (pct) => `${pct}%`,
    grafNenhumGasto: "Sem gastos no período.",
    grafVereditoAlugar: (diferenca, anos) => `Alugar e investir: ${diferenca} à frente em ${anos} anos.`,
    grafVereditoFinanciar: (diferenca, anos) => `Financiar: ${diferenca} à frente em ${anos} anos.`,

    // Casal
    casTitulo: "Quanto cada um paga",
    casSub: "Divisão proporcional à renda, não 50/50.",
    casRendaA: "Renda de um dos dois",
    casRendaAHint: "Líquida, por mês.",
    casRendaB: "Renda do outro",
    casRendaBHint: "Líquida, por mês.",
    casDespesas: "Despesas comuns do mês",
    casDespesasHint: "Aluguel, mercado, contas da casa. Não inclui gasto individual.",
    casDespesasSugestao: (valor) => `Gasto do mês: ${valor}`,
    casPctLabel: "Percentual combinado (opcional)",
    casPctSufixo: "% pro outro",
    casPctVoltar: (pct) => `Voltar à proporção da renda (${pct}%)`,
    casPctDica: "Em branco, usa a proporção da renda.",
    casSemRenda: "Preencha a renda dos dois.",
    casHeaderAuto: "Divisão proporcional à renda",
    casHeaderManual: "Percentual combinado",
    casTextoAuto: "Cada um paga na mesma proporção que representa na renda do casal.",
    casTextoManual: "Percentual definido por vocês, não pela proporção da renda.",
    casContribA: "Um dos dois paga",
    casContribB: "O outro paga",
    casContribPct: (pct) => `${pct}% das despesas comuns`,
    casSobraLivre: (valor) => `Sobra: ${valor}`,
    casComparandoTitulo: "Comparado com 50/50",
    casComparandoIgual: (valor) => `Dividido igual, cada um pagaria ${valor}.`,
    casComparandoMenos: (valor) => `Quem ganha menos paga ${valor} a menos por mês.`,
    casComparandoMais: (valor) => `Quem ganha menos paga ${valor} a mais por mês.`,
    casComparandoParecido: "Rendas parecidas: quase igual a 50/50.",
    casComparandoManualNota: (pct) => `Pela renda, seria ${pct}%.`,
    casRendaConjunta: (valor) => `Renda conjunta: ${valor}. Não fica salvo.`,

    // Empresa
    invTitulo: "Vale a pena investir na empresa?",
    invSub: "Payback e comparação com a aplicação.",
    invCusto: "Custo do investimento",
    invCustoHint: "Valor à vista.",
    invTipoLabel: "O que traz por mês",
    invTipoVenda: "Mais vendas",
    invTipoEconomia: "Economia de custo",
    invReceitaLabelVenda: "Receita a mais por mês",
    invReceitaLabelEconomia: "Economia por mês",
    invReceitaHintVenda: "Média esperada, não o melhor mês.",
    invReceitaHintEconomia: "O que deixa de gastar por mês.",
    invMargemLabel: "Margem sobre cada venda",
    invMargemHint: "Margem de contribuição, pela DRE.",
    invCustoMensal: "Custo fixo novo por mês",
    invCustoMensalHint: "Manutenção, salário, aluguel, software. Zero se não tiver.",
    invPrazoLabel: "Prazo de avaliação",
    invTaxaLabel: "Taxa da aplicação ao ano",
    invVeredictoEyebrow: "Veredito",
    invVeredictoValeTitulo: "Vale a pena",
    invVeredictoValeTexto: (meses) => `Payback em ${meses} ${meses === 1 ? "mês" : "meses"}. Rende mais que a aplicação.`,
    invVeredictoEmpataTitulo: "Empata com a aplicação",
    invVeredictoEmpataTexto: (meses) => `Payback em ${meses} meses, ganho parecido com a aplicação.`,
    invVeredictoNaoValeTitulo: "Não vale, por enquanto",
    invVeredictoNaoValeTextoForaDoPrazo: (meses, horizonte) => `Payback em ${meses} meses, além do prazo de ${horizonte}.`,
    invVeredictoNaoValeTextoRendeMais: "A aplicação rende mais que esse investimento, no prazo dado.",
    invVeredictoNuncaSePagaTitulo: "Não se paga",
    invVeredictoNuncaSePagaTexto: "O custo novo consome toda a margem da receita nova.",
    invGanhoMes: "Ganho por mês",
    invGanhoMesNota: "líquido do custo novo",
    invSePagaEm: "Payback",
    invSePagaNunca: "nunca",
    invSePagaNota: "payback",
    invResultadoEm: (horizonte) => `Resultado em ${horizonte} meses`,
    invResultadoNota: (pct) => `${pct}% sobre o investido`,
    invNaAplicacao: "Rendimento da aplicação",
    invNaAplicacaoNota: (taxa) => `${taxa}% ao ano, sem IR`,
    invGraficoTitulo: "Empresa × aplicação",
    invGraficoDescSupera: (mes) => `Empresa supera a aplicação no mês ${mes}.`,
    invGraficoDescNaoSupera: "A aplicação rende mais no prazo dado.",
    invGraficoLegendaEmpresa: "Empresa",
    invGraficoLegendaAplicacao: "Aplicação",
    invReceitaNecessariaAntes: (horizonte) => `Payback em ${horizonte} meses exige pelo menos `,
    invReceitaNecessariaDepois: " de vendas a mais por mês.",
    invReceitaAbaixo: " Estimativa abaixo do necessário.",
    invReceitaAcima: " Estimativa acima do necessário.",
    invRodapeNota: "Conta simples, sem inflação nem imposto sobre a aplicação. Decisão apertada: consulte o contador.",
  },
};
